#!/usr/bin/env python3
import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
L=Path(__file__).resolve().parent
rw=json.loads((L/'RW_RELATION_CENSUS_RESULT_V2.json').read_text())
ep=json.loads((L/'EPMC_RIGHTS_TYPED_FEASIBILITY_RESULT_V2.json').read_text())
now=datetime.now(timezone.utc).isoformat()
rows=rw['row_level_structural_counts']; rs=rw['relation_census']['status_counts']; fs=rw['family_census']['status_counts']; cells=ep['typed_feasibility_cells']; stages=ep['relation_feasibility']['status_counts']
result={
 'schema_version':'orion.p1.rw-epmc-relation-feasibility-result.v2','identity':'P1.RW.EPMC.RIGHTS.RELATION.CENSUS.COMBINED.RESULT.V2','generated_at_utc':now,'authority':'FINITE_PINNED_OUTCOME_BLIND_METADATA_RELATION_AND_RIGHTS_FEASIBILITY_ONLY',
 'protocol_freezes':[
  {'path':'RELATION_CENSUS_PROTOCOL_V2.json','sha256':'af8b7373a6ce2de34d0a5185d5d70410b46fbda44af996f922f9fa098e3117dc'},
  {'path':'RELATION_CENSUS_PROTOCOL_V2_AMENDMENT_A.json','sha256':'6932397a6c85ebc8586a9903f55507a9412222d5fd7fa441d2ba1660989b3596'},
  {'path':'RELATION_CENSUS_PROTOCOL_V2_AMENDMENT_B.json','sha256':'ce18a89594b4e850e09204ce5b66695340239b9a25b4f09475e660e8376cb4aa'},
  {'path':'EPMC_AGGREGATE_RIGHTS_REDUCER_PREFREEZE_V2.json','sha256':'4a80d9408aa594141f1d9c475a2145b7349ae129a006117c832830071db898c9'},
  {'path':'EPMC_CORE_LICENSE_GATEWAY_AMENDMENT_C_V2.json','sha256':'70d0591c353fa156d5be4dcfc7640649b10bcc3a6578e98d0f24b538c6783d9d'}],
 'pinned_source':rw['source'],
 'rw_structural_census':{
  'data_rows':rows['rows_total'],'explicit_both_endpoint_rows':rows['explicit_both_endpoints_rows'],'invalid_record_id_rows':rows['invalid_record_id'],'missing_both_endpoint_rows':rows['missing_both_endpoints'],'missing_original_endpoint_rows':rows['missing_original_endpoint'],'missing_notice_endpoint_rows':rows['missing_notice_endpoint'],
  'self_relation_occurrences':rs['CANNOT_CHECK_SELF_RELATION_OCCURRENCES'],'duplicate_relation_later_occurrences':rs['DUPLICATE_RELATION_KEY_LATER_OCCURRENCES'],'identifier_alias_ambiguous_relations':rs['CANNOT_CHECK_IDENTIFIER_ALIAS_AMBIGUITY'],'original_notice_role_collision_relations':rs['CANNOT_CHECK_ORIGINAL_NOTICE_ROLE_COLLISION'],
  'admitted_explicit_cc0_relations':rw['relation_census']['admitted_explicit_rw_cc0_relations'],'admitted_source_connected_cc0_families':rw['family_census']['admitted_explicit_rw_cc0_source_families'],
  'family_component_adversities':{'identifier_alias_ambiguity':fs['CANNOT_CHECK_IDENTIFIER_ALIAS_AMBIGUITY'],'original_notice_role_collision':fs['CANNOT_CHECK_ORIGINAL_NOTICE_ROLE_COLLISION']}
 },
 'epmc_exact_pair_rights_census':{
  'admitted_rw_relations_input':ep['input']['admitted_rw_cc0_relations'],'cannot_check_no_both_endpoint_pmid':stages['CANNOT_CHECK_NO_BOTH_PMID_FOR_BOUNDED_REDUCER'],'both_endpoint_pmid_relations':ep['input']['relations_with_both_endpoint_pmids'],'cannot_check_epmc_allowlist_search_absence':stages['CANNOT_CHECK_EPMC_ALLOWLIST_SEARCH_ABSENCE'],'exact_both_endpoint_rights_pass_relations':ep['relation_feasibility']['exact_both_endpoint_content_rights_pass_relations'],'exact_rights_pass_source_families':ep['relation_feasibility']['exact_rights_pass_unique_source_families'],'exact_endpoint_license_counts':ep['epmc_core_exact_rights']['normalized_status_counts'],
  'absence_is_negative':False
 },
 'source_native_typed_feasibility_cells':cells,
 'positive_theorem':'For the pinned 2026-08-21 Retraction Watch CC0 snapshot, the frozen seven-field gateway identifies 49,878 structurally admitted explicit metadata relations in 42,924 source-connected families. Within the bounded PMID-addressable subframe, official Europe PMC metadata gives exact allowlisted licenses on both endpoints for 12,038 relations in 11,602 families. Retraction-notice, correction-or-erratum, and expression-of-concern provider strata each contain at least 20 unique families in both prospectively deterministic waves. Therefore a rights-valid, three-stratum public development pool exists at metadata level.',
 'claim_boundary':{
  'licensed':['finite pinned metadata-relation existence and prevalence','exact structural exclusion counts','existence of a rights-admissible PMID-addressable public relation pool','nonzero provider-native metadata strata and deterministic wave width'],
  'not_licensed':['case-text eligibility','minimal scientific terminal or action gold','causal responsibility or author intent','anti-leak candidate-view construct validity','matched controls or donor arms','model or comparator performance','protected score','naturalistic effect, transport, external validity or top-tier readiness'],
  'publication_type_is_gold':False,'missing_or_nonmatching_is_negative':False,'scientific_terminal_cells_assigned':0
 },
 'historical_terminal_preserved':'P1_NATURALISTIC_PUBLIC_PANEL_CANNOT_CHECK_RIGHTS_OR_CONSTRUCT_VALIDITY',
 'current_terminal':'P1_RW_EPMC_RIGHTS_VALID_RELATION_AND_SOURCE_NATIVE_TYPED_FEASIBILITY_PASS__SCIENTIFIC_ACTION_GOLD_AND_CONSTRUCT_VALIDITY_CANNOT_CHECK',
 'manuscript_integration':{'warranted':True,'scope':'ONE_NARROW_METADATA_FEASIBILITY_PARAGRAPH_ONLY','full_empirical_claim_warranted':False,'paper_top_tier_ready_from_this_result':False}
}
(L/'RESULT_V2.json').write_text(json.dumps(result,indent=2,sort_keys=True)+'\n')

theorem={'schema_version':'orion.p1.rw-epmc-feasibility-theorem.v2','identity':'P1.RW.EPMC.METADATA.FEASIBILITY.THEOREM.V2','premises':['Pinned RW blob identity and official CC0 metadata binding pass.','Only the seven frozen identifier/date fields are semantically opened.','Source-declared DOI-PMID aliases and explicit original-notice endpoints define relations; connected components define non-splittable source families.','Europe PMC core metadata supplies exact endpoint PMCID, OA/PMC flags and machine-readable license; no case-bearing field is used.','Provider publication types are aggregate metadata strata, not scientific terminals or gold.'],'finite_result':{'rw_relations':49878,'rw_families':42924,'exact_pair_rights_relations':12038,'exact_pair_rights_families':11602,'three_width_pass_strata':['EPMC_RETRACTION_NOTICE','EPMC_CORRECTION_OR_ERRATUM','EPMC_EXPRESSION_OF_CONCERN']},'theorem':'A rights-valid three-stratum development source universe exists for a future owner-separated P1 construct-validation study.','bound':'The theorem is point-identified only on the exact pinned metadata relations and frozen reducer. Every scientific-terminal, case-text, anti-leak, donor, model-effect and transport claim remains CANNOT_CHECK.','not_a_performance_theorem':True,'no_absence_as_negative':True}
(L/'FEASIBILITY_THEOREM_V2.json').write_text(json.dumps(theorem,indent=2,sort_keys=True)+'\n')

ledger=[
 {'id':'N01_HEADER_SCHEMA_DRIFT','status':'REPAIRED_WITH_ADVERSE_PRESERVED','result':'The 20 documented header names were followed by one unnamed terminal field, so the original exact-header gate failed.','cause':'Pinned CSV serialization contains an undocumented trailing column.','residual':'All 71,944 data rows had width 21 and the frozen Amendment B gateway required the terminal cell to be empty; zero nonempty terminal cells occurred.','next_discriminator':'On every future blob, refreeze and repeat the exact header plus uniformly-empty check before row semantics.'},
 {'id':'N02_INVALID_RECORD_ID','status':'EXCLUDED','result':'246 rows lacked a usable Record ID.','cause':'Source identifier missing under frozen normalization.','residual':'Never imputed from DOI, title or ordering.','next_discriminator':'Provider-issued corrected identifiers in a later pinned release.'},
 {'id':'N03_MISSING_ENDPOINTS','status':'CANNOT_CHECK','result':'2,683 rows lacked both endpoints; 2,504 lacked an original endpoint; 1,151 lacked a notice endpoint.','cause':'The seven-field source metadata did not supply both source-native endpoints.','residual':'No title, author, date or fuzzy relation inference was used.','next_discriminator':'An official provider-native endpoint relation or rights-owner attestation.'},
 {'id':'N04_SELF_RELATIONS','status':'CANNOT_CHECK','result':'14,144 explicit-both-endpoint row occurrences collapsed original and notice to the same source-declared identity.','cause':'The endpoint fields do not identify two distinct artifacts after exact aliasing.','residual':'They cannot support an original-notice pair.','next_discriminator':'A provider correction binding a distinct notice identifier.'},
 {'id':'N05_DUPLICATE_RELATIONS','status':'DEDUPLICATED','result':'198 later row occurrences repeated an already frozen relation key.','cause':'Multiple source rows encode one exact directed identifier relation.','residual':'Only one relation was counted; row multiplicity is not sample size.','next_discriminator':'None for census; retain component-level family grouping in any study.'},
 {'id':'N06_IDENTIFIER_ALIAS_AMBIGUITY','status':'CANNOT_CHECK','result':'302 unique relations and 406 connected components failed DOI-PMID alias consistency.','cause':'A DOI co-occurred with multiple PMIDs or a PMID with multiple DOIs.','residual':'No equivalence direction was guessed.','next_discriminator':'Official identifier resolution with immutable response receipts.'},
 {'id':'N07_ORIGINAL_NOTICE_ROLE_COLLISION','status':'CANNOT_CHECK','result':'838 unique relations were in role-collision components; 13,451 source components contained an identity used as both original and notice, including self/update chains.','cause':'The same identifier occupies both endpoint roles somewhere in the visible relation graph.','residual':'Connected families were not split to manufacture independence.','next_discriminator':'Provider-native version-chain semantics prospectively frozen before reclassification.'},
 {'id':'N08_NO_BOTH_PMID','status':'CANNOT_CHECK_BOUNDED_ROUTE','result':'20,110 otherwise admitted RW relations lacked PMIDs on both endpoints for the frozen batch reducer.','cause':'The bounded Europe PMC idlist/core reducer was PMID-addressable only.','residual':'DOI presence is preserved in the RW census; this is not absence from Europe PMC or a rights failure.','next_discriminator':'Prospectively freeze an official DOI-to-PMCID resolver and rerun only this residual.'},
 {'id':'N09_EPMC_ALLOWLIST_SEARCH_ABSENCE','status':'CANNOT_CHECK','result':'17,730 both-PMID relations lacked an allowlist search match on one or both endpoints.','cause':'At least one endpoint was not returned under the frozen Europe PMC OA/PMC/license search predicate.','residual':'No incompatible license or missing article was inferred.','next_discriminator':'Exact endpoint resolution plus article-specific rights metadata or permission.'},
 {'id':'N10_TYPE_OTHER_OR_AMBIGUOUS','status':'CANNOT_CHECK_TYPED_CELL','result':'11 exact-rights relations were outside the three frozen provider strata and 1 matched multiple strata.','cause':'Provider publication-type metadata was absent/outside-band or nonunique.','residual':'No nearest action or scientific terminal was imputed.','next_discriminator':'Owner-separated source-native type adjudication under a frozen mapping.'},
 {'id':'N11_SCIENTIFIC_TERMINAL_GOLD','status':'CANNOT_CHECK','result':'0 scientific terminal cells were assigned; 0 cases were adjudicated.','cause':'Publication type and retraction metadata are not minimal scientific responsibility-to-authority gold.','residual':'No case text, causal responsibility, author intent or action column was opened.','next_discriminator':'Rights-cleared case dossiers and sealed, owner-separated minimal-transition adjudication.'},
 {'id':'N12_CONSTRUCT_AND_EFFECT','status':'CANNOT_CHECK','result':'0 anti-leak candidate views, donor-complete arms, information-equivalent arms, model outputs, protected scores or effect estimates exist.','cause':'This lane stops at source-universe feasibility.','residual':'The V1 overall construct-validity terminal remains active.','next_discriminator':'Freeze and execute owner-separated construct validation on the three width-pass strata.'}
]
neg={'schema_version':'orion.negative-result-ledger.v2','identity':'P1.RW.EPMC.NEGATIVE.RESULT.LEDGER.V2','generated_at_utc':now,'entries':ledger,'principle':'Every adverse result remains a research problem with a next discriminator. Missing or ambiguous metadata is CANNOT_CHECK, never an empirical or scientific negative.'}
(L/'NEGATIVE_RESULT_LEDGER_V2.json').write_text(json.dumps(neg,indent=2,sort_keys=True)+'\n')

md=f'''# P1 V2 outcome-blind rights/relation census\n\n## Result\n\n**Terminal:** `{result['current_terminal']}`\n\nThe pinned CC0 Retraction Watch snapshot supports an exact finite metadata theorem: **49,878** structurally admitted explicit original-notice relations in **42,924** source-connected families. The bounded official Europe PMC reducer identifies **12,038** relations in **11,602** families for which both endpoints have exact allowlisted OA licences. No case text, RW action/outcome column, scientific terminal, model output or protected score was opened.\n\n## Exact census and exclusions\n\n| Stage | Count | Interpretation |\n|---|---:|---|\n| Pinned rows | 71,944 | exact blob, 65,984,968 bytes |\n| Explicit endpoint rows | 65,360 | before alias/component gates |\n| Missing Record ID | 246 | excluded |\n| Missing both endpoints | 2,683 | CANNOT_CHECK |\n| Missing original endpoint | 2,504 | CANNOT_CHECK |\n| Missing notice endpoint | 1,151 | CANNOT_CHECK |\n| Self-relation occurrences | 14,144 | CANNOT_CHECK |\n| Duplicate relation occurrences | 198 | deduplicated |\n| Alias-ambiguous relations | 302 | CANNOT_CHECK |\n| Role-collision relations | 838 | CANNOT_CHECK |\n| **Admitted CC0 relations** | **49,878** | positive metadata relation census |\n| **Admitted CC0 families** | **42,924** | connected source families |\n\nThe bounded PMID route left **20,110** admitted relations CANNOT_CHECK because both endpoint PMIDs were unavailable. Of the **29,768** both-PMID relations, **12,038** passed exact pair rights and **17,730** had no frozen allowlist-search match on one or both endpoints. The latter is CANNOT_CHECK—not evidence of incompatible rights or nonexistence.\n\n## Source-native metadata feasibility cells\n\n| Provider stratum | exact-rights relations | unique families | primary | replication | >=20 each wave |\n|---|---:|---:|---:|---:|:---:|\n'''
for c in ['EPMC_RETRACTION_NOTICE','EPMC_CORRECTION_OR_ERRATUM','EPMC_EXPRESSION_OF_CONCERN','EPMC_OTHER_OR_CANNOT_CHECK','EPMC_AMBIGUOUS_MULTIPLE_STRATA']:
 x=cells[c]; md+=f"| {c} | {x['exact_rights_pass_relations']:,} | {x['unique_source_families']:,} | {x['primary_families']:,} | {x['replication_families']:,} | {'PASS' if x['minimum_20_families_each_wave_pass'] else 'FAIL'} |\n"
md+='''\nFamily counts across rows are not additive because one connected family may contain more than one relation/type. Retraction, correction/erratum and expression-of-concern each pass the prospectively deterministic 20-family-per-wave feasibility width. These are provider metadata strata, not P1 scientific action terminals or gold.\n\n## Strongest licensed claim\n\nA rights-valid, source-connected, three-stratum public **development pool exists** at metadata level. This closes the source-universe existence/width gap for a future construct-validation study. It does not close construct validity or demonstrate the P1 relation improves decisions.\n\n## Immutable boundary\n\n- 0 case texts or action/outcome columns opened.\n- 0 scientific terminal assignments or adjudicated cases.\n- 0 candidate/comparator executions and 0 protected scores.\n- No causal responsibility, author-intent, model-effect, transport or external-authority claim.\n- The V1 terminal `P1_NATURALISTIC_PUBLIC_PANEL_CANNOT_CHECK_RIGHTS_OR_CONSTRUCT_VALIDITY` remains active for the unexecuted scientific panel.\n\n## Manuscript decision\n\n**One narrow metadata-feasibility paragraph is warranted.** A full empirical/result claim or top-tier-readiness claim is not.\n'''
(L/'RESULTS_V2.md').write_text(md)

thmd='''# P1 V2 feasibility theorem and bound\n\n## Finite theorem\n\nOn the exact 2026-08-21 Retraction Watch CC0 blob, under the prospectively frozen seven-field gateway and source-declared alias/component rules, there are **49,878** admitted explicit metadata relations in **42,924** connected families. Official Europe PMC metadata supplies exact allowlisted endpoint licences for **12,038** relations in **11,602** families. Retraction-notice, correction/erratum and expression-of-concern strata each contain at least 20 families in both deterministic waves. Thus a rights-valid three-stratum public development source universe exists.\n\n## Bound\n\nThis theorem is point-identified only on the finite pinned metadata relation set and the frozen reducer. It is not a theorem about case eligibility, scientific actions, causal responsibility, anti-leak evidence, system performance, naturalistic effect, transport or external validity. Every relation outside the exact-rights subframe, and every scientific terminal, remains set-valued/CANNOT_CHECK unless separately certified.\n'''
(L/'FEASIBILITY_THEOREM_V2.md').write_text(thmd)

nmd='# P1 V2 negative-result ledger\n\nEvery item remains visible; no absence is converted into a negative.\n\n'
for e in ledger:
 nmd+=f"## {e['id']} — {e['status']}\n\n- **Result:** {e['result']}\n- **Cause:** {e['cause']}\n- **Residual:** {e['residual']}\n- **Next discriminator:** {e['next_discriminator']}\n\n"
(L/'NEGATIVE_RESULT_LEDGER_V2.md').write_text(nmd)

rec='''# P1 V2 manuscript-integration recommendation\n\n## Verdict\n\n`NARROW_PARAGRAPH_WARRANTED__FULL_EMPIRICAL_INTEGRATION_NOT_WARRANTED`\n\nThe new result is materially positive: it replaces “candidate counts only” with a rights-valid exact relation/family census and three source-native metadata strata of adequate deterministic wave width. It still stops before case content, scientific-terminal gold and construct validation.\n\n## Warranted paragraph\n\n> Under a prospectively frozen outcome-blind metadata protocol, the pinned CC0 Retraction Watch snapshot yielded 49,878 structurally admitted explicit update relations in 42,924 source-connected families. A bounded official Europe PMC rights reducer identified 12,038 relations in 11,602 families with exact allowlisted licences on both endpoints. Retraction-notice, correction/erratum, and expression-of-concern metadata strata each exceeded 20 independent families in both deterministic waves. This establishes feasibility of a rights-valid three-stratum public development pool, not scientific-action gold, construct validity, system effect, or external authority.\n\nDo not integrate the adverse counts as claims of source failure; they are CANNOT_CHECK/exclusion accounting and future discriminators.\n'''
(L/'MANUSCRIPT_INTEGRATION_RECOMMENDATION_V2.md').write_text(rec)
print('built')
