#!/usr/bin/env python3
"""Native ORION-Q authority gate for MAX-R4E QG-skill replay calibration."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];A=ROOT/"artifacts/orion-q-max-r4e-qg-skill-replay.json";G=ROOT/"artifacts/orion-q-max-r4e-qg-skill-replay-generic.json";P=ROOT/"development/orion-q-max-r0/MAX_R4E_QG_SKILL_REPLAY_CALIBRATION_PROTOCOL_V1.md";OUT=ROOT/"artifacts/orion-q-max-r4e-qg-skill-replay-native.json";TOKEN="ORIONQ_MAX_R4E_QG_REPLAY_NATIVE=";POS="MAX_R4E_QG_SKILLS_HAVE_REAL_COMPILER_OPERATIONAL_VALUE__REPLAY_CALIBRATED"
def canon(v):return json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False)
def valid(r):u={k:v for k,v in r.items() if k!="result_digest"};return r.get("result_digest")==hashlib.sha256(canon(u).encode()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--analyzer",type=Path,default=A);ap.add_argument("--generic",type=Path,default=G);ap.add_argument("--output",type=Path,default=OUT);ns=ap.parse_args();a=json.loads(ns.analyzer.read_text());g=json.loads(ns.generic.read_text());false_keys=("MAX_R4E_QG_SKILLS_COMPILER_GENERAL","MAX_R4E_QG_SKILLS_REAL_METHOD_SEARCH_VALUE","MAX_R4E_QG_SKILLS_BROAD_QUANTUM_RESEARCH_TRANSFER","REAL_QUANTUM_SUPERIORITY_AUTHORIZED","NOVELTY_AUTHORIZED")
 checks={"analyzer":a.get("terminal")==POS and a.get("MAX_R4E_QG_SKILLS_REAL_COMPILER_OPERATIONAL_VALUE_REPLAY") is True and valid(a),"generic":g.get("decision")=="ACCEPT_REAL_COMPILER_REPLAY_VALUE" and g.get("all_checks") is True,"digest":g.get("source_result_digest")==a.get("result_digest"),"protocol":a.get("protocol_sha256")==hashlib.sha256(P.read_bytes()).hexdigest(),"actions":a.get("required_actions")=={"R6I":"RESTRICT_TO_PROVED_SUPPORT1","SixLCU":"USE_MINIMAL_EXACT_K1D1_PREDICATE","StabPrep":"REJECT_ZERO_ERROR_IN_FROZEN_VOCAB__ESCALATE_REPRESENTATION"},"scope":all(a.get(k) is False and g.get(k) is False for k in false_keys),"positive_work_surface":a.get("r6i_support_localization",{}).get("minimum_pair_reduction_ratio",0)>1 and a.get("sixlcu_minimal_predicate",{}).get("higher_order_raw_conjunctions_avoidable_for_minimal_exact_classifier_task",0)>0 and a.get("stabprep_information_barrier",{}).get("mixed_cells")==12}
 ok=all(checks.values());out={"schema":"ORIONQ.MAXR4E.QGSkillReplayNative.v1","decision":"ACCEPT_REAL_COMPILER_REPLAY_VALUE" if ok else "REJECT","responsibility":"REAL_COMPILER_REPLAY_OPERATIONAL_VALUE_ONLY__NO_TRANSFER_SUPERIORITY" if ok else "CANNOT_CHECK","all_checks":bool(ok),"checks":checks,"source_result_digest":a.get("result_digest"),"MAX_R4E_QG_SKILLS_REAL_COMPILER_OPERATIONAL_VALUE_REPLAY":bool(ok),"MAX_R4E_QG_SKILLS_COMPILER_GENERAL":False,"MAX_R4E_QG_SKILLS_REAL_METHOD_SEARCH_VALUE":False,"MAX_R4E_QG_SKILLS_BROAD_QUANTUM_RESEARCH_TRANSFER":False,"REAL_QUANTUM_SUPERIORITY_AUTHORIZED":False,"NOVELTY_AUTHORIZED":False};ns.output.parent.mkdir(parents=True,exist_ok=True);ns.output.write_text(json.dumps(out,indent=2,sort_keys=True)+"\n");print(TOKEN+canon({"decision":out["decision"],"responsibility":out["responsibility"]}));return 0
if __name__=="__main__":raise SystemExit(main())
