#!/usr/bin/env python3
"""Independent generic ORION verifier for MAX-R4E-B1 SixLCU different-family transfer."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
SRC=ROOT/"artifacts/orion-q-max-r4eb1-sixlcu-label-value.json";SKILL=ROOT/"research/extensions/orion-q/MAX_R4EA_AUTHORITY_INDEXED_ROUTER_RESULTS.json";PRIOR=ROOT/"research/extensions/orion-q/MAX_R4EB0_HELDOUT_QG32_RESULTS.json";TARGET=ROOT/"research/extensions/orion-qg/QG33_SIXLCU_LABEL_VALUE_RESULTS.json";PROTO=ROOT/"development/orion-q-max-r0/MAX_R4EB1_SIXLCU_LABEL_VALUE_FORECAST_PROTOCOL.md";OUT=ROOT/"artifacts/orion-q-max-r4eb1-generic-verification.json";TOKEN="ORIONQ_MAX_R4EB1_GENERIC=";POS="MAX_R4EB1_QG_DERIVED_AUTHORITY_SKILL_TRANSFERS_PROSPECTIVELY_TO_DIFFERENT_COMPILER_FAMILY"
def canon(v):return json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False)
def valid(r):
 u={k:v for k,v in r.items() if k!="result_digest"};return r.get("result_digest")==hashlib.sha256(canon(u).encode()).hexdigest()
def independent_adjudication(t):
 stronger=("ALL_N_VALUE_THEOREM","GLOBAL_PREDICATE_MINIMALITY","NEW_FEATURE_VOCABULARY_AUTHORITY","novelty_authority","physical_quantum_advantage_claim")
 boundary=all(t.get(k) is False for k in stronger);green=t.get("both_accept") is True;complete=t.get("COMPLETE_N2_DOMAIN") is True;noinv=t.get("NO_POST_OUTCOME_FEATURE_INVENTION") is True;label=t.get("LABEL_QUOTIENT_VALUE_SUFFICIENT")
 if green and complete and noinv and boundary and label is False:return "BORNE_OUT_LABEL_VALUE_SEPARATION"
 if green and complete and noinv and boundary and label is True:return "BORNE_OUT_LABEL_VALUE_SUFFICIENCY"
 return "CANNOT_CHECK"
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--input",type=Path,default=SRC);ap.add_argument("--output",type=Path,default=OUT);ns=ap.parse_args();src=json.loads(ns.input.read_text());skill=json.loads(SKILL.read_text());prior=json.loads(PRIOR.read_text());t=json.loads(TARGET.read_text());adj=independent_adjudication(t);positive=adj.startswith("BORNE_OUT_");full=t.get("FULL_FEATURE_VECTOR_VALUE_SUFFICIENT");secondary="FULL_FEATURE_VALUE_SUFFICIENT" if full is True else ("FULL_FEATURE_VALUE_INSUFFICIENT_AND_ESCALATION_REQUIRED" if full is False else "FULL_FEATURE_STATUS_UNKNOWN")
 checks={"source_digest":valid(src),"protocol_bound":src.get("protocol_sha256")==hashlib.sha256(PROTO.read_bytes()).hexdigest(),"skill_green":skill.get("both_accept") is True and skill.get("AUTHORITY_INDEXED_ROUTER_REAL_RECEIPT_CALIBRATION") is True,"prior_green":prior.get("both_accept") is True and prior.get("MAX_R4EB0_HELDOUT_TARE_TRANSFER") is True,"adjudication_match":src.get("adjudication")==adj,"secondary_match":src.get("secondary_full_feature_adjudication")==secondary,"positive_terminal_match":(src.get("terminal")==POS)==positive,"number_free":src.get("forecast_number_present") is False and src.get("forecast_outcome_guess_present") is False,"hidden_outcome_free":src.get("hidden_outcome_dependency_count")==0,"false_authority_zero":src.get("false_authority_count")==0,"no_feature_invention":src.get("post_outcome_feature_invention") is False,"compiler_general_consistency":src.get("MAX_R4E_QG_SKILLS_COMPILER_GENERAL") is positive,"scope":src.get("MAX_R4E_QG_SKILLS_REAL_METHOD_SEARCH_VALUE") is False and src.get("MAX_R4E_QG_SKILLS_BROAD_QUANTUM_RESEARCH_TRANSFER") is False and src.get("AUTONOMOUS_SKILL_SELECTION_AUTHORITY") is False and src.get("GENERAL_QUANTUM_SCIENCE_IMPROVEMENT") is False and src.get("NOVELTY_AUTHORITY") is False}
 ok=all(checks.values());out={"schema":"ORIONQ.MAXR4EB1.GenericVerification.v1","decision":"ACCEPT_DIFFERENT_COMPILER_ACTION_TRANSFER" if ok and positive else ("ACCEPT_NONPOSITIVE_ADJUDICATION" if ok else "REJECT"),"all_checks":bool(ok),"checks":checks,"independent_adjudication":adj,"independent_secondary":secondary,"positive_transfer":bool(ok and positive),"source_result_digest":src.get("result_digest"),"MAX_R4E_QG_SKILLS_COMPILER_GENERAL":bool(ok and positive),"MAX_R4E_QG_SKILLS_REAL_METHOD_SEARCH_VALUE":False,"MAX_R4E_QG_SKILLS_BROAD_QUANTUM_RESEARCH_TRANSFER":False,"AUTONOMOUS_SKILL_SELECTION_AUTHORITY":False,"GENERAL_QUANTUM_SCIENCE_IMPROVEMENT":False,"NOVELTY_AUTHORITY":False};ns.output.parent.mkdir(parents=True,exist_ok=True);ns.output.write_text(json.dumps(out,indent=2,sort_keys=True)+"\n");print(TOKEN+canon({"decision":out["decision"],"adjudication":adj,"secondary":secondary,"positive":out["positive_transfer"],"compiler_general":out["MAX_R4E_QG_SKILLS_COMPILER_GENERAL"]}));return 0
if __name__=="__main__":raise SystemExit(main())
