"""Protected scientific objective revision without reward self-authoring (#288)."""

from .benchmark import HiddenIntentBenchmark, load_hidden_intent_benchmark
from .process import (
    GoalEvolutionSession,
    ProcessRefusal,
    ProcessStage,
    admit_or_reject,
    diagnose,
    discriminate,
    freeze_revision,
    observe,
    optimize,
    propose_objective_revision,
    protected_compare,
    start_session,
)
from .protocol import PROTOCOL_ID, LayerKind, load_protocol, protocol_hash, protocol_layers
from .revision import (
    AuthorityProvenance,
    ObjectiveRevisionArchive,
    ObjectiveRevisionRecord,
    ObjectiveRevisionStatus,
    ObjectiveVersion,
    ResponsibilityClass,
    RevisionStatusEvent,
    append_status_event,
    append_version,
    current_status,
    empty_archive,
    register_revision,
)

__all__ = [
    "PROTOCOL_ID",
    "AuthorityProvenance",
    "GoalEvolutionSession",
    "HiddenIntentBenchmark",
    "LayerKind",
    "ObjectiveRevisionArchive",
    "ObjectiveRevisionRecord",
    "ObjectiveRevisionStatus",
    "ObjectiveVersion",
    "ProcessRefusal",
    "ProcessStage",
    "ResponsibilityClass",
    "RevisionStatusEvent",
    "admit_or_reject",
    "append_status_event",
    "append_version",
    "current_status",
    "diagnose",
    "discriminate",
    "empty_archive",
    "freeze_revision",
    "load_hidden_intent_benchmark",
    "load_protocol",
    "observe",
    "optimize",
    "propose_objective_revision",
    "protected_compare",
    "protocol_hash",
    "protocol_layers",
    "register_revision",
    "start_session",
]
