#!/usr/bin/env python3
"""Render the external Wide comparison table and its LaTeX section from records.

Result-bearing tables in this paper are generated from archived records, never
transcribed, so this reads the scored summary produced by
``score_wide_comparison.py`` and emits both a markdown table for the repository
and a LaTeX fragment for the manuscript.

Three properties are enforced rather than assumed, because each corresponds to a
way a table like this normally lies:

* the caption states N, the aggregation unit, the uncertainty definition and the
  result's role, so a reader cannot mistake a descriptive number for a
  confirmatory one;
* the ``UNDERPOWERED`` label travels with the number it qualifies, in the caption
  and in the table, rather than living in a methods paragraph nobody re-reads;
* nothing renders at all when the summary is missing, empty or carries no
  verdict. A results table that quietly prints zeros is worse than an absent one.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

PAPER = Path(__file__).resolve().parent.parent


class RefusedToRender(RuntimeError):
    """Raised instead of emitting a table that would misrepresent the evidence."""


def _require(summary: dict[str, Any]) -> None:
    for key in ("systems", "comparison", "verdict", "precision", "cost_ratio"):
        if key not in summary:
            raise RefusedToRender(f"summary is missing {key!r}; nothing may be rendered")
    if not summary["systems"]:
        raise RefusedToRender("summary contains no systems")
    for system_id, block in summary["systems"].items():
        metrics = block.get("exact_metrics") or {}
        if "avg_iou" not in metrics:
            raise RefusedToRender(
                f"{system_id} has no avg_iou; the official exact metric is required"
            )


def _fmt(value: Any, digits: int = 4) -> str:
    if isinstance(value, (int, float)):
        return f"{value:.{digits}f}" if isinstance(value, float) else str(value)
    return str(value)


def caption(summary: dict[str, Any]) -> str:
    precision = summary["precision"]
    comparison = summary["comparison"]
    verdict = summary["verdict"]
    cost = summary["cost_ratio"]
    label = " Reported UNDERPOWERED per the frozen plan." if verdict.get("underpowered_label") else ""
    return (
        f"AutoResearchBench Wide, official scorer at pinned commit "
        f"{summary['pinned_upstream_commit'][:12]}. N={precision['n']} paired tasks; the "
        f"aggregation unit is the task and repeats nest within task. Intervals are "
        f"{comparison['interval_definition']} with {comparison['resamples']} resamples at "
        f"seed {comparison['seed']}. Budgets are matched at "
        f"{cost['baseline_requests_per_task']} provider requests per task per system "
        f"(measured consumption ratio {cost['ratio']}, ceiling {cost['ceiling']}). "
        f"Achieved half-width {precision['achieved_half_width']} "
        f"({precision['tier']}).{label} Decision rule outcome: {verdict['outcome']}. "
        f"The sampled max-IoU-at-k family is excluded: upstream draws it unseeded."
    )


def markdown(summary: dict[str, Any]) -> str:
    _require(summary)
    rows = ["| system | avg_iou | avg_recall | avg_precision | scored tasks | requests/task |",
            "|---|---|---|---|---|---|"]
    manifest_systems = summary.get("run_manifest", {}).get("systems", {})
    for system_id, block in summary["systems"].items():
        metrics = block["exact_metrics"]
        requests = manifest_systems.get(system_id, {}).get("provider_requests_per_task", "n/a")
        rows.append(
            f"| `{system_id}` | {_fmt(metrics.get('avg_iou'))} | "
            f"{_fmt(metrics.get('avg_recall'))} | {_fmt(metrics.get('avg_precision'))} | "
            f"{block.get('scored_tasks', 'n/a')} | {requests} |"
        )
    comparison = summary["comparison"]
    verdict = summary["verdict"]
    lines = [
        "# Table P2-2-external — AutoResearchBench Wide, matched budget",
        "",
        "Generated by `scripts/render_wide_comparison.py`. Do not edit by hand.",
        "",
        *rows,
        "",
        f"**Paired difference (candidate − baseline):** {_fmt(comparison['mean_difference'])} "
        f"[{_fmt(comparison['ci_low'])}, {_fmt(comparison['ci_high'])}]",
        "",
        f"**Verdict:** `{verdict['outcome']}` — {verdict['reason']}",
        "",
        f"**Underpowered label:** {'yes' if verdict.get('underpowered_label') else 'no'}"
        f" — {verdict.get('underpowered_note', '')}",
        "",
        "## Caption of record",
        "",
        caption(summary),
        "",
    ]
    return "\n".join(lines)


def latex(summary: dict[str, Any]) -> str:
    _require(summary)
    manifest_systems = summary.get("run_manifest", {}).get("systems", {})
    body = []
    for system_id, block in summary["systems"].items():
        metrics = block["exact_metrics"]
        requests = manifest_systems.get(system_id, {}).get("provider_requests_per_task", "n/a")
        body.append(
            f"\\idt{{{system_id}}} & {_fmt(metrics.get('avg_iou'))} & "
            f"{_fmt(metrics.get('avg_recall'))} & {_fmt(metrics.get('avg_precision'))} & "
            f"{block.get('scored_tasks', 'n/a')} & {requests} \\\\"
        )
    comparison = summary["comparison"]
    verdict = summary["verdict"]
    return "\n".join(
        [
            "% Generated by scripts/render_wide_comparison.py. Do not edit by hand.",
            "\\begin{table}[t]",
            "\\centering\\small",
            "\\begin{tabular}{lrrrrr}",
            "\\hline",
            "system & IoU & recall & precision & tasks & req/task \\\\",
            "\\hline",
            *body,
            "\\hline",
            "\\end{tabular}",
            f"\\caption{{\\textbf{{Table P2-2-external.}} {caption(summary)}}}",
            "\\label{tab:p2-2-external}",
            "\\end{table}",
            "",
            f"\\noindent The paired difference on the official exact metric is "
            f"${_fmt(comparison['mean_difference'])}$ with a 95\\% interval of "
            f"$[{_fmt(comparison['ci_low'])}, {_fmt(comparison['ci_high'])}]$ over "
            f"{comparison['paired_tasks']} matched tasks. Under the pre-declared decision rule "
            f"this is \\idt{{{verdict['outcome']}}}: {verdict['reason']}.",
            "",
        ]
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--summary", type=Path, required=True)
    parser.add_argument(
        "--markdown-out",
        type=Path,
        default=PAPER / "evidence" / "external_results" / "TABLE_P2-2-external_wide.md",
    )
    parser.add_argument(
        "--latex-out",
        type=Path,
        default=PAPER / "manuscript" / "generated" / "wide_comparison_table.tex",
    )
    args = parser.parse_args(argv)

    summary = json.loads(args.summary.read_text(encoding="utf-8"))
    md, tex = markdown(summary), latex(summary)
    args.markdown_out.parent.mkdir(parents=True, exist_ok=True)
    args.latex_out.parent.mkdir(parents=True, exist_ok=True)
    args.markdown_out.write_text(md, encoding="utf-8")
    args.latex_out.write_text(tex, encoding="utf-8")
    print(f"wrote {args.markdown_out}")
    print(f"wrote {args.latex_out}")
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    raise SystemExit(main())
