#!/usr/bin/env python3
from pathlib import Path
import datetime as dt, hashlib, json
R=Path(__file__).resolve().parent
REPO=R.parents[1]
def load(name): return json.loads((R/name).read_text())
def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest()
protocol=load('PROTOCOL_V9.json'); freeze=load('PROTOCOL_FREEZE_RECEIPT_V9.json')
assert sha(R/'PROTOCOL_V9.json')==freeze['sha256']
pred=REPO/protocol['predecessor']['path']; assert sha(pred)==protocol['predecessor']['sha256']
payload=load('EXACT_EDGE_PAYLOAD_COMPARISON_V9.json')
payload_rows={x['frozen_index']:x for x in payload['rows']}
e190=load('EDGE_190_CONTENT_COMPARISON_V9.json')['receipts']['compare_archive_pre_joss_main']
r190=load('EDGE_190_COMMIT_RIGHTS_V9.json')
lineage=load('LINEAGE_NATURAL_PAIR_AUTHORITY_V9.json')
assert payload_rows[165]['exact_normalized_manifest_equal'] is True
assert payload_rows[165]['archive_file_count']==payload_rows[165]['commit_file_count']==293
assert e190['equal'] is True and e190['counts']==[355,355]
assert r190['byte_equal'] is True
rows=[
 {'frozen_index':36,'repository':'jaxionproject/jaxion','domain':'SCIENTIFIC_SOFTWARE','verdict':'REMAINS_CANNOT_CHECK','residual':'EXACT_ARCHIVE_VERSION_DOI_RELATION_AND_ARCHIVE_ROOT_TO_TAG_COMMIT_IDENTITY_CANNOT_CHECK','new_evidence':'Current provider pass still exposes concept DOI 10.5281/zenodo.21221061 through child 10.5281/zenodo.21221062 with no exact 0.0.3 version field, while GitHub binds tag 0.0.3 to 069ab4f56d100d765d46c594ac1b06add7e49f9e. The archive is a later repository state, not the exact tag root.','next_discriminator':'Zenodo/provider correction must bind the frozen DOI to 0.0.3 and authenticate the archive root to commit 069ab4f56d100d765d46c594ac1b06add7e49f9e.'},
 {'frozen_index':91,'repository':'nutritionallungimmunity/pai','domain':'SCIENTIFIC_SOFTWARE','verdict':'REMAINS_CANNOT_CHECK','residual':'ARCHIVE_TO_ACCEPTED_TAG_COMMIT_IDENTITY_CONTRADICTED_BY_EMBEDDED_GIT_HEAD','new_evidence':'The checksum-bound archive embeds a complete Git repository whose HEAD, local main and origin/main all authenticate aa021231cdafb6d74ce9ab5f55f824a3032058a4. The accepted v1.0.0 commit 9fa30e9f405de4446c792bd59cb7c5a4bb7ecb59 is absent from the embedded object store. The archive has 209 extra paths and one differing common path relative to the tag commit.','next_discriminator':'A corrected exact archive for v1.0.0 or provider-authenticated statement that binds the frozen bytes to tag commit 9fa30e9f405de4446c792bd59cb7c5a4bb7ecb59; current bytes authenticate a different HEAD.'},
 {'frozen_index':133,'repository':'artefactory/woodtapper','domain':'SCIENTIFIC_SOFTWARE','verdict':'REMAINS_CANNOT_CHECK','residual':'SDIST_TO_FULL_COMMIT_AUTHENTICATED_BUILD_PROVENANCE_CANNOT_CHECK','new_evidence':'Zenodo and PyPI bind the same sdist SHA-256 b509f6469b9ff8888195751c811d689559f45e24aeb35bb173b9680c99c8dbf3. A local source build from tag commit 7ac6d23d504404c4004faad663f6b889427109e6 reproduces all 34 paths, but two generated C files differ. PyPI exposes no provenance attestation for the sdist.','next_discriminator':'Provider-native trusted-publisher/Sigstore provenance or an exact build receipt binding sdist hash b509f646... to commit 7ac6d23d..., including Cython/build versions.'},
 {'frozen_index':165,'repository':'alek050/databallpy','domain':'SCIENTIFIC_SOFTWARE','verdict':'RESOLVED_SAME_IDENTITY','accepted_identity_method':'EXACT_NORMALIZED_ZENODO_ARCHIVE_TO_GITHUB_IMMUTABLE_COMMIT_MANIFEST_EQUALITY','new_evidence':'The 106,471,934-byte checksum-bound Zenodo archive and GitHub immutable commit b52a049f685af3fc849359673c4ac183e7ccc5d3 have exactly 293 normalized paths; every path and byte hash is equal. V8 already bound exact v0.7.3 tag/release, version DOI and MIT rights at archive and commit.','repaired_gates':['archive_to_commit_content_or_authenticated_origin_identity'],'residual':None,'next_discriminator':'Closed.'},
 {'frozen_index':185,'repository':'mit-psfc/disruption-py','domain':'PHYSICAL_ENGINEERING','verdict':'REMAINS_CANNOT_CHECK','residual':'SDIST_PROJECTION_TO_TAG_COMMIT_AUTHENTICATED_BUILD_PROVENANCE_CANNOT_CHECK','new_evidence':'GitHub binds source tag v0.14 to commit dec5c58a3e3970bc6817f33efb615fea11057fce, whose pyproject version is 0.14.0. Zenodo and PyPI bind the same sdist SHA-256 775f92dbcbd6d1523db241494998e4b0867d51a84236feb7accc86b63b033a19. All 64 source paths common to the sdist and commit are byte-identical, but the sdist is a projection plus PKG-INFO; a local rebuild omitted three tracked ignored CSV files and no PyPI provenance attestation exists.','next_discriminator':'Provider-native build attestation binding the exact PyPI/Zenodo sdist hash to source tag v0.14/commit dec5c58..., including the tracked-ignored CSV inclusion state.'},
 {'frozen_index':190,'repository':'ugurdar/datadriftr','domain':'SCIENTIFIC_SOFTWARE','verdict':'RESOLVED_SAME_IDENTITY','accepted_identity_method':'EXACT_NORMALIZED_ZENODO_ARCHIVE_TO_GITHUB_IMMUTABLE_COMMIT_MANIFEST_EQUALITY','new_evidence':'GitHub current branch Atom exposes immutable commit 6bcb4fb83fccff05eb030b6a9e6af8e81d79dcbc. Its provider-native codeload ZIP and the checksum-bound Zenodo archive have exactly 355 normalized paths with identical bytes. The exact-commit LICENSE and archive LICENSE are byte-equal MIT (SHA-256 79dd70a104e1136db181d225335f5d4adfc3516e4124e647093de7db0bfb24bb). The missing 1.1.0 tag is no longer needed for source identity because the archive itself exactly names the full immutable content state.','repaired_gates':['exact_source_native_full_commit_identity','archive_to_commit_content_or_authenticated_origin_identity','accepted_commit_software_rights'],'residual':None,'next_discriminator':'Closed.'},
 {'frozen_index':199,'repository':'targene/targene-pipeline','domain':'LIFE_BIOMEDICAL','verdict':'REMAINS_CANNOT_CHECK','residual':'FULL_COMMIT_DISCOVERED_BUT_PROVIDER_NATIVE_REVISION_AUTHORITY_CANNOT_CHECK','new_evidence':'Outcome-free third-party GH Archive discovery identifies prefix 0f8b2db as full push head 0f8b2dbca06a3bb7031de9058ee9882995e04412 on 2026-03-24. However current GitHub commit, codeload and raw-license endpoints all return 404, and Software Heritage reports that full revision absent. SWH authenticates only deposit release -> outer directory ba731454... -> inner directory 178315b..., not a revision. The third-party event cannot be promoted to provider-native source authority.','next_discriminator':'GitHub restoration or Software Heritage ingestion of full revision 0f8b2dbca06a3bb7031de9058ee9882995e04412 with directory 178315b57afafc1f20ab9929b4de893430524c62 and exact-commit rights.'}
]
closed=[x['frozen_index'] for x in rows if x['verdict']=='RESOLVED_SAME_IDENTITY']
remaining=[x['frozen_index'] for x in rows if x['verdict']!='RESOLVED_SAME_IDENTITY']
assert closed==[165,190] and remaining==[36,91,133,185,199]
result={
 'schema_version':'orion.p4.exact-edge-lineage-authority.v9.result',
 'identity':protocol['identity'],'finished_at':dt.datetime.now(dt.timezone.utc).isoformat(),
 'predecessor_exact_bridge':'73/80','v9_closed_count':len(closed),'v9_closed_indices':closed,'v9_remaining_count':len(remaining),'v9_remaining_indices':remaining,'cumulative_exact_bridge':'75/80',
 'cumulative_exact_by_domain':{'EARTH_ENVIRONMENT':5,'LIFE_BIOMEDICAL':6,'SCIENTIFIC_SOFTWARE':60,'PHYSICAL_ENGINEERING':4},
 'rows':rows,
 'lineage_authority':lineage['adjudication']|{'counts':lineage['counts']},
 'natural_pair_and_scientific_boundary':{'eligible_natural_pairs_added':0,'author_lineage_adjudications_added':0,'external_custody_added':False,'comparator_outcomes_accessed':False,'scientific_authority_granted':False,'programme_terminal':'P4_NATURAL_PAIR_SOURCE_TRANSPORT_CANNOT_CHECK'},
 'evidence':{name:{'sha256':sha(R/name)} for name in ['PROTOCOL_V9.json','PRIMARY_AUTHORITY_PROBE_RECEIPT_V9.json','EXACT_EDGE_PAYLOAD_COMPARISON_V9.json','EDGE_91_EMBEDDED_GIT_AUTHORITY_V9.json','EDGE_133_REPRODUCIBLE_SDIST_V9.json','EDGE_185_REPRODUCIBLE_SDIST_V9.json','EDGE_190_CONTENT_COMPARISON_V9.json','EDGE_190_COMMIT_RIGHTS_V9.json','EDGE_199_GHARCHIVE_DISCOVERY_RECEIPT_V9.json','EDGE_199_FULL_COMMIT_PROVIDER_VERIFICATION_V9.json','EDGE_199_SWH_FULL_REVISION_V9.json','LINEAGE_NATURAL_PAIR_AUTHORITY_V9.json','PYPI_INTEGRITY_PROVENANCE_V9.json']},
 'claim_boundary':['same seven frozen identities only; no replacement or proxy units','V9 is development provenance repair, not confirmatory naturalistic evidence','GH Archive is discovery-only and did not close index 199','ORCID concordance is person-identity progress, not author-lineage independence','no natural pair, comparator outcome, evaluator custody, performance or superiority claim'],
 'next_discriminator':'Repair five exact edges only when named provider-native authority appears. Independently build the full 75-edge ORCID/name conflict graph and freeze primary/replication partitions under external adjudication; then open natural-pair eligibility and external custody. Do not treat five edge residuals as the current source-cell quota bottleneck: Life, Earth and Physical remain structurally short, and Scientific Software source-disjoint replication remains separate.'
}
(R/'RESULT_V9.json').write_text(json.dumps(result,indent=2,sort_keys=True)+'\n')
neg={'schema_version':'orion.p4.exact-edge-lineage-authority.v9.negative-ledger','finished_at':result['finished_at'],'immutable_predecessor':'P4 V8 73/80','remaining':[x for x in rows if x['verdict']!='RESOLVED_SAME_IDENTITY'],'lineage_residual':result['lineage_authority'],'natural_pair_boundary':result['natural_pair_and_scientific_boundary'],'next_discriminator':result['next_discriminator']}
(R/'NEGATIVE_RESULT_LEDGER_V9.json').write_text(json.dumps(neg,indent=2,sort_keys=True)+'\n')
print(json.dumps({'closed':closed,'remaining':remaining,'cumulative':result['cumulative_exact_bridge'],'domains':result['cumulative_exact_by_domain'],'orcid_matches':lineage['counts']['cross_provider_exact_orcid_matches']},sort_keys=True))
