"""P9 structured epistemic neural-computation study helpers."""

from .bootstrap import bootstrap_information_lattice, bootstrap_worlds
from .generated_worlds import (
    CorpusSplit,
    GeneratedCorpus,
    GeneratedPair,
    GeneratedSplit,
    HostileFamily,
    generate_balanced_split,
    generate_corpus,
    generate_pair,
)
from .identifiability import (
    IdentifiabilityCollision,
    IdentifiabilityReport,
    analyze_identifiability,
)
from .m0 import (
    M0Baseline,
    evaluate_prediction,
    exact_semantic_oracle,
    predict_null,
    run_m0_harness,
)
from .m0_tasks import (
    CandidateInput,
    GluingTask,
    MechanicRankingTask,
    P9Task,
    TaskKind,
    build_task,
)
from .structural_world import (
    AffineTransport,
    Atom,
    AtomType,
    FailureRecord,
    GluingVerdict,
    GoldKind,
    GoldTarget,
    MechanicView,
    P9StructuralWorld,
    Relation,
    RelationType,
    ViewMode,
    classify_cycle_gluing,
    failure_history_pair,
    relation_semantics_pair,
    transport_gluing_pair,
)

__all__ = [
    "AffineTransport",
    "Atom",
    "AtomType",
    "CandidateInput",
    "CorpusSplit",
    "FailureRecord",
    "GeneratedCorpus",
    "GeneratedPair",
    "GeneratedSplit",
    "GluingTask",
    "GluingVerdict",
    "GoldKind",
    "GoldTarget",
    "HostileFamily",
    "IdentifiabilityCollision",
    "IdentifiabilityReport",
    "M0Baseline",
    "MechanicRankingTask",
    "MechanicView",
    "P9StructuralWorld",
    "P9Task",
    "Relation",
    "RelationType",
    "TaskKind",
    "ViewMode",
    "analyze_identifiability",
    "bootstrap_information_lattice",
    "bootstrap_worlds",
    "build_task",
    "classify_cycle_gluing",
    "evaluate_prediction",
    "exact_semantic_oracle",
    "failure_history_pair",
    "generate_balanced_split",
    "generate_corpus",
    "generate_pair",
    "predict_null",
    "relation_semantics_pair",
    "run_m0_harness",
    "transport_gluing_pair",
]
