#!/usr/bin/env python3
"""Independent confirmatory verifier for the X1-B k=3 scalar residual.

This implementation is intentionally algorithmically independent from
`x1b_k3_scalar_residual_exploratory.py`:

* state is a full 26-entry multiplicity vector;
* candidates are generated by direct multiplicity-vector augmentation;
* completed vectors are canonicalized under the full GL(3,3) action;
* no support-stabilizer quotient is used;
* every surviving orbit is replayed from primitive position subsets;
* the affine common-RHS system is independently reduced over F_5.

The exploratory outcome was known before this file was written.  Agreement is
confirmatory finite evidence only and grants no theorem/novelty authority.
"""
from __future__ import annotations

from collections import Counter
from hashlib import sha256
from itertools import combinations, product
import json

ZERO = (0, 0, 0)
ELS = tuple(
    (a, b, c)
    for a in range(3)
    for b in range(3)
    for c in range(3)
    if (a, b, c) != ZERO
)
INDEX = {v: i for i, v in enumerate(ELS)}
POW3 = tuple(3**i for i in range(len(ELS)))
PREFIX = "ORIONRG_X1B_K3_CONFIRM="


def neg(v):
    return tuple((-x) % 3 for x in v)


def det3(vals):
    a, b, c, d, e, f, g, h, i = vals
    return (
        a * (e * i - f * h)
        - b * (d * i - f * g)
        + c * (d * h - e * g)
    ) % 3


def mat_vec(vals, v):
    return tuple(
        sum(vals[3 * row + col] * v[col] for col in range(3)) % 3
        for row in range(3)
    )


def gl33_maps():
    maps = []
    for vals in product(range(3), repeat=9):
        if det3(vals) == 0:
            continue
        maps.append(tuple(INDEX[mat_vec(vals, v)] for v in ELS))
    if len(maps) != 11232:
        raise AssertionError(f"unexpected GL(3,3) size: {len(maps)}")
    return tuple(maps)


OPPOSITE = tuple(INDEX[neg(v)] for v in ELS)


def support_addition_ok(candidate_index, support):
    """Primitive length-2/3 zero-sum pruning for a new support element."""
    if OPPOSITE[candidate_index] in support:
        return False
    v = ELS[candidate_index]
    for a, b in combinations(support, 2):
        if all((ELS[a][j] + ELS[b][j] + v[j]) % 3 == 0 for j in range(3)):
            return False
    return True


def encode_multiplicity(mult):
    return sum(mult[i] * POW3[i] for i in range(len(ELS)))


def orbit_codes(mult, maps):
    out = []
    for mp in maps:
        code = 0
        for i, multiplicity in enumerate(mult):
            if multiplicity:
                code += multiplicity * POW3[mp[i]]
        out.append(code)
    return out


def canonical_full_multiplicity_representatives(maps):
    """Enumerate complete multiplicity vectors, quotienting only at completion."""
    seen_codes = set()
    representatives = []
    mult = [0] * len(ELS)
    support = []
    raw_candidate_count = 0

    def rec(index, total):
        nonlocal raw_candidate_count
        remaining = len(ELS) - index
        if total > 10 or total + 2 * remaining < 10:
            return
        if index == len(ELS):
            if total != 10:
                return
            raw_candidate_count += 1
            code = encode_multiplicity(mult)
            if code in seen_codes:
                return
            orbit = orbit_codes(mult, maps)
            seen_codes.update(orbit)
            representatives.append((min(orbit), tuple(mult)))
            return

        # multiplicity 0
        rec(index + 1, total)

        # multiplicities 1 or 2. Three copies of a nonzero F_3 element sum to 0,
        # hence multiplicity 2 is the maximum allowed by the short-zero-sum gate.
        if total < 10 and support_addition_ok(index, support):
            support.append(index)
            mult[index] = 1
            rec(index + 1, total + 1)
            if total + 2 <= 10:
                mult[index] = 2
                rec(index + 1, total + 2)
            mult[index] = 0
            support.pop()

    rec(0, 0)
    if len(seen_codes) != raw_candidate_count:
        raise AssertionError(
            "full GL orbit coverage mismatch: "
            f"seen={len(seen_codes)} raw={raw_candidate_count}"
        )
    return raw_candidate_count, representatives


def expand_positions(mult):
    positions = []
    for index, multiplicity in enumerate(mult):
        positions.extend([index] * multiplicity)
    if len(positions) != 10:
        raise AssertionError("candidate does not contain exactly 10 positions")
    return tuple(positions)


def primitive_zero_sum_masks(mult):
    positions = expand_positions(mult)
    masks = []
    for mask in range(1, 1 << len(positions)):
        s0 = s1 = s2 = 0
        for position, element_index in enumerate(positions):
            if (mask >> position) & 1:
                x, y, z = ELS[element_index]
                s0 = (s0 + x) % 3
                s1 = (s1 + y) % 3
                s2 = (s2 + z) % 3
        if (s0, s1, s2) == ZERO:
            masks.append(mask)
    return tuple(masks)


def has_disjoint_zero_sum_pair(masks):
    for index, a in enumerate(masks):
        for b in masks[index + 1 :]:
            if a & b == 0:
                return True
    return False


def common_rhs_system(masks):
    """Return (consistent, coefficient_rank, augmented_rank) over F_5."""
    rows = [
        [int((mask >> position) & 1) for position in range(10)] + [1]
        for mask in masks
    ]

    rank = 0
    for col in range(10):
        pivot = next(
            (row for row in range(rank, len(rows)) if rows[row][col] % 5),
            None,
        )
        if pivot is None:
            continue
        rows[rank], rows[pivot] = rows[pivot], rows[rank]
        inv = pow(rows[rank][col] % 5, -1, 5)
        rows[rank] = [(value * inv) % 5 for value in rows[rank]]
        for row in range(len(rows)):
            if row == rank or rows[row][col] % 5 == 0:
                continue
            factor = rows[row][col] % 5
            rows[row] = [
                (rows[row][j] - factor * rows[rank][j]) % 5
                for j in range(11)
            ]
        rank += 1

    inconsistent = any(
        all(row[col] % 5 == 0 for col in range(10)) and row[10] % 5 != 0
        for row in rows
    )
    augmented_rank = rank + int(inconsistent)
    return (not inconsistent), rank, augmented_rank


def main():
    maps = gl33_maps()
    raw_count, representatives = canonical_full_multiplicity_representatives(maps)

    survivors = []
    support_histogram = Counter()
    coefficient_rank_histogram = Counter()
    augmented_rank_histogram = Counter()
    consistent_count = 0

    for canonical_code, mult in representatives:
        masks = primitive_zero_sum_masks(mult)

        # Independent replay of the frozen short-zero-sum gate.
        if any(mask.bit_count() <= 3 for mask in masks):
            raise AssertionError("canonical augmentation admitted a short zero sum")
        if has_disjoint_zero_sum_pair(masks):
            continue

        consistent, coefficient_rank, augmented_rank = common_rhs_system(masks)
        support_size = sum(value > 0 for value in mult)
        support_histogram[support_size] += 1
        coefficient_rank_histogram[coefficient_rank] += 1
        augmented_rank_histogram[augmented_rank] += 1
        consistent_count += int(consistent)
        survivors.append(
            {
                "canonical_code": canonical_code,
                "multiplicity": list(mult),
                "support_size": support_size,
                "zero_sum_mask_count": len(masks),
                "coefficient_rank": coefficient_rank,
                "augmented_rank": augmented_rank,
                "consistent": consistent,
            }
        )

    canonical_codes = sorted(row["canonical_code"] for row in survivors)
    survivor_digest = sha256(
        json.dumps(canonical_codes, separators=(",", ":")).encode()
    ).hexdigest()

    payload = {
        "schema": "ORION.RG.X1B.K3ScalarConfirmatory.v1",
        "evidence_status": "INDEPENDENT_CONFIRMATORY_RECONSTRUCTION",
        "algorithm": "FULL_MULTIPLICITY_CANONICAL_AUGMENTATION",
        "exploratory_module_imported": False,
        "support_stabilizer_quotient_used": False,
        "gl33_size": len(maps),
        "raw_candidate_count": raw_count,
        "canonical_candidate_orbit_count": len(representatives),
        "surviving_orbit_count": len(survivors),
        "consistent_common_rhs_orbit_count": consistent_count,
        "inconsistent_common_rhs_orbit_count": len(survivors) - consistent_count,
        "support_size_histogram": {
            str(key): value for key, value in sorted(support_histogram.items())
        },
        "coefficient_rank_histogram": {
            str(key): value for key, value in sorted(coefficient_rank_histogram.items())
        },
        "augmented_rank_histogram": {
            str(key): value for key, value in sorted(augmented_rank_histogram.items())
        },
        "survivor_canonical_code_digest": survivor_digest,
        "primitive_replay_complete": True,
        "survivors": survivors,
        "finite_confirmatory_reconstruction": consistent_count == 0,
        "c15_theorem_authority": False,
        "infinite_family_authority": False,
        "novelty_authority": False,
        "scientific_authority": False,
    }
    print(PREFIX + json.dumps(payload, sort_keys=True, separators=(",", ":")))


if __name__ == "__main__":
    main()
