#!/usr/bin/env python3
"""Quantify what the R2 memorization disclosure states qualitatively.

The frozen R2 addendum records that stage-1 determination is "near-injective"
(1109 cells / 1146 instances, 1072 singletons) and therefore proves only
vocabulary EXISTENCE, not a compact law. That disclosure is correct but
qualitative. This script computes three exact quantities that make it precise.

(1) COMPRESSION BOUND.  For any feature map with c cells on N instances,
    E*(phi) <= (N - c)/N, because a cell of size m contributes at most m-1 to
    the floor. The observed cell structure therefore forced the floor into a
    known interval BEFORE any label was consulted.

(2) STRUCTURE-FREE NULL.  Given the exact realized cell structure and the exact
    class balance, what fraction of relabelings also attain floor 0? Computed in
    closed form with exact integer arithmetic, and cross-checked by permutation.
    This separates "the features carry regime information" from "the cells are
    small enough that any labelling would have been pure".

(3) SEPARATOR COMPLEXITY k*.  The minimum number of the frozen features whose
    projection still attains floor 0. Floor 0 holds exactly when every
    opposite-label pair is separated, so k* is a minimum hitting set over the
    pairs' discernibility sets. A small k* means a genuine low-order law; a
    large k* quantifies the memorization concern.

Nothing here changes a frozen artifact. All inputs come from FROZEN_MATRIX.json,
itself regenerated by extract_frozen_matrix.py from hash-verified modules.

Exit codes
    0  computed
    2  an internal consistency check failed
    3  inputs missing  -- CANNOT_CHECK
"""

from __future__ import annotations

import json
import math
import random
import sys
import time
from collections import Counter
from pathlib import Path

PACKET = Path(__file__).resolve().parent.parent
MATRIX = PACKET / "FROZEN_MATRIX.json"
PERM_TRIALS = 20000
SEED = 20260828


# ---------------------------------------------------------------------------
def cell_structure(rows, labels, feature_subset=None):
    """Cells, mixed-cell count and floor, computed from the definition."""
    cells: dict[tuple, list[int]] = {}
    for vec, lab in zip(rows, labels):
        key = vec if feature_subset is None else tuple(vec[j] for j in feature_subset)
        c = cells.setdefault(key, [0, 0])
        c[1 - lab] += 1          # index 0 counts label 1, index 1 counts label 0
    floor = sum(min(c) for c in cells.values() if c[0] and c[1])
    mixed = sum(1 for c in cells.values() if c[0] and c[1])
    singles = sum(1 for c in cells.values() if sum(c) == 1)
    return len(cells), singles, mixed, floor


def exact_null_probability(sizes, n_pos, n_total):
    """P(floor == 0) under a uniformly random relabelling with fixed class balance.

    Floor 0 requires every cell to be label-homogeneous. Cells of size 1 are
    always homogeneous. With cells of sizes s_1..s_m (all >= 2), choosing which
    are all-positive determines the positives they absorb; the rest come from
    the singletons. Exact integer arithmetic, no approximation.
    """
    multi = [s for s in sizes if s >= 2]
    n_single = n_total - sum(multi)
    fav = 0
    # subset-sum over the multiset of cell sizes, tracking how many positives
    # the chosen all-positive cells absorb
    ways = Counter({0: 1})
    for s in multi:
        nxt = Counter()
        for absorbed, w in ways.items():
            nxt[absorbed] += w              # this cell is all-negative
            nxt[absorbed + s] += w          # this cell is all-positive
        ways = nxt
    for absorbed, w in ways.items():
        rest = n_pos - absorbed
        if 0 <= rest <= n_single:
            fav += w * math.comb(n_single, rest)
    return fav, math.comb(n_total, n_pos)


# ---------------------------------------------------------------------------
def discernibility_sets(rows, labels, n_features):
    """Minimal discernibility sets over opposite-label pairs, as bitmasks."""
    pos = [i for i, l in enumerate(labels) if l == 1]
    neg = [i for i, l in enumerate(labels) if l == 0]
    seen = set()
    for i in pos:
        ri = rows[i]
        for j in neg:
            rj = rows[j]
            m = 0
            for k in range(n_features):
                if ri[k] != rj[k]:
                    m |= 1 << k
            seen.add(m)
    if 0 in seen:                      # an identical opposite-label pair exists
        return None, len(pos) * len(neg)
    masks = sorted(seen, key=lambda m: bin(m).count("1"))
    minimal = []
    for m in masks:                    # keep only subset-minimal sets
        if not any((m & s) == s for s in minimal):
            minimal.append(m)
    return minimal, len(pos) * len(neg)


def greedy_cover(minimal, n_features):
    remaining = list(minimal)
    chosen = []
    while remaining:
        counts = Counter()
        for m in remaining:
            mm = m
            while mm:
                b = mm & -mm
                counts[b.bit_length() - 1] += 1
                mm ^= b
        best = counts.most_common(1)[0][0]
        chosen.append(best)
        bit = 1 << best
        remaining = [m for m in remaining if not (m & bit)]
    return sorted(chosen)


def disjoint_lower_bound(minimal):
    """Greedy packing of pairwise-disjoint sets: each needs its own element."""
    used, count = 0, 0
    for m in sorted(minimal, key=lambda x: bin(x).count("1")):
        if not (m & used):
            used |= m
            count += 1
    return count


def exact_min_hitting_set(minimal, ub, lb, budget_s=120.0):
    """Iterative deepening with a disjoint-packing bound. Returns (k, proved)."""
    t0 = time.perf_counter()

    def search(sets, depth, limit):
        if not sets:
            return []
        if depth == limit or time.perf_counter() - t0 > budget_s:
            return None
        if depth + disjoint_lower_bound(sets) > limit:
            return None
        target = min(sets, key=lambda x: bin(x).count("1"))   # branch on smallest
        mm = target
        while mm:
            b = mm & -mm
            mm ^= b
            rest = [s for s in sets if not (s & b)]
            sub = search(rest, depth + 1, limit)
            if sub is not None:
                return [b.bit_length() - 1] + sub
        return None

    for limit in range(lb, ub + 1):
        if time.perf_counter() - t0 > budget_s:
            return ub, False
        got = search(minimal, 0, limit)
        if got is not None:
            return limit, True
    return ub, False


# ---------------------------------------------------------------------------
def main() -> int:
    if not MATRIX.is_file():
        print(json.dumps({"status": "CANNOT_CHECK",
                          "error": f"missing {MATRIX}; run extract_frozen_matrix.py"},
                         indent=2))
        return 3
    data = json.loads(MATRIX.read_text())
    rows = [tuple(r) for r in data["matrix"]]
    labels = data["labels"]
    n_total = len(rows)
    n_feat = data["feature_count"]
    n_pos = sum(labels)

    cells, singles, mixed, floor = cell_structure(rows, labels)
    sizes = list(Counter(rows).values())
    assert sum(sizes) == n_total

    # (1) compression bound
    bound_num = n_total - cells
    # (2) exact structure-free null
    fav, tot = exact_null_probability(sizes, n_pos, n_total)
    p_null = fav / tot
    rng = random.Random(SEED)
    perm_hits = 0
    idx = list(range(n_total))
    for _ in range(PERM_TRIALS):
        rng.shuffle(idx)
        shuffled = [labels[i] for i in idx]
        _, _, _, f = cell_structure(rows, shuffled)
        perm_hits += (f == 0)

    # (3) separator complexity
    t0 = time.perf_counter()
    minimal, n_pairs = discernibility_sets(rows, labels, n_feat)
    if minimal is None:
        print(json.dumps({"status": "FAIL",
                          "error": "identical opposite-label pair; floor 0 impossible"},
                         indent=2))
        return 2
    ub_set = greedy_cover(minimal, n_feat)
    lb = disjoint_lower_bound(minimal)
    core = sorted(m.bit_length() - 1 for m in minimal if bin(m).count("1") == 1)
    k_star, proved = exact_min_hitting_set(minimal, len(ub_set), max(lb, len(core)))
    t_sep = time.perf_counter() - t0

    # verify a witness subset of size k_star actually attains floor 0
    witness = None
    if proved:
        for limit in (k_star,):
            got = None
            # re-run the search once to recover the witness
            def search(sets, depth, chosen):
                if not sets:
                    return list(chosen)
                if depth == limit:
                    return None
                if depth + disjoint_lower_bound(sets) > limit:
                    return None
                target = min(sets, key=lambda x: bin(x).count("1"))
                mm = target
                while mm:
                    b = mm & -mm
                    mm ^= b
                    r = search([s for s in sets if not (s & b)], depth + 1,
                               chosen + [b.bit_length() - 1])
                    if r is not None:
                        return r
                return None
            got = search(minimal, 0, [])
            if got:
                witness = sorted(got)
    verified = None
    witness_null = None
    if witness:
        c2, s2, m2, f2 = cell_structure(rows, labels, feature_subset=witness)
        verified = {"subset": witness, "size": len(witness), "cells": c2,
                    "mixed_cells": m2, "floor": f2, "attains_floor_zero": f2 == 0}
        # Structure-free null for the witness map itself. Computed here rather
        # than by hand so that no value in RESULT.json is un-reproducible.
        w_sizes = list(Counter(tuple(v[j] for j in witness) for v in rows).values())
        w_fav, w_tot = exact_null_probability(w_sizes, n_pos, n_total)
        w_p = w_fav / w_tot
        witness_null = {
            "cells": c2,
            "compression_ratio": round(c2 / n_total, 6),
            "compression_bound": f"{n_total - c2}/{n_total}",
            "exact_probability": w_p,
            "exact_probability_sci": f"{w_p:.3e}",
            "reading": ("the witness map is far from injective, so attaining "
                        "floor 0 with it is overwhelming evidence of genuine "
                        "structure rather than memorization"),
        }

    report = {
        "schema": "ORION.ORION09.RegimeSeparatorComplexity.Analysis.v1",
        "inputs": {"instances": n_total, "features": n_feat, "positives": n_pos,
                   "negatives": n_total - n_pos},
        "observed_cell_structure": {
            "cells": cells, "singleton_cells": singles,
            "non_singleton_cells": cells - singles,
            "mixed_cells": mixed, "floor": floor,
            "max_cell_size": max(sizes),
            "cell_size_histogram": dict(sorted(Counter(sizes).items())),
        },
        "result_1_compression_bound": {
            "statement": "E*(phi) <= (N - c)/N for any feature map with c cells on N instances",
            "N_minus_c": bound_num,
            "bound": f"{bound_num}/{n_total}",
            "bound_decimal": round(bound_num / n_total, 6),
            "reading": ("The realized cell structure confined the floor to "
                        f"[0, {bound_num}/{n_total}] before any label was read. "
                        "Floor 0 is therefore at most this far from the value the "
                        "cell structure alone would force."),
        },
        "result_2_structure_free_null": {
            "question": ("Given the exact realized cells and class balance, how "
                         "often does a random relabelling also attain floor 0?"),
            "exact_favourable": str(fav),
            "exact_total": str(tot),
            "exact_probability": p_null,
            "exact_probability_sci": f"{p_null:.3e}",
            "permutation_trials": PERM_TRIALS,
            "permutation_hits": perm_hits,
            "permutation_rate": perm_hits / PERM_TRIALS,
            "reading": ("Low probability means floor 0 is NOT explained by cell "
                        "sizes alone and the labels really are aligned with the "
                        "feature partition. High probability would mean the "
                        "conversion is an artifact of near-injectivity."),
        },
        "result_3_separator_complexity": {
            "opposite_label_pairs": n_pairs,
            "distinct_minimal_discernibility_sets": len(minimal),
            "core_features_forced": core,
            "lower_bound_disjoint_packing": lb,
            "greedy_upper_bound": len(ub_set),
            "k_star": k_star,
            "k_star_proved_minimal": proved,
            "witness": verified,
            "witness_structure_free_null": witness_null,
            "seconds": round(t_sep, 1),
            "reading": ("k* is the minimum number of frozen features whose "
                        "projection still attains floor 0. Small k* means a "
                        "genuine low-order sufficient vocabulary exists; k* close "
                        "to the full 127 would quantify the memorization concern."),
        },
        "status": "PASS",
    }
    if verified and not verified["attains_floor_zero"]:
        report["status"] = "FAIL"
    (PACKET / "ANALYSIS.json").write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps({k: report[k] for k in
                      ("status", "result_1_compression_bound",
                       "result_2_structure_free_null",
                       "result_3_separator_complexity")}, indent=2, default=str))
    return 0 if report["status"] == "PASS" else 2


if __name__ == "__main__":
    sys.exit(main())
