#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; RESULT=ROOT/'artifacts/orion-qg-qg15c-enlarged-vocab.json'; GENERIC=ROOT/'artifacts/orion-qg-qg15c-generic.json'; OUT=ROOT/'artifacts/orion-qg-qg15c-native.json'; TOKEN='ORIONQG_QG15C_NATIVE='
def canonical(v): return json.dumps(v,sort_keys=True,separators=(',',':'),allow_nan=False)
def main():
 a=json.loads(RESULT.read_text()); g=json.loads(GENERIC.read_text()); negative=a.get('terminal')=='QG15C_ENLARGED_DONOR_PATH_VOCABULARY_STILL_INSUFFICIENT__MIXED_CELLS_MACHINE_VERIFIED'; positive=a.get('terminal')=='QG15C_L2_FEATURE_DETERMINED_ON_COMPLETE_NLE3__HELDOUT_STAGE_REQUIRED'; exp='ACCEPT_INSUFFICIENT' if negative else 'ACCEPT_HELDOUT_REQUIRED'; checks={'analyzer_gates':a.get('all_gates') is True,'generic':g.get('decision')==exp and g.get('all_checks') is True,'terminal_allowed':negative or positive,'negative_first_class':(not negative) or (a.get('mixed_cell_count',0)>0 and a.get('irreducible_error_floor',0)>0),'positive_not_closed':(not positive) or a.get('heldout_stage_authorized') is True,'scope':a.get('chemistry_sources_read') is False and a.get('protected_subject_read') is False,'no_overclaim':a.get('novelty_authority') is False and a.get('r6_authority') is False and a.get('physical_quantum_advantage_claim') is False}; decision=exp if all(checks.values()) else 'REJECT'; responsibility=('ENLARGED_VOCABULARY_INSUFFICIENT_CLOSED' if negative else 'HELDOUT_STAGE_REQUIRED') if decision!='REJECT' else 'CANNOT_CHECK'; out={'schema':'ORION.QG.QG15C.Native.v1','issue':'SzeChunYiu/ORION#840','decision':decision,'responsibility':responsibility,'checks':checks,'all_checks':all(checks.values()),'terminal':a.get('terminal'),'scientifically_closed':negative and decision=='ACCEPT_INSUFFICIENT','novelty_authority':False}; OUT.parent.mkdir(parents=True,exist_ok=True); OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n'); print(TOKEN+canonical(out)); return 0
if __name__=='__main__': raise SystemExit(main())
