#!/usr/bin/env python3
"""Native ORION-Q responsibility gate for QG-28 local-Clifford orbit compression."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];A=ROOT/"artifacts/orion-qg-qg28-local-clifford-orbits.json";G=ROOT/"artifacts/orion-qg-qg28-generic-verification.json";PROTO=ROOT/"development/orion-qg-regime-geometry/QG28_LOCAL_CLIFFORD_ORBIT_PROTOCOL_V1.md";OUT=ROOT/"artifacts/orion-qg-qg28-native-verification.json";TOKEN="ORIONQG_QG28_NATIVE=";POS="QG28_TARE_EXACT_COST_DESCENDS_TO_715_LOCAL_CLIFFORD_COLUMN_ORBIT_COUNTS_ALL_N"
def canon(v):return json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False)
def valid(r):u={k:v for k,v in r.items() if k!="result_digest"};return r.get("result_digest")==hashlib.sha256(canon(u).encode()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--analyzer",type=Path,default=A);ap.add_argument("--generic",type=Path,default=G);ap.add_argument("--output",type=Path,default=OUT);x=ap.parse_args();a=json.loads(x.analyzer.read_text());g=json.loads(x.generic.read_text())
 checks={"analyzer_positive":a.get("terminal")==POS and a.get("LOCAL_CLIFFORD_EQUIVARIANCE_PER_QUBIT") is True and a.get("ORBIT_HISTOGRAM_SUFFICIENT_STATISTIC_ALL_N") is True and valid(a),"generic_positive":g.get("decision")=="ACCEPT_LOCAL_CLIFFORD_ORBIT_COMPRESSION" and g.get("all_checks") is True,"digest_bound":g.get("source_result_digest")==a.get("result_digest"),"protocol_bound":a.get("protocol_sha256")==hashlib.sha256(PROTO.read_bytes()).hexdigest(),"orbit_exact":a.get("LOCAL_CLIFFORD_ORBIT_COUNT")==715 and a.get("orbit_census",{}).get("orbit_size_distribution")=={"1":1,"3":63,"6":651},"equivariance":a.get("table_checks",{}).get("all_equivariant") is True and len(a.get("automorphism_checks",[]))==6,"baseline_descent":a.get("baseline_quotient",{}).get("checks",{}).get("constant_on_orbits") is True and a.get("baseline_quotient",{}).get("checks",{}).get("lift_exact") is True and a.get("baseline_quotient",{}).get("checks",{}).get("distinct_quotient_vectors")==4,"active_control":a.get("active_canonicalization_control",{}).get("rows")==1572864 and a.get("active_canonicalization_control",{}).get("all_match") is True,"unsafe_barrier":a.get("INDEPENDENT_POSITION_RELABEL_PER_COLUMN") is False and a.get("COMBINED_LOCAL_POSITION_QUOTIENT_54") is False and g.get("INDEPENDENT_POSITION_RELABEL_PER_COLUMN") is False and g.get("COMBINED_LOCAL_POSITION_QUOTIENT_54") is False,"stronger_false":all(a.get(k) is False and g.get(k) is False for k in ("EXPLICIT_TEMPLATE_BASIS_ENUMERATED","PRACTICAL_STATIC_FORECASTER","CHAIN_ALL_N","CLOSED_FORM_BDOUBLEPRIME_COMPLETENESS","novelty_authority","r6_authority","physical_quantum_advantage_claim"))};ok=all(checks.values());out={"schema":"ORIONQG.QG28.NativeVerification.v1","decision":"ACCEPT_LOCAL_CLIFFORD_ORBIT_COMPRESSION" if ok else "REJECT","responsibility":"LOCAL_CLIFFORD_EQUIVARIANCE__715_ORBIT_HISTOGRAM_GEOMETRY" if ok else "CANNOT_CHECK","all_checks":bool(ok),"checks":checks,"source_result_digest":a.get("result_digest"),"LOCAL_CLIFFORD_EQUIVARIANCE_PER_QUBIT":bool(ok),"LOCAL_CLIFFORD_ORBIT_COUNT":715 if ok else None,"ORBIT_HISTOGRAM_SUFFICIENT_STATISTIC_ALL_N":bool(ok),"GUARDED_TROPICAL_GEOMETRY_DESCENDS_TO_715_COUNTS":bool(ok),"INDEPENDENT_POSITION_RELABEL_PER_COLUMN":False,"COMBINED_LOCAL_POSITION_QUOTIENT_54":False,"EXPLICIT_TEMPLATE_BASIS_ENUMERATED":False,"PRACTICAL_STATIC_FORECASTER":False,"CHAIN_ALL_N":False,"CLOSED_FORM_BDOUBLEPRIME_COMPLETENESS":False,"novelty_authority":False,"r6_authority":False,"physical_quantum_advantage_claim":False};x.output.parent.mkdir(parents=True,exist_ok=True);x.output.write_text(json.dumps(out,indent=2,sort_keys=True)+"\n");print(TOKEN+canon({"decision":out["decision"],"responsibility":out["responsibility"],"orbits":out["LOCAL_CLIFFORD_ORBIT_COUNT"]}));return 0
if __name__=="__main__":raise SystemExit(main())
