#!/usr/bin/env python3
"""Native ORION-Q responsibility gate for QG-29 defect saturation / universal k=43 theorem."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];A=ROOT/"artifacts/orion-qg-qg29-defect-saturation.json";G=ROOT/"artifacts/orion-qg-qg29-generic-verification.json";PROTO=ROOT/"development/orion-qg-regime-geometry/QG29_DEFECT_SATURATION_PROTOCOL_V1.md";OUT=ROOT/"artifacts/orion-qg-qg29-native-verification.json";TOKEN="ORIONQG_QG29_NATIVE=";POS="QG29_TARE_DEFECTS_CLIP_AT_6_AND_ALL_SCALING_RAYS_AFFINE_BY_K43_MACHINE_CHECKED"
def canon(v):return json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False)
def valid(r):u={k:v for k,v in r.items() if k!="result_digest"};return r.get("result_digest")==hashlib.sha256(canon(u).encode()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--analyzer",type=Path,default=A);ap.add_argument("--generic",type=Path,default=G);ap.add_argument("--output",type=Path,default=OUT);x=ap.parse_args();a=json.loads(x.analyzer.read_text());g=json.loads(x.generic.read_text())
 stronger=("K43_SHARP_FOR_REAL_TARE","EXPLICIT_Q_H_FORECASTER","FINITE_N_GLOBAL_PHASE_BOUNDARY","CHAIN_ALL_N","CLOSED_FORM_BDOUBLEPRIME_COMPLETENESS")
 checks={"analyzer_positive":a.get("terminal")==POS and a.get("DEFECT_POTENTIAL_CLIP6_SUFFICIENT") is True and a.get("PURE_SCALING_RAY_AFFINE_BY_K43") is True and valid(a),"generic_positive":g.get("decision")=="ACCEPT_DEFECT_CLIP6_K43_AFFINITY" and g.get("all_checks") is True,"digest_bound":g.get("source_result_digest")==a.get("result_digest"),"protocol_bound":a.get("protocol_sha256")==hashlib.sha256(PROTO.read_bytes()).hexdigest(),"parents":all(a.get("qg26_checks",{}).values()) and all(a.get("qg27_checks",{}).values()),"clip6":a.get("defect_potential",{}).get("individual_guard_threshold_max")==6 and a.get("defect_potential",{}).get("kappa_level_count")==43 and a.get("defect_potential",{}).get("strict_defect_level_drops_max")==42,"ray_saturation":a.get("scaling_rays",{}).get("kappa_r_constant_for_all_k_ge")==6,"ray_affinity":a.get("scaling_rays",{}).get("universal_affine_onset_k")==43 and "k>=43" in a.get("scaling_rays",{}).get("theorem","") ,"abstract_control":a.get("abstract_crossover_control",{}).get("pairwise_obstruction_cases")==11094 and a.get("abstract_crossover_control",{}).get("all_positive_gap_lines_strictly_dominated_by_k43") is True and a.get("abstract_crossover_control",{}).get("minimum_margin_at_43")==1 and a.get("abstract_crossover_control",{}).get("frozen_tight_witness_verified") is True,"generic_arithmetic":g.get("independent_derived",{}).get("universal_affine_onset")==43 and g.get("independent_derived",{}).get("abstract_control",{}).get("cases")==11094,"qg28_optional":a.get("optional_qg28",{}).get("authority_depends_on_qg28") is False,"stronger_false":all(a.get(k) is False and g.get(k) is False for k in stronger),"no_external_authority":all(a.get(k) is False and g.get(k) is False for k in ("novelty_authority","r6_authority","physical_quantum_advantage_claim"))}
 ok=all(checks.values());out={"schema":"ORIONQG.QG29.NativeVerification.v1","decision":"ACCEPT_DEFECT_CLIP6_K43_AFFINITY" if ok else "REJECT","responsibility":"DEFECT_CLIP6__K6_GUARD_SATURATION__K43_AFFINE_ONSET" if ok else "CANNOT_CHECK","all_checks":bool(ok),"checks":checks,"source_result_digest":a.get("result_digest"),"DEFECT_POTENTIAL_CLIP6_SUFFICIENT":bool(ok),"DEFECT_LEVEL_CHANGES_AT_MOST_42_PER_BULK_CLASS":bool(ok),"PURE_SCALING_RAY_DEFECTS_STABLE_BY_K6":bool(ok),"PURE_SCALING_RAY_AFFINE_BY_K43":bool(ok),"K43_SHARP_FOR_REAL_TARE":False,"EXPLICIT_Q_H_FORECASTER":False,"FINITE_N_GLOBAL_PHASE_BOUNDARY":False,"CHAIN_ALL_N":False,"CLOSED_FORM_BDOUBLEPRIME_COMPLETENESS":False,"novelty_authority":False,"r6_authority":False,"physical_quantum_advantage_claim":False};x.output.parent.mkdir(parents=True,exist_ok=True);x.output.write_text(json.dumps(out,indent=2,sort_keys=True)+"\n");print(TOKEN+canon({"decision":out["decision"],"responsibility":out["responsibility"],"clip":6,"stable_k":6,"affine_k":43}));return 0
if __name__=="__main__":raise SystemExit(main())
