#!/usr/bin/env python3
"""Native ORION-Q responsibility gate for QG-30 bulk coarse-graining / defect separation."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];A=ROOT/"artifacts/orion-qg-qg30-bulk-coarse-grain.json";G=ROOT/"artifacts/orion-qg-qg30-generic-verification.json";PROTO=ROOT/"development/orion-qg-regime-geometry/QG30_BULK_COARSE_GRAIN_PROTOCOL_V1.md";OUT=ROOT/"artifacts/orion-qg-qg30-native-verification.json";TOKEN="ORIONQG_QG30_NATIVE=";POS="QG30_TARE_BULK_GEOMETRY_COMPRESSES_EXACTLY_TO_45_SIGNATURE_COUNTS__DEFECT_INFORMATION_REMAINS"
def canon(v):return json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False)
def valid(r):u={k:v for k,v in r.items() if k!="result_digest"};return r.get("result_digest")==hashlib.sha256(canon(u).encode()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--analyzer",type=Path,default=A);ap.add_argument("--generic",type=Path,default=G);ap.add_argument("--output",type=Path,default=OUT);x=ap.parse_args();a=json.loads(x.analyzer.read_text());g=json.loads(x.generic.read_text());c=a.get("bulk_signature_census",{});w=c.get("information_loss_witness")
 stronger=("BULK_SIGNATURE_SUFFICIENT_FOR_FULL_DEFECT","FULL_FINITE_N_OPTIMUM_FROM_45_COUNTS","PHYSICAL_RENORMALIZATION_GROUP","FINITE_N_GLOBAL_PHASE_BOUNDARY","CHAIN_ALL_N","CLOSED_FORM_BDOUBLEPRIME_COMPLETENESS")
 checks={"analyzer_positive":a.get("terminal")==POS and a.get("BULK_45_HISTOGRAM_SUFFICIENT_FOR_ASYMPTOTIC_DENSITY") is True and a.get("BULK_DEFECT_SCALE_SEPARATION") is True and valid(a),"generic_positive":g.get("decision")=="ACCEPT_BULK45_DEFECT_SEPARATION" and g.get("all_checks") is True,"digest_bound":g.get("source_result_digest")==a.get("result_digest"),"protocol_bound":a.get("protocol_sha256")==hashlib.sha256(PROTO.read_bytes()).hexdigest(),"issue_bound":a.get("issue")=="SzeChunYiu/ORION#893","parents":all(a.get("parent_checks",{}).values()),"census":c.get("signature_count")==45 and c.get("orbit_total")==715 and c.get("raw_type_total")==4096,"profiles":a.get("complete_one_active_profile_rows")==274560 and c.get("information_loss_witness_found") is True and w is not None,"generic_same_witness":g.get("independent_summary",{}).get("witness")==w,"bulk_geometry":len(a.get("bulk_coefficient_rows_45",{}).get("rows",[]))==4 and all(len(r)==45 for r in a.get("bulk_coefficient_rows_45",{}).get("rows",[])) and len(a.get("pairwise_bulk_ties_45",[]))==6,"information_barrier":a.get("BULK_SIGNATURE_SUFFICIENT_FOR_FULL_DEFECT") is False and g.get("BULK_SIGNATURE_SUFFICIENT_FOR_FULL_DEFECT") is False,"stronger_false":all(a.get(k) is False and g.get(k) is False for k in stronger),"no_external_authority":all(a.get(k) is False and g.get(k) is False for k in ("novelty_authority","r6_authority","physical_quantum_advantage_claim"))}
 ok=all(checks.values());out={"schema":"ORIONQG.QG30.NativeVerification.v1","decision":"ACCEPT_BULK45_DEFECT_SEPARATION" if ok else "REJECT","responsibility":"BULK45_ASYMPTOTIC_SUFFICIENCY__FINITE_DEFECT_INFORMATION_BARRIER" if ok else "CANNOT_CHECK","all_checks":bool(ok),"checks":checks,"source_result_digest":a.get("result_digest"),"BULK_SIGNATURE_COUNT_45":45 if ok else None,"BULK_45_HISTOGRAM_SUFFICIENT_FOR_ASYMPTOTIC_DENSITY":bool(ok),"ASYMPTOTIC_PHASE_GEOMETRY_DESCENDS_TO_45_COUNTS":bool(ok),"BULK_DEFECT_SCALE_SEPARATION":bool(ok),"BULK_SIGNATURE_SUFFICIENT_FOR_FULL_DEFECT":False,"FULL_FINITE_N_OPTIMUM_FROM_45_COUNTS":False,"PHYSICAL_RENORMALIZATION_GROUP":False,"FINITE_N_GLOBAL_PHASE_BOUNDARY":False,"CHAIN_ALL_N":False,"CLOSED_FORM_BDOUBLEPRIME_COMPLETENESS":False,"novelty_authority":False,"r6_authority":False,"physical_quantum_advantage_claim":False};x.output.parent.mkdir(parents=True,exist_ok=True);x.output.write_text(json.dumps(out,indent=2,sort_keys=True)+"\n");print(TOKEN+canon({"decision":out["decision"],"responsibility":out["responsibility"],"signatures":45,"witness_found":w is not None}));return 0
if __name__=="__main__":raise SystemExit(main())
