#!/usr/bin/env python3
"""Native ORION-Q responsibility gate for QG-31 query-indexed abstraction."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];A=ROOT/"artifacts/orion-qg-qg31-query-abstraction.json";G=ROOT/"artifacts/orion-qg-qg31-generic-verification.json";P=ROOT/"development/orion-qg-regime-geometry/QG31_QUERY_INDEXED_ABSTRACTION_PROTOCOL_V1.md";OUT=ROOT/"artifacts/orion-qg-qg31-native-verification.json";TOKEN="ORIONQG_QG31_NATIVE=";POS="QG31_QUERY_INDEXED_ABSTRACTION_LADDER_CONFIRMED__INDEXED_LOCAL_RESPONSE_INJECTIVE_ON_715_ORBITS"
def canon(v):return json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False)
def valid(r):u={k:v for k,v in r.items() if k!="result_digest"};return r.get("result_digest")==hashlib.sha256(canon(u).encode()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--analyzer",type=Path,default=A);ap.add_argument("--generic",type=Path,default=G);ap.add_argument("--output",type=Path,default=OUT);x=ap.parse_args();a=json.loads(x.analyzer.read_text());g=json.loads(x.generic.read_text());r=a.get("partition_relations",{})
 checks={"analyzer":a.get("terminal")==POS and valid(a),"generic":g.get("decision")=="ACCEPT_QUERY_INDEXED_ABSTRACTION" and g.get("all_checks") is True,"digest":g.get("source_result_digest")==a.get("result_digest"),"protocol":a.get("protocol_sha256")==hashlib.sha256(P.read_bytes()).hexdigest(),"counts":a.get("class_counts")=={"bulk":45,"spectrum":54,"indexed":715},"indexed_refines":r.get("indexed_refines_bulk") is True and r.get("indexed_refines_spectrum") is True,"indexed_injective":a.get("INDEXED_LOCAL_RESPONSE_CLASSES_715") is True and a.get("INDEXED_RESPONSE_MINIMALITY_715") is True,"query_scope":a.get("QUERY_INDEXED_ABSTRACTION_REQUIRED") is True,"stronger_false":a.get("FULL_FINITE_N_OPTIMUM_REQUIRES_715_CLASSES") is False and a.get("QG28_ORBIT_HISTOGRAM_GLOBALLY_MINIMAL") is False and g.get("FULL_FINITE_N_OPTIMUM_REQUIRES_715_CLASSES") is False and g.get("QG28_ORBIT_HISTOGRAM_GLOBALLY_MINIMAL") is False,"no_external":all(a.get(k) is False and g.get(k) is False for k in ("novelty_authority","r6_authority","physical_quantum_advantage_claim"))};ok=all(checks.values());out={"schema":"ORIONQG.QG31.NativeVerification.v1","decision":"ACCEPT_QUERY_INDEXED_ABSTRACTION" if ok else "REJECT","responsibility":"QUERY_SCOPED_ABSTRACTION__INDEXED_RESPONSE_MINIMALITY_ONLY" if ok else "CANNOT_CHECK","all_checks":bool(ok),"checks":checks,"source_result_digest":a.get("result_digest"),"BULK_QUERY_CLASSES_45":bool(ok),"DEFECT_SPECTRUM_QUERY_CLASSES_54":bool(ok),"INDEXED_LOCAL_RESPONSE_CLASSES_715":bool(ok),"INDEXED_RESPONSE_MINIMALITY_715":bool(ok),"BULK_SPECTRUM_PARTITIONS_INCOMPARABLE":bool(ok and a.get("BULK_SPECTRUM_PARTITIONS_INCOMPARABLE")),"QUERY_INDEXED_ABSTRACTION_REQUIRED":bool(ok),"FULL_FINITE_N_OPTIMUM_REQUIRES_715_CLASSES":False,"QG28_ORBIT_HISTOGRAM_GLOBALLY_MINIMAL":False,"novelty_authority":False,"r6_authority":False,"physical_quantum_advantage_claim":False};x.output.parent.mkdir(parents=True,exist_ok=True);x.output.write_text(json.dumps(out,indent=2,sort_keys=True)+"\n");print(TOKEN+canon({"decision":out["decision"],"responsibility":out["responsibility"],"incomparable":out["BULK_SPECTRUM_PARTITIONS_INCOMPARABLE"]}));return 0
if __name__=="__main__":raise SystemExit(main())
