#!/usr/bin/env python3
"""Native ORION-Q responsibility gate for QG-32 fixed separating probes."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2];A=ROOT/"artifacts/orion-qg-qg32-min-probes.json";G=ROOT/"artifacts/orion-qg-qg32-generic-verification.json";P=ROOT/"development/orion-qg-regime-geometry/QG32_MIN_SEPARATING_PROBES_PROTOCOL_V1.md";OUT=ROOT/"artifacts/orion-qg-qg32-native-verification.json";TOKEN="ORIONQG_QG32_NATIVE="
def canon(v:Any)->str:return json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False)
def valid(r):
 u={k:v for k,v in r.items() if k!="result_digest"};return r.get("result_digest")==hashlib.sha256(canon(u).encode()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--analyzer",type=Path,default=A);ap.add_argument("--generic",type=Path,default=G);ap.add_argument("--output",type=Path,default=OUT);ns=ap.parse_args();a=json.loads(ns.analyzer.read_text());g=json.loads(ns.generic.read_text());proof=g.get("independent",{}).get("proof",{})
 checks={"analyzer_digest":valid(a),"protocol_bound":a.get("protocol_sha256")==hashlib.sha256(P.read_bytes()).hexdigest(),"parent":all(a.get("parent_checks",{}).values()),"production_optimal":a.get("PRODUCTION_MILP_MINIMUM_OPTIMAL") is True and a.get("selected_separates_715") is True,"generic_accept":g.get("decision")=="ACCEPT_MINIMUM_FIXED_PROBE_BASIS" and g.get("all_checks") is True,"digest_bound":g.get("source_result_digest")==a.get("result_digest"),"independent_minimum":proof.get("no_smaller") is True,"fixed_query_scope":a.get("minimum_probe_cardinality") is not None and len(a.get("selected_probe_indices",[]))==a.get("minimum_probe_cardinality"),"no_lex_authority":"NO_LEX_AUTHORITY" in str(a.get("selected_canonicalization","")),"boundaries":all(a.get(k) is False and g.get(k) is False for k in ("MINIMUM_FULL_FINITE_OPTIMUM_PROBES","HARDWARE_MEASUREMENT_MINIMUM","QG28_GLOBAL_STATE_MINIMALITY","ADAPTIVE_TREE_OPTIMALITY","novelty_authority","physical_quantum_advantage_claim"))}
 ok=all(checks.values());out={"schema":"ORIONQG.QG32.NativeVerification.v1","decision":"ACCEPT_MINIMUM_FIXED_PROBE_BASIS" if ok else "REJECT","responsibility":"JOINT_SUMMARY_PLUS_MINIMUM_FIXED_PROBE_ACTIVE_VERIFICATION_ONLY" if ok else "CANNOT_CHECK","all_checks":bool(ok),"checks":checks,"source_result_digest":a.get("result_digest"),"MINIMUM_FIXED_PROBE_BASIS_AUTHORITY":bool(ok),"MINIMUM_FULL_FINITE_OPTIMUM_PROBES":False,"HARDWARE_MEASUREMENT_MINIMUM":False,"QG28_GLOBAL_STATE_MINIMALITY":False,"ADAPTIVE_TREE_OPTIMALITY":False,"novelty_authority":False,"physical_quantum_advantage_claim":False};ns.output.parent.mkdir(parents=True,exist_ok=True);ns.output.write_text(json.dumps(out,indent=2,sort_keys=True)+"\n");print(TOKEN+canon({"decision":out["decision"],"responsibility":out["responsibility"],"m":a.get("minimum_probe_cardinality"),"no_smaller":proof.get("no_smaller"),"cover_classes":proof.get("unique_nondominated_cover_classes")}));return 0
if __name__=="__main__":raise SystemExit(main())
