#!/usr/bin/env python3
"""Native ORION-Q authority gate for QG-32c independent fixed-probe replication."""
from __future__ import annotations
import argparse,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];SRC=ROOT/"artifacts/orion-qg-qg32c-mitm-replication.json";GEN=ROOT/"artifacts/orion-qg-qg32c-generic-verification.json";OUT=ROOT/"artifacts/orion-qg-qg32c-native-verification.json";TOKEN="ORIONQG_QG32C_NATIVE="
YES="QG32C_INDEPENDENT_REPLICATION_FINDS_FOUR_OR_FEWER_SEPARATOR";NO="QG32C_INDEPENDENT_REPLICATION_CONFIRMS_NO_FOUR_PROBE_SEPARATOR"
def canon(v):return json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False)
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--input",type=Path,default=SRC);ap.add_argument("--generic",type=Path,default=GEN);ap.add_argument("--output",type=Path,default=OUT);ns=ap.parse_args();s=json.loads(ns.input.read_text());g=json.loads(ns.generic.read_text());term=s.get("terminal");positive=term in {YES,NO};generic=(g.get("all_checks") is True and ((term==YES and g.get("decision")=="ACCEPT_YES") or (term==NO and g.get("decision")=="ACCEPT_NO")));bound=all(s.get(k) is False and g.get(k) is False for k in ("ADAPTIVE_TREE_OPTIMALITY","MINIMUM_FULL_FINITE_OPTIMUM_PROBES","HARDWARE_MEASUREMENT_MINIMUM","QG28_GLOBAL_STATE_MINIMALITY","novelty_authority","physical_quantum_advantage_claim"));shape=s.get("reconstruction",{})=={"orbits":715,"probes":384,"joint_classes":92,"unresolved_pairs":5895,"nondominated_coverage_classes":168};ifno=(term!=NO) or (s.get("EXISTS_SEPARATOR_AT_MOST_4") is False and s.get("MINIMUM_FIXED_PROBE_CARDINALITY")==5 and s.get("MINIMUM_FIXED_PROBE_CARDINALITY_AUTHORITY") is True);ifyes=(term!=YES) or (s.get("EXISTS_SEPARATOR_AT_MOST_4") is True and 1<=s.get("witness_size",0)<=4 and s.get("witness_covers_all_unresolved_pairs") is True and s.get("MINIMUM_FIXED_PROBE_CARDINALITY_AUTHORITY") is False);checks={"positive_terminal":positive,"generic":generic,"shape":shape,"no_branch":ifno,"yes_branch":ifyes,"authority_boundary":bound};ok=all(checks.values());responsibility="EXACT_FIXED_INDEXED_PROBE_MINIMUM_FIVE_REPLICATION" if ok and term==NO else ("FOUR_OR_FEWER_FIXED_PROBE_SEPARATOR_REPLICATION" if ok and term==YES else "CANNOT_CHECK");out={"schema":"ORIONQG.QG32C.NativeVerification.v1","decision":"ACCEPT" if ok else "REJECT","all_checks":ok,"checks":checks,"responsibility":responsibility,"EXISTS_SEPARATOR_AT_MOST_4":s.get("EXISTS_SEPARATOR_AT_MOST_4") if ok else None,"MINIMUM_FIXED_PROBE_CARDINALITY":5 if ok and term==NO else None,"MINIMUM_FIXED_PROBE_CARDINALITY_AUTHORITY":bool(ok and term==NO),"ADAPTIVE_TREE_OPTIMALITY":False,"MINIMUM_FULL_FINITE_OPTIMUM_PROBES":False,"HARDWARE_MEASUREMENT_MINIMUM":False,"QG28_GLOBAL_STATE_MINIMALITY":False,"novelty_authority":False,"physical_quantum_advantage_claim":False};ns.output.parent.mkdir(parents=True,exist_ok=True);ns.output.write_text(json.dumps(out,indent=2,sort_keys=True)+"\n");print(TOKEN+canon({"decision":out["decision"],"responsibility":responsibility,"minimum":out["MINIMUM_FIXED_PROBE_CARDINALITY"]}));return 0
if __name__=="__main__":raise SystemExit(main())
