#!/usr/bin/env python3
"""Native ORION-Q authority gate for QG-33 SixLCU label-vs-value result."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
A=ROOT/"artifacts/orion-qg-qg33-sixlcu-label-value.json";G=ROOT/"artifacts/orion-qg-qg33-generic-verification.json";P=ROOT/"development/orion-qg-regime-geometry/QG33_SIXLCU_LABEL_VALUE_PROTOCOL_V1.md";OUT=ROOT/"artifacts/orion-qg-qg33-native-verification.json";TOKEN="ORIONQG_QG33_NATIVE="
SEP="QG33_SIXLCU_EXACT_LABEL_QUOTIENT_IS_NOT_EXACT_VALUE_QUOTIENT__N2_COMPLETE";SUFF="QG33_SIXLCU_ONE_LITERAL_LABEL_QUOTIENT_ALSO_VALUE_SUFFICIENT__N2_COMPLETE"
def canon(v):return json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False)
def valid(r):
 u={k:v for k,v in r.items() if k!="result_digest"};return r.get("result_digest")==hashlib.sha256(canon(u).encode()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--analyzer",type=Path,default=A);ap.add_argument("--generic",type=Path,default=G);ap.add_argument("--output",type=Path,default=OUT);ns=ap.parse_args();a=json.loads(ns.analyzer.read_text());g=json.loads(ns.generic.read_text());term=a.get("terminal");label=a.get("LABEL_QUOTIENT_VALUE_SUFFICIENT");expected="ACCEPT_LABEL_VALUE_SUFFICIENCY" if term==SUFF else ("ACCEPT_LABEL_VALUE_SEPARATION" if term==SEP else "")
 checks={"analyzer_digest":valid(a),"protocol_bound":a.get("protocol_sha256")==hashlib.sha256(P.read_bytes()).hexdigest(),"parents":all(a.get("parent_checks",{}).values()),"complete_domain":a.get("COMPLETE_N2_DOMAIN") is True and a.get("instance_count")==38760,"terminal_decided":term in {SEP,SUFF},"terminal_consistency":(term==SEP and label is False) or (term==SUFF and label is True),"generic":g.get("decision")==expected and g.get("all_checks") is True,"digest_bound":g.get("source_result_digest")==a.get("result_digest"),"label_authority_exact":a.get("label_confusion",{}).get("errors")==0 and a.get("p0_confusion",{}).get("errors")==0,"no_feature_invention":a.get("NO_POST_OUTCOME_FEATURE_INVENTION") is True,"scope":all(a.get(k) is False and g.get(k) is False for k in ("ALL_N_VALUE_THEOREM","GLOBAL_PREDICATE_MINIMALITY","NEW_FEATURE_VOCABULARY_AUTHORITY","novelty_authority","physical_quantum_advantage_claim"))};ok=all(checks.values());responsibility=("N2_LABEL_QUOTIENT_VALUE_SUFFICIENCY_ONLY" if label else "N2_LABEL_VALUE_SEPARATION_AND_FROZEN_FEATURE_FLOOR_ONLY") if ok else "CANNOT_CHECK"
 out={"schema":"ORIONQG.QG33.NativeVerification.v1","decision":expected if ok else "REJECT","responsibility":responsibility,"all_checks":bool(ok),"checks":checks,"source_result_digest":a.get("result_digest"),"LABEL_QUOTIENT_VALUE_SUFFICIENT":label if ok else None,"FULL_FEATURE_VECTOR_VALUE_SUFFICIENT":a.get("FULL_FEATURE_VECTOR_VALUE_SUFFICIENT") if ok else None,"COMPLETE_N2_DOMAIN":bool(ok),"NO_POST_OUTCOME_FEATURE_INVENTION":bool(ok),"ALL_N_VALUE_THEOREM":False,"GLOBAL_PREDICATE_MINIMALITY":False,"NEW_FEATURE_VOCABULARY_AUTHORITY":False,"novelty_authority":False,"physical_quantum_advantage_claim":False};ns.output.parent.mkdir(parents=True,exist_ok=True);ns.output.write_text(json.dumps(out,indent=2,sort_keys=True)+"\n");print(TOKEN+canon({"decision":out["decision"],"responsibility":responsibility,"label_value_sufficient":out["LABEL_QUOTIENT_VALUE_SUFFICIENT"],"feature_value_sufficient":out["FULL_FEATURE_VECTOR_VALUE_SUFFICIENT"]}));return 0
if __name__=="__main__":raise SystemExit(main())
