#!/usr/bin/env python3
"""Native ORION-Q authority gate for QG-34 adaptive minimax identification."""
from __future__ import annotations
import argparse,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];SRC=ROOT/"artifacts/orion-qg-qg34-adaptive-probe-tree.json";GEN=ROOT/"artifacts/orion-qg-qg34-generic-verification.json";OUT=ROOT/"artifacts/orion-qg-qg34-native-verification.json";TOKEN="ORIONQG_QG34_NATIVE=";TERM="QG34_EXACT_MINIMAX_ADAPTIVE_PROBE_DEPTH_MACHINE_CHECKED"
def canon(v):return json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False)
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--input',type=Path,default=SRC);ap.add_argument('--generic',type=Path,default=GEN);ap.add_argument('--output',type=Path,default=OUT);ns=ap.parse_args();s=json.loads(ns.input.read_text());g=json.loads(ns.generic.read_text());strong=('EXACT_FIXED_PROBE_MINIMUM_BOUND','ADAPTIVITY_ADVANTAGE_OVER_EXACT_FIXED_MINIMUM','MINIMUM_FULL_FINITE_OPTIMUM_PROBES','HARDWARE_MEASUREMENT_MINIMUM','QG28_GLOBAL_STATE_MINIMALITY','novelty_authority','physical_quantum_advantage_claim');checks={'terminal':s.get('terminal')==TERM,'generic':g.get('all_checks') is True and g.get('decision')=='ACCEPT_EXACT_ADAPTIVE_MINIMAX','universe':s.get('universe',{}).get('orbits')==715 and s.get('universe',{}).get('probes')==384 and s.get('universe',{}).get('joint_classes')==92,'depth':isinstance(s.get('worst_case_depth'),int) and 0<=s.get('worst_case_depth')<=5,'class_depths':isinstance(s.get('class_depths'),list) and len(s['class_depths'])==92,'exact_authority':s.get('EXACT_ADAPTIVE_MINIMAX_AUTHORITY') is True,'boundary':all(s.get(k) is False and g.get(k) is False for k in strong)};ok=all(checks.values());out={'schema':'ORIONQG.QG34.NativeVerification.v1','decision':'ACCEPT_EXACT_ADAPTIVE_MINIMAX' if ok else 'REJECT','all_checks':ok,'checks':checks,'responsibility':'EXACT_ADAPTIVE_IDENTIFICATION_ON_715_ORBIT_JOINT_SUMMARY_QUERY_ONLY' if ok else 'CANNOT_CHECK','worst_case_depth':s.get('worst_case_depth') if ok else None,'depth_histogram':s.get('depth_histogram') if ok else None,'EXACT_ADAPTIVE_MINIMAX_AUTHORITY':bool(ok),'EXACT_FIXED_PROBE_MINIMUM_BOUND':False,'ADAPTIVITY_ADVANTAGE_OVER_EXACT_FIXED_MINIMUM':False,'MINIMUM_FULL_FINITE_OPTIMUM_PROBES':False,'HARDWARE_MEASUREMENT_MINIMUM':False,'QG28_GLOBAL_STATE_MINIMALITY':False,'novelty_authority':False,'physical_quantum_advantage_claim':False};ns.output.parent.mkdir(parents=True,exist_ok=True);ns.output.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(TOKEN+canon({'decision':out['decision'],'responsibility':out['responsibility'],'worst_depth':out['worst_case_depth']}));return 0
if __name__=='__main__':raise SystemExit(main())
