#!/usr/bin/env python3
"""Native ORION-Q authority gate for QG-35 summary-conditioned fixed complexity."""
from __future__ import annotations
import argparse,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];SRC=ROOT/"artifacts/orion-qg-qg35-summary-conditioned-fixed.json";GEN=ROOT/"artifacts/orion-qg-qg35-generic-verification.json";OUT=ROOT/"artifacts/orion-qg-qg35-native-verification.json";TOKEN="ORIONQG_QG35_NATIVE=";TERM="QG35_EXACT_SUMMARY_CONDITIONED_FIXED_PROBE_COMPLEXITY_MACHINE_CHECKED"
def canon(v):return json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False)
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--input',type=Path,default=SRC);ap.add_argument('--generic',type=Path,default=GEN);ap.add_argument('--output',type=Path,default=OUT);ns=ap.parse_args();s=json.loads(ns.input.read_text());g=json.loads(ns.generic.read_text());strong=('ADAPTIVE_MINIMAX_AUTHORITY','STRICT_ADAPTIVITY_ADVANTAGE_AUTHORITY','UNIVERSAL_FIXED_MINIMUM_REDERIVED','MINIMUM_FULL_FINITE_OPTIMUM_PROBES','HARDWARE_MEASUREMENT_MINIMUM','QG28_GLOBAL_STATE_MINIMALITY','novelty_authority','physical_quantum_advantage_claim');checks={'terminal':s.get('terminal')==TERM,'generic':g.get('all_checks') is True and g.get('decision')=='ACCEPT_EXACT_SUMMARY_CONDITIONED_FIXED','universe':s.get('universe',{}).get('orbits')==715 and s.get('universe',{}).get('probes')==384 and s.get('universe',{}).get('joint_classes')==92,'minima':isinstance(s.get('class_minima'),list) and len(s['class_minima'])==92 and all(isinstance(x,int) and 0<=x<=5 for x in s['class_minima']),'F_star':s.get('worst_case_class_conditioned_fixed_minimum')==max(s.get('class_minima',[-1])),'exact':s.get('EXACT_SUMMARY_CONDITIONED_FIXED_AUTHORITY') is True,'boundary':all(s.get(k) is False and g.get(k) is False for k in strong)};ok=all(checks.values());out={'schema':'ORIONQG.QG35.NativeVerification.v1','decision':'ACCEPT_EXACT_SUMMARY_CONDITIONED_FIXED' if ok else 'REJECT','all_checks':ok,'checks':checks,'responsibility':'EXACT_CLASS_CONDITIONED_NONADAPTIVE_OBSERVATION_COMPLEXITY_ON_92_SUMMARY_CLASSES_ONLY' if ok else 'CANNOT_CHECK','class_minima':s.get('class_minima') if ok else None,'F_star':s.get('worst_case_class_conditioned_fixed_minimum') if ok else None,'EXACT_SUMMARY_CONDITIONED_FIXED_AUTHORITY':bool(ok),'ADAPTIVE_MINIMAX_AUTHORITY':False,'STRICT_ADAPTIVITY_ADVANTAGE_AUTHORITY':False,'UNIVERSAL_FIXED_MINIMUM_REDERIVED':False,'MINIMUM_FULL_FINITE_OPTIMUM_PROBES':False,'HARDWARE_MEASUREMENT_MINIMUM':False,'QG28_GLOBAL_STATE_MINIMALITY':False,'novelty_authority':False,'physical_quantum_advantage_claim':False};ns.output.parent.mkdir(parents=True,exist_ok=True);ns.output.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(TOKEN+canon({'decision':out['decision'],'responsibility':out['responsibility'],'F_star':out['F_star']}));return 0
if __name__=='__main__':raise SystemExit(main())
