#!/usr/bin/env python3
"""Native ORION-Q authority gate for QG-36 fair receipt composition."""
from __future__ import annotations
import argparse,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];SRC=ROOT/"artifacts/orion-qg-qg36-fair-adaptivity-composition.json";GEN=ROOT/"artifacts/orion-qg-qg36-generic-verification.json";OUT=ROOT/"artifacts/orion-qg-qg36-native-verification.json";TOKEN="ORIONQG_QG36_NATIVE=";STRICT="QG36_TARE_POSTSUMMARY_ADAPTIVITY_STRICTLY_REDUCES_WORST_CASE_OBSERVATION_COUNT";TIE="QG36_NO_STRICT_POSTSUMMARY_ADAPTIVITY_ADVANTAGE__EXACT_TIE"
def canon(v):return json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False)
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--input',type=Path,default=SRC);ap.add_argument('--generic',type=Path,default=GEN);ap.add_argument('--output',type=Path,default=OUT);ns=ap.parse_args();s=json.loads(ns.input.read_text());g=json.loads(ns.generic.read_text());term=s.get('terminal');positive=term==STRICT;comparable=term in {STRICT,TIE};checks={'generic':g.get('all_checks') is True and g.get('decision')=='ACCEPT_FAIR_COMPARISON','terminal':comparable,'pointwise':s.get('pointwise_violation_count')==0,'maxima':isinstance(s.get('D_star'),int) and isinstance(s.get('F_star'),int) and s.get('D_star')<=s.get('F_star'),'authority':s.get('EXACT_FAIR_FIXED_VS_ADAPTIVE_COMPARISON_AUTHORITY') is True,'positive_exact':s.get('TARE_POSTSUMMARY_ADAPTIVITY_STRICTLY_REDUCES_WORST_CASE_OBSERVATION_COUNT') is positive,'boundary':all(s.get(k) is False and g.get(k) is False for k in ('COMPILER_OPTIMIZATION_COST_ADVANTAGE','HARDWARE_MEASUREMENT_MINIMUM','MINIMUM_FULL_FINITE_OPTIMUM_PROBES','GENERIC_ADAPTIVE_TESTING_NOVELTY','AUTONOMOUS_SKILL_SELECTION_AUTHORITY','physical_quantum_advantage_claim'))};ok=all(checks.values());resp='STRICT_POSTSUMMARY_OBSERVATION_COUNT_ADAPTIVITY_ADVANTAGE' if ok and positive else ('EXACT_POSTSUMMARY_FIXED_ADAPTIVE_WORST_CASE_TIE' if ok else 'CANNOT_CHECK');out={'schema':'ORIONQG.QG36.NativeVerification.v1','decision':'ACCEPT_FAIR_COMPARISON' if ok else 'REJECT','all_checks':ok,'checks':checks,'responsibility':resp,'D_star':s.get('D_star') if ok else None,'F_star':s.get('F_star') if ok else None,'TARE_POSTSUMMARY_ADAPTIVITY_STRICTLY_REDUCES_WORST_CASE_OBSERVATION_COUNT':bool(ok and positive),'EXACT_FAIR_FIXED_VS_ADAPTIVE_COMPARISON_AUTHORITY':bool(ok),'COMPILER_OPTIMIZATION_COST_ADVANTAGE':False,'HARDWARE_MEASUREMENT_MINIMUM':False,'MINIMUM_FULL_FINITE_OPTIMUM_PROBES':False,'GENERIC_ADAPTIVE_TESTING_NOVELTY':False,'AUTONOMOUS_SKILL_SELECTION_AUTHORITY':False,'physical_quantum_advantage_claim':False};ns.output.parent.mkdir(parents=True,exist_ok=True);ns.output.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(TOKEN+canon({'decision':out['decision'],'responsibility':resp,'D_star':out['D_star'],'F_star':out['F_star'],'strict':out['TARE_POSTSUMMARY_ADAPTIVITY_STRICTLY_REDUCES_WORST_CASE_OBSERVATION_COUNT']}));return 0
if __name__=='__main__':raise SystemExit(main())
