#!/usr/bin/env python3
from __future__ import annotations
import argparse,hashlib,json
from fractions import Fraction
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];SRC=ROOT/'artifacts/orion-qg-qg38-observation-hierarchy.json';A=ROOT/'research/extensions/orion-qg/QG38_PARENT_QG36_PROJECTION.json';B=ROOT/'research/extensions/orion-qg/QG38_PARENT_QG32C_PROJECTION.json';OUT=ROOT/'artifacts/orion-qg-qg38-generic-verification.json';STRICT='QG38_EXACT_STRICT_OBSERVATION_COST_HIERARCHY_MACHINE_CHECKED';CANNOT='QG38_CANNOT_CHECK_PARENT_OR_SEMANTIC_BINDING';Q32='4a4a0429f2e0d9d3a65573549e31e28f7ac8ca473e905d86c0f8f497111be64d'
def c(v):return json.dumps(v,sort_keys=True,separators=(',',':'),allow_nan=False)
def valid(d):return d.get('result_digest')==hashlib.sha256(c({k:v for k,v in d.items() if k!='result_digest'}).encode()).hexdigest()
def r(x,y):
 if y==0:return None
 z=Fraction(x,y);return f'{z.numerator}/{z.denominator}'
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--input',type=Path,default=SRC);ap.add_argument('--qg36',type=Path,default=A);ap.add_argument('--qg32c',type=Path,default=B);ap.add_argument('--output',type=Path,default=OUT);n=ap.parse_args();s=json.loads(n.input.read_text());a=json.loads(n.qg36.read_text());b=json.loads(n.qg32c.read_text());D,F,U=a.get('D_star'),a.get('F_star'),b.get('MINIMUM_FIXED_PROBE_CARDINALITY');uni={'orbits':715,'probes':384,'joint_classes':92};parent=valid(a) and valid(b) and a.get('both_accept') is True and b.get('both_accept') is True and a.get('EXACT_FAIR_FIXED_VS_ADAPTIVE_COMPARISON_AUTHORITY') is True and b.get('MINIMUM_FIXED_PROBE_CARDINALITY_AUTHORITY') is True and b.get('EXISTS_SEPARATOR_AT_MOST_4') is False and a.get('qg32_parent_sha256')==b.get('qg32_parent_sha256')==Q32 and a.get('universe')==b.get('universe')==uni and all(isinstance(x,int) and not isinstance(x,bool) and x>=0 for x in (D,F,U));term=CANNOT if not parent else (STRICT if D<F<U else ('QG38_EXACT_THREE_WAY_TIE_MACHINE_CHECKED' if D==F==U else ('QG38_EXACT_NONSTRICT_MONOTONE_HIERARCHY_MACHINE_CHECKED' if D<=F<=U else 'QG38_PARENT_INCONSISTENCY_OR_NONMONOTONE_MODEL_ORDERING')));checks={'source_digest':valid(s),'parent':parent,'terminal':s.get('terminal')==term,'values':s.get('models',{}).get('D_star',{}).get('value')==D and s.get('models',{}).get('F_star',{}).get('value')==F and s.get('models',{}).get('U_star',{}).get('value')==U,'gaps':s.get('gaps')=={'F_minus_D':F-D,'U_minus_F':U-F,'U_minus_D':U-D} if parent else False,'ratios':s.get('ratios')=={'F_over_D':r(F,D),'U_over_F':r(U,F),'U_over_D':r(U,D)} if parent else False,'ceiling':all(s.get(k) is False for k in ('HARDWARE_MEASUREMENT_MINIMUM','MINIMUM_FULL_FINITE_OPTIMUM_PROBES','COMPILER_OPTIMIZATION_COST_ADVANTAGE','COMPILER_RUNTIME_ADVANTAGE','GENERIC_ACTIVE_LEARNING_NOVELTY','AUTONOMOUS_SKILL_SELECTION_AUTHORITY','physical_quantum_advantage_claim','novelty_authority'))};ok=all(checks.values());o={'schema':'ORIONQG.QG38.GenericVerification.v1','decision':'ACCEPT' if ok else 'REJECT','all_checks':ok,'checks':checks,'terminal':term,'D_star':D if parent else None,'F_star':F if parent else None,'U_star':U if parent else None};n.output.parent.mkdir(parents=True,exist_ok=True);n.output.write_text(json.dumps(o,indent=2,sort_keys=True)+'\n');print('ORIONQG_QG38_GENERIC='+c({'decision':o['decision'],'terminal':term}));return 0
if __name__=='__main__':raise SystemExit(main())
