#!/usr/bin/env python3
"""Native ORION-Q authority gate for QG-42 bounded pytket transfer."""
from __future__ import annotations
import argparse,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];SRC=ROOT/'artifacts/orion-qg-qg42-pytket.json';GEN=ROOT/'artifacts/orion-qg-qg42-generic-verification.json';OUT=ROOT/'artifacts/orion-qg-qg42-native-verification.json';TOKEN='ORIONQG_QG42_NATIVE=';ALLOWED={'QG42_PYTKET_SELECTION_SEPARATION_BOTH_TOPOLOGIES_MACHINE_CHECKED','QG42_PYTKET_SELECTION_SEPARATION_ONE_TOPOLOGY_ONLY','QG42_PYTKET_NO_SELECTION_SEPARATION_ON_FROZEN_PANEL'}
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--input',type=Path,default=SRC);ap.add_argument('--generic',type=Path,default=GEN);ap.add_argument('--output',type=Path,default=OUT);a=ap.parse_args();s=json.loads(a.input.read_text());g=json.loads(a.generic.read_text());checks={'generic':g.get('all_checks') is True and g.get('decision')=='ACCEPT_BOUNDED_PYTKET_TRANSFER','source_terminal':s.get('terminal') in ALLOWED,'version':s.get('pytket_version')=='2.18.1','selection_agreement':s.get('selection_separation',{}).get('line6')==g.get('independent_selection',{}).get('line6') and s.get('selection_separation',{}).get('ring6')==g.get('independent_selection',{}).get('ring6'),'scope':all(s.get(k) is False for k in ('ALL_CIRCUIT_THEOREM','ALL_PYTKET_VERSION_CLAIM','OPTIMAL_ROUTING_CLAIM','COMPARATIVE_COMPILER_PERFORMANCE','HARDWARE_NOISE_OR_FT_CLAIM','physical_quantum_advantage_claim','GENERIC_SYMMETRY_DECISION_THEORY_NOVELTY','novelty_authority'))};ok=all(checks.values());o={'schema':'ORIONQG.QG42.NativeVerification.v1','decision':'ACCEPT_BOUNDED_PRODUCTION_COMPILER_INFORMATION_RESULT' if ok else 'REJECT','terminal':s.get('terminal') if ok else 'QG42_CANNOT_CHECK','all_checks':bool(ok),'checks':checks,'selection_separation':s.get('selection_separation') if ok else None,'BOUNDED_PYTKET_SELECTION_INFORMATION_AUTHORITY':bool(ok),'ALL_CIRCUIT_THEOREM':False,'COMPARATIVE_COMPILER_PERFORMANCE':False,'HARDWARE_NOISE_OR_FT_CLAIM':False,'physical_quantum_advantage_claim':False,'novelty_authority':False};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(o,indent=2,sort_keys=True)+'\n');print(TOKEN+json.dumps({'decision':o['decision'],'terminal':o['terminal']},sort_keys=True,separators=(',',':')));return 0
if __name__=='__main__':raise SystemExit(main())
