#!/usr/bin/env python3
"""Native ORION-Q authority gate for QG-7e V2."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];A=ROOT/"artifacts/orion-qg-qg7e-v2-pp-single-pinner.json";G=ROOT/"artifacts/orion-qg-qg7e-v2-generic-verification.json";PROTO=ROOT/"development/orion-qg-regime-geometry/QG7E_V2_PP_SINGLE_PINNER_PROTOCOL.md";OUT=ROOT/"artifacts/orion-qg-qg7e-v2-native-verification.json";TOKEN="ORIONQG_QG7E_V2_NATIVE=";POS="QG7E_V2_PP_SINGLE_PINNER_CLOSED_ALL_HIDDEN_ENVIRONMENTS__CHAIN_OPEN"
def canon(v):return json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False)
def vd(r):
 u={k:v for k,v in r.items() if k!="result_digest"};return r.get("result_digest")==hashlib.sha256(canon(u).encode()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--analyzer",type=Path,default=A);ap.add_argument("--generic",type=Path,default=G);ap.add_argument("--output",type=Path,default=OUT);x=ap.parse_args();a=json.loads(x.analyzer.read_text());g=json.loads(x.generic.read_text());c={"analyzer":a.get("terminal")==POS and a.get("all_gates") is True and vd(a),"generic":g.get("decision")=="ACCEPT_PP_SINGLE_PINNER_ALL_N" and g.get("all_checks") is True,"bound":g.get("source_result_digest")==a.get("result_digest"),"protocol":a.get("protocol_sha256")==hashlib.sha256(PROTO.read_bytes()).hexdigest(),"counts":a.get("visible",{}).get("failures")==32556 and a.get("product_domain")==133349376 and a.get("relocation",{}).get("residual")==5684 and a.get("dplus",{}).get("residual")==380 and a.get("bprime",{}).get("final_residual")==0,"bindings":a.get("dplus",{}).get("control_failures")==[] and a.get("bprime",{}).get("witness_failures")==[] and a.get("bprime",{}).get("reference_failures")==[],"scope":a.get("PP_SINGLE_PINNER_ALL_N") is True and g.get("PP_SINGLE_PINNER_ALL_N") is True and a.get("CHAIN_ALL_N") is False and g.get("CHAIN_ALL_N") is False and a.get("GLOBAL_BDOUBLEPRIME_COMPLETENESS") is False and g.get("GLOBAL_BDOUBLEPRIME_COMPLETENESS") is False,"authority":a.get("novelty_authority") is False and a.get("r6_authority") is False and a.get("physical_quantum_advantage_claim") is False};ok=all(c.values());o={"schema":"ORIONQG.QG7E.V2.NativeVerification.v1","decision":"ACCEPT_PP_SINGLE_PINNER_ALL_N" if ok else "REJECT","responsibility":"PP_SINGLE_PINNER_NORMALIZATION" if ok else "CANNOT_CHECK","all_checks":bool(ok),"checks":c,"source_result_digest":a.get("result_digest"),"PP_SINGLE_PINNER_ALL_N":bool(ok),"CHAIN_ALL_N":False,"GLOBAL_BDOUBLEPRIME_COMPLETENESS":False,"novelty_authority":False,"r6_authority":False,"physical_quantum_advantage_claim":False};x.output.parent.mkdir(parents=True,exist_ok=True);x.output.write_text(json.dumps(o,indent=2,sort_keys=True)+"\n");print(TOKEN+canon({"decision":o["decision"],"all_checks":o["all_checks"],"PP":o["PP_SINGLE_PINNER_ALL_N"],"chain":False}));return 0
if __name__=="__main__":raise SystemExit(main())
