#!/usr/bin/env python3
"""Native ORION-Q authority gate for QG-7f representation-premise audit."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];A=ROOT/"artifacts/orion-qg-qg7f-chain-representation-audit.json";G=ROOT/"artifacts/orion-qg-qg7f-generic-verification.json";P=ROOT/"development/orion-qg-regime-geometry/QG7F_CHAIN_REPRESENTATION_AUDIT_PROTOCOL_V1.md";OUT=ROOT/"artifacts/orion-qg-qg7f-native-verification.json";TOKEN="ORIONQG_QG7F_NATIVE=";POS="QG7F_TWO_COORD_REDUCTION_REFUTED__TAG3_MULTI_COMM_S2_CONFIGURATION"
def canon(v):return json.dumps(v,sort_keys=True,separators=(",",":"),allow_nan=False)
def vd(r):
 d={k:v for k,v in r.items() if k!="result_digest"};return r.get("result_digest")==hashlib.sha256(canon(d).encode()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--analyzer",type=Path,default=A);ap.add_argument("--generic",type=Path,default=G);ap.add_argument("--output",type=Path,default=OUT);x=ap.parse_args();a=json.loads(x.analyzer.read_text());g=json.loads(x.generic.read_text())
 c={"analyzer":a.get("terminal")==POS and a.get("representation_premise_refuted") is True and vd(a),"generic":g.get("decision")=="ACCEPT_REPRESENTATION_PREMISE_REFUTATION" and g.get("all_checks") is True,"bound":g.get("source_result_digest")==a.get("result_digest"),"protocol":a.get("protocol_sha256")==hashlib.sha256(P.read_bytes()).hexdigest(),"parent":a.get("gates",{}).get("parent_custody") is True,"candidate":a.get("gates",{}).get("B_comm_s2_irreducible") is True and a.get("gates",{}).get("C_comm_s2_irreducible") is True and a.get("gates",{}).get("different_comm_s2_support_pairs") is True and a.get("gates",{}).get("tag_weight_three") is True,"scope":a.get("CHAIN_REPRESENTATION_COMPLETE") is False and a.get("CHAIN_ALL_N") is False and a.get("GLOBAL_BDOUBLEPRIME_COMPLETENESS") is False and a.get("FIFTH_REGIME_FOUND") is False,"authority":a.get("novelty_authority") is False and a.get("r6_authority") is False and a.get("physical_quantum_advantage_claim") is False};ok=all(c.values());o={"schema":"ORIONQG.QG7F.NativeVerification.v1","decision":"ACCEPT_REPRESENTATION_PREMISE_REFUTATION" if ok else "REJECT","responsibility":"REPRESENTATION_PREMISE_REFUTATION" if ok else "CANNOT_CHECK","all_checks":bool(ok),"checks":c,"source_result_digest":a.get("result_digest"),"representation_premise_refuted":bool(ok),"CHAIN_REPRESENTATION_COMPLETE":False,"CHAIN_ALL_N":False,"GLOBAL_BDOUBLEPRIME_COMPLETENESS":False,"FIFTH_REGIME_FOUND":False,"novelty_authority":False,"r6_authority":False,"physical_quantum_advantage_claim":False};x.output.parent.mkdir(parents=True,exist_ok=True);x.output.write_text(json.dumps(o,indent=2,sort_keys=True)+"\n");print(TOKEN+canon({"decision":o["decision"],"responsibility":o["responsibility"],"all_checks":ok}));return 0
if __name__=="__main__":raise SystemExit(main())
