#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; RESULT=ROOT/'artifacts/orion-qg-programme-scientific-closure.json'; GENERIC=ROOT/'artifacts/orion-qg-programme-closure-generic.json'; OUT=ROOT/'artifacts/orion-qg-programme-closure-native.json'; TOKEN='ORIONQG_PROGRAMME_CLOSURE_NATIVE='
def canonical(v): return json.dumps(v,sort_keys=True,separators=(',',':'),allow_nan=False)
def main():
 a=json.loads(RESULT.read_text()); g=json.loads(GENERIC.read_text()); expected='ORION_QG_PROGRAMME_SCIENTIFICALLY_CLOSED__THEOREMS_REFUTATIONS_AND_BOUNDED_CANNOT_CHECKS_RECEIPTED__NOT_NOVELTY_AUTHORITY'; checks={'analyzer_closed':a.get('scientifically_closed') is True and a.get('terminal')==expected,'generic_accept':g.get('decision')=='ACCEPT_PROGRAMME_SCIENTIFIC_CLOSURE' and g.get('all_checks') is True,'qg7d_cannot_check_preserved':'qg7d' in a.get('bounded_cannot_checks',{}) and any('TARE all-n' in x for x in a.get('unproved_not_promoted',[])),'qg11_cannot_check_preserved':'qg11' in a.get('bounded_cannot_checks',{}),'no_authority_laundering':a.get('novelty_authority') is False and a.get('r6_authority') is False and a.get('physical_quantum_advantage_claim') is False and a.get('publication_acceptance_authority') is False,'new_freeze_required':a.get('future_reopen_requires_new_freeze') is True}; decision='ACCEPT_PROGRAMME_SCIENTIFIC_CLOSURE' if all(checks.values()) else 'REJECT'; out={'schema':'ORION.QG.ProgrammeClosureNative.v1','issue':'SzeChunYiu/ORION#839','programme_issue':'SzeChunYiu/ORION#740','decision':decision,'responsibility':'SCIENTIFIC_PROGRAMME_TERMINAL_ADJUDICATION' if decision.startswith('ACCEPT') else 'CANNOT_CHECK','checks':checks,'all_checks':all(checks.values()),'terminal':a.get('terminal'),'scientifically_closed':decision.startswith('ACCEPT'),'novelty_authority':False,'r6_authority':False,'physical_quantum_advantage_claim':False}; OUT.parent.mkdir(parents=True,exist_ok=True); OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n'); print(TOKEN+canonical(out)); return 0
if __name__=='__main__': raise SystemExit(main())
