#!/usr/bin/env python3
"""Run the independent V4 verifier against the exact reconstructed pre-outcome protocol.

The execution receipt binds the pre-outcome protocol generated by
freeze_confirmatory_v4.py, while the execution commit stores a post-outcome
metadata update at the same path. This wrapper reconstructs the former from the
frozen constructor, verifies its digest, runs the scorer-independent verifier,
and restores every overwritten byte in a finally block.
"""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CONF = ROOT / "research/self-orion-v4/confirmatory"
PROTOCOL = ROOT / "papers/orion-15-self-orion/protocol/SELF_ORION_V4_REVISION_LEVEL_PROTOCOL_V1.json"
FREEZE_RECEIPT = CONF / "CONFIRMATORY_FREEZE_RECEIPT_2026-08-27.json"
CONSTRUCTOR = CONF / "freeze_confirmatory_v4.py"
VERIFIER = Path(__file__).resolve().parent / "verify_v4_independent_v1.py"


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def require(ok: bool, msg: str) -> None:
    if not ok:
        raise AssertionError(msg)


def main() -> int:
    original_protocol = PROTOCOL.read_bytes()
    original_freeze = FREEZE_RECEIPT.read_bytes()
    expected = json.loads(original_freeze)["digests"]["protocol_sha256"]
    env = dict(os.environ)
    env["PYTHONPATH"] = str(ROOT / "src") + (os.pathsep + env["PYTHONPATH"] if env.get("PYTHONPATH") else "")
    try:
        build = subprocess.run([sys.executable, str(CONSTRUCTOR)], cwd=ROOT, env=env, capture_output=True, text=True)
        require(build.returncode == 0, f"constructor failed rc={build.returncode}: {build.stdout}\n{build.stderr}")
        regenerated = PROTOCOL.read_bytes()
        require(sha(regenerated) == expected, f"reconstructed protocol digest mismatch: {sha(regenerated)} != {expected}")
        verify = subprocess.run([sys.executable, str(VERIFIER)], cwd=ROOT, env=env, capture_output=True, text=True)
        sys.stdout.write(verify.stdout)
        sys.stderr.write(verify.stderr)
        require(verify.returncode == 0, f"independent verifier rc={verify.returncode}")
    finally:
        PROTOCOL.write_bytes(original_protocol)
        FREEZE_RECEIPT.write_bytes(original_freeze)
    require(PROTOCOL.read_bytes() == original_protocol, "post-outcome protocol restore failed")
    require(FREEZE_RECEIPT.read_bytes() == original_freeze, "freeze receipt restore failed")
    print("ORION_15_V4_INDEPENDENT_AUDIT_WITH_RECONSTRUCTED_PROTOCOL=PASS")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except AssertionError as exc:
        print(f"ORION_15_V4_RECONSTRUCTED_AUDIT=FAIL: {exc}", file=sys.stderr)
        raise SystemExit(2)
