from .qg3_positive_forecast import QG3_POSITIVE_FORECAST_CAMPAIGN_MANIFEST
from .qg8_support_phase import QG8_SUPPORT_PHASE_CAMPAIGN_MANIFEST
from .qg12_sixlcu_p0 import QG12_SIXLCU_P0_CAMPAIGN_MANIFEST
from .qg13_v3_three_column import QG13V3_THREE_COLUMN_CAMPAIGN_MANIFEST

__all__ = [
    "QG3_POSITIVE_FORECAST_CAMPAIGN_MANIFEST",
    "QG8_SUPPORT_PHASE_CAMPAIGN_MANIFEST",
    "QG12_SIXLCU_P0_CAMPAIGN_MANIFEST",
    "QG13V3_THREE_COLUMN_CAMPAIGN_MANIFEST",
]
