from .qg3_positive_forecast import QG3_POSITIVE_FORECAST_CAMPAIGN_MANIFEST
from .qg6_syndrome_compression import QG6_SYNDROME_COMPRESSION_CAMPAIGN_MANIFEST

__all__ = [
    "QG3_POSITIVE_FORECAST_CAMPAIGN_MANIFEST",
    "QG6_SYNDROME_COMPRESSION_CAMPAIGN_MANIFEST",
]
