from .qg3_positive_forecast import QG3_POSITIVE_FORECAST_CAMPAIGN_MANIFEST
from .qg13_v2_combined_edit import QG13V2_COMBINED_EDIT_CAMPAIGN_MANIFEST

__all__ = [
    "QG3_POSITIVE_FORECAST_CAMPAIGN_MANIFEST",
    "QG13V2_COMBINED_EDIT_CAMPAIGN_MANIFEST",
]
