"""Native ORION-Q admission for QG-13 V2 / QG-9 support-four theorem evidence."""
_LOAD='ORIONQG_QG13_V2_NATIVE_LOAD=';_DEC='ORIONQG_QG13_V2_NATIVE_DECISION='
def _decision(decision,next_phase):
    payload={'decision':decision,'support3_authority':False,'tightness4_authority':False,'novelty_authority':False,'scientific_scope':'FROZEN_R6I_SUPPORT4_ONLY'}
    code="import json;print('"+_DEC+"'+json.dumps("+repr(payload)+",sort_keys=True,separators=(',',':')))"
    return {'host_capability':'PYTHON','payload':{'code':code,'cwd':'.','timeout':30},'result_contract':{'kind':'SHELL_JSON_TOKEN','prefix':_DEC,'required_payload_values':[{'path':['decision'],'equals':decision},{'path':['support3_authority'],'equals':False},{'path':['tightness4_authority'],'equals':False},{'path':['novelty_authority'],'equals':False}],'evidence_rules':[{'evidence_key':'QG13V2_DECISION','path':['decision'],'transform':'STRING'}]},'next_phase':next_phase}
_LOAD_CODE=r'''
import hashlib,json
from pathlib import Path
a=json.loads(Path('artifacts/orion-qg-qg13-v2-support4.json').read_text());g=json.loads(Path('artifacts/orion-qg-qg13-v2-generic-verification.json').read_text())
u=dict(a);obs=u.pop('result_digest');can=json.dumps(u,sort_keys=True,separators=(',',':'),allow_nan=False)
out={'positive':a.get('terminal')=='QG13_V2_R6I_SUPPORT4_CANDIDATE_COMPLETE','digest':obs==hashlib.sha256(can.encode()).hexdigest(),'gates':all(a.get('gates',{}).values()),'generic':g.get('decision')=='ACCEPT' and all(g.get('checks',{}).values()),'w5':a.get('support5',{}).get('irreducible_count')==324 and a.get('support5',{}).get('unresolved_count')==0,'w4_boundary':a.get('support4_boundary',{}).get('unresolved_count')==36,'support3_false':a.get('support3_authority') is False,'tightness_false':a.get('tightness4_authority') is False,'novelty_false':a.get('novelty_authority') is False}
print('ORIONQG_QG13_V2_NATIVE_LOAD='+json.dumps(out,sort_keys=True,separators=(',',':')))
'''
_ACCEPT={k:['YES'] for k in ['QG13V2_POSITIVE','QG13V2_DIGEST','QG13V2_GATES','QG13V2_GENERIC','QG13V2_W5','QG13V2_W4','QG13V2_S3FALSE','QG13V2_TIGHTFALSE','QG13V2_NOVELFALSE']}
QG13_V2_SUPPORT4_CAMPAIGN_MANIFEST={'schema':'ORION.ResearchCampaignManifest.v1','campaign_id':'orion-qg:qg13-v2-r6i-support4','claim_id':'orion-qg:qg9-r6i-support4','initial_phase':'S0','initial_observations':{'QG13V2_NEED':'YES'},'authority_ceiling':'NON_AUTHORIZING_SUPPORT4_THEOREM_EVIDENCE','protected_refs':[],'capabilities':{
'qg13v2.load':{'host_capability':'PYTHON','payload':{'code':_LOAD_CODE,'cwd':'.','timeout':30},'declared_read_paths':['artifacts/orion-qg-qg13-v2-support4.json','artifacts/orion-qg-qg13-v2-generic-verification.json'],'result_contract':{'kind':'SHELL_JSON_TOKEN','prefix':_LOAD,'required_payload_values':[{'path':['novelty_false'],'equals':True}],'evidence_rules':[{'evidence_key':'QG13V2_POSITIVE','path':['positive'],'transform':'BOOL_YES_NO'},{'evidence_key':'QG13V2_DIGEST','path':['digest'],'transform':'BOOL_YES_NO'},{'evidence_key':'QG13V2_GATES','path':['gates'],'transform':'BOOL_YES_NO'},{'evidence_key':'QG13V2_GENERIC','path':['generic'],'transform':'BOOL_YES_NO'},{'evidence_key':'QG13V2_W5','path':['w5'],'transform':'BOOL_YES_NO'},{'evidence_key':'QG13V2_W4','path':['w4_boundary'],'transform':'BOOL_YES_NO'},{'evidence_key':'QG13V2_S3FALSE','path':['support3_false'],'transform':'BOOL_YES_NO'},{'evidence_key':'QG13V2_TIGHTFALSE','path':['tightness_false'],'transform':'BOOL_YES_NO'},{'evidence_key':'QG13V2_NOVELFALSE','path':['novelty_false'],'transform':'BOOL_YES_NO'}]},'next_phase':'D0'},
'qg13v2.accept':_decision('ACCEPT_SUPPORT4','ACCEPT_RECORDED'),'qg13v2.reject':_decision('REJECT','REJECT_RECORDED')},'phases':{
'S0':{'active_hard_obligations':['LOAD'],'responsibility_hypotheses':[{'hypothesis_id':'RESP:LOAD','expected_observations':{'QG13V2_NEED':['YES']}}],'interface_checks':[{'check_id':'IFACE:SERIALIZED','scope':'EVIDENCE_BINDING','state':'PASS'}],'revision_mechanics':[{'mechanic_id':'REV:WAIT','kind':'WAIT_EVIDENCE','write_coordinates':['EVIDENCE'],'cost':0.1}],'computation_actions':[{'action_id':'COMPUTE:LOAD','kind':'VERIFY','expected_decision_value':5.0,'cost':0.1,'discharges_obligations':['LOAD']}],'responsibility_bindings':{'RESP:LOAD':['REV:WAIT']},'selected_capabilities':{'COMPUTE:LOAD':'qg13v2.load'}},
'D0':{'active_hard_obligations':[],'responsibility_hypotheses':[{'hypothesis_id':'RESP:ACCEPT','expected_observations':_ACCEPT},{'hypothesis_id':'RESP:REJECT','expected_observations':{'QG13V2_POSITIVE':['NO']}}],'interface_checks':[{'check_id':'IFACE:NO_S3_LAUNDER','scope':'AUTHORITY','state':'PASS'}],'revision_mechanics':[{'mechanic_id':'REV:ACCEPT','kind':'ACCEPT_BOUNDED_THEOREM_EVIDENCE','read_coordinates':['EVIDENCE'],'write_coordinates':['BOUNDED_RESULT'],'cost':0.1},{'mechanic_id':'REV:REJECT','kind':'REJECT','read_coordinates':['EVIDENCE'],'write_coordinates':['TERMINAL'],'cost':0.1}],'computation_actions':[{'action_id':'COMPUTE:NONE','kind':'NONE','expected_decision_value':0.0,'cost':1.0}],'responsibility_bindings':{'RESP:ACCEPT':['REV:ACCEPT'],'RESP:REJECT':['REV:REJECT']},'selected_capabilities':{'REV:ACCEPT':'qg13v2.accept','REV:REJECT':'qg13v2.reject'}},
'ACCEPT_RECORDED':{'terminal':True,'terminal_name':'QG13V2_NATIVE_ACCEPT_RECORDED','active_hard_obligations':[]},'REJECT_RECORDED':{'terminal':True,'terminal_name':'QG13V2_NATIVE_REJECT_RECORDED','active_hard_obligations':[]}}}
