from __future__ import annotations

from enum import Enum


SCHEMA_ID = "ScientificNoveltyCertificate.v1"


class NoveltyFinalState(str, Enum):
    NOVELTY_SUPPORTED = "NOVELTY_SUPPORTED"
    NOVELTY_NARROWED = "NOVELTY_NARROWED"
    ALREADY_SOLVED = "ALREADY_SOLVED"
    CANNOT_CHECK = "CANNOT_CHECK"


class NoveltySearchRoute(str, Enum):
    EXACT_TERM = "EXACT_TERM"
    SYNONYM_FUNCTION_ONLY = "SYNONYM_FUNCTION_ONLY"
    PROBLEM_DECOMPOSITION = "PROBLEM_DECOMPOSITION"
    PARENT_DISCIPLINE_HISTORY = "PARENT_DISCIPLINE_HISTORY"
    BENCHMARK_IMPLEMENTATION = "BENCHMARK_IMPLEMENTATION"
    CITED_BY_RELATED = "CITED_BY_RELATED"
    HOSTILE_ALREADY_SOLVED = "HOSTILE_ALREADY_SOLVED"


REQUIRED_SEARCH_ROUTES = tuple(NoveltySearchRoute)


class SourceAccess(str, Enum):
    FULL_TEXT = "FULL_TEXT"
    ABSTRACT_ONLY = "ABSTRACT_ONLY"
    METADATA_ONLY = "METADATA_ONLY"
    INACCESSIBLE = "INACCESSIBLE"


class MechanismOverlap(str, Enum):
    IDENTICAL = "IDENTICAL"
    FUNCTIONAL_EQUIVALENT = "FUNCTIONAL_EQUIVALENT"
    PARTIAL = "PARTIAL"
    DISTINCT = "DISTINCT"
    UNRESOLVED = "UNRESOLVED"


class ExperimentStatus(str, Enum):
    PROPOSED = "PROPOSED"
    EXECUTED = "EXECUTED"
    UNAVAILABLE = "UNAVAILABLE"
