#!/usr/bin/env python3
"""Emit the N4 paired-uncertainty table from the committed publication analysis.

Reads ``PUBLICATION_PAIRED_ANALYSIS_V1.json`` (schema
``ORION.Q4.PublicationPairedAnalysis.v1``) and renders every paired comparison it
contains -- mean difference, 95 percent percentile bootstrap interval, pair count,
and win/tie/loss decomposition -- as a LaTeX table.

The table is a faithful transcription. This script performs no resampling, fits
nothing, and derives no new estimate: every printed value is read directly from a
field of the committed JSON. Comparisons whose interval contains zero are marked
so that they are not read as positive results.

Usage::

    python3 papers/orion-08-typed-state/scripts/emit_paired_uncertainty_table.py

Writes ``papers/orion-08-typed-state/manuscript/tables/N4-U1_paired_uncertainty.tex``.
"""

from __future__ import annotations

import json
from pathlib import Path

PAPER = Path(__file__).resolve().parents[1]
SOURCE = PAPER / "PUBLICATION_PAIRED_ANALYSIS_V1.json"
TARGET = PAPER / "manuscript" / "tables" / "N4-U1_paired_uncertainty.tex"

# Display order and human-readable labels. Keys are (study, *path-into-study).
ROWS: list[tuple[str, tuple[str, ...], str, str]] = [
    ("N4-A", ("typed_vs_known_graph_utility",), "typed VOI vs.\\ greedy known-graph", "utility"),
    ("N4-A", ("typed_vs_uniform_voi_utility",), "typed VOI vs.\\ uniform-prior VOI", "utility"),
    (
        "N4-B",
        ("REOPEN_WASTEFUL", "scoped_vs_never_mean_round_utility"),
        "scoped vs.\\ never reopen (wasteful)",
        "round utility",
    ),
    (
        "N4-B",
        ("REOPEN_WASTEFUL", "scoped_vs_unscoped_mean_round_utility"),
        "scoped vs.\\ unscoped reopen (wasteful)",
        "round utility",
    ),
    (
        "N4-B",
        ("STALE_MATTERS", "scoped_vs_never_mean_round_utility"),
        "scoped vs.\\ never reopen (stale)",
        "round utility",
    ),
    (
        "N4-B",
        ("STALE_MATTERS", "scoped_vs_unscoped_mean_round_utility"),
        "scoped vs.\\ unscoped reopen (stale)",
        "round utility",
    ),
    (
        "N4-C",
        ("orion_vs_random_verification_regret_reduction",),
        "interval-Pareto vs.\\ random verification",
        "regret reduction",
    ),
    ("N4-E", ("decision_voi_vs_infogain_utility",), "decision VOI vs.\\ information gain", "utility"),
    ("N4-E", ("decision_voi_vs_llm_proxy_utility",), "decision VOI vs.\\ LLM proxy", "utility"),
    (
        "N4-F3",
        ("mixed_typed_vs_naive_utility",),
        "typed transport vs.\\ naive carry-forward",
        "utility",
    ),
    (
        "N4-F3",
        ("mixed_typed_vs_rederive_utility",),
        "typed transport vs.\\ re-derivation (mixed)",
        "utility",
    ),
    (
        "N4-F3",
        ("unnecessary_typed_vs_rederive_utility",),
        "typed transport vs.\\ re-derivation (no remint needed)",
        "utility",
    ),
]


def _dig(payload: dict, study: str, path: tuple[str, ...]) -> dict:
    node = payload["studies"][study.replace("-", "_")]
    for key in path:
        node = node[key]
    return node


def _fmt(value: float) -> str:
    return f"{value:.3f}"


def main() -> int:
    payload = json.loads(SOURCE.read_text(encoding="utf-8"))

    lines: list[str] = []
    lines.append(
        "% Generated by papers/orion-08-typed-state/scripts/emit_paired_uncertainty_table.py"
    )
    lines.append(f"% Source: {SOURCE.name} (schema {payload['schema']}). Do not edit by hand.")
    lines.append("% Every value is transcribed from the source JSON. No new estimate is derived.")
    lines.append("\\begin{table}[t]")
    lines.append("  \\centering")
    lines.append(
        "  \\caption{Paired uncertainty for every synthetic comparison in the preserved publication "
        "analysis. Intervals are 95\\,\\% percentile bootstrap intervals over paired episode "
        "differences (5000 deterministic resamples, seeds recorded per row in the source "
        "artifact). Win/tie/loss is the paired decomposition over the same $n$ pairs. "
        "Intervals are per-comparison and are \\emph{not} adjusted for the twelve comparisons "
        "shown; any family-wise adjustment widens them, so rows already containing "
        "zero would continue to contain zero. Rows marked $\\dagger$ have an interval "
        "containing zero: the contrast is \\emph{undetermined} at this $n$ and is not a "
        "positive result. The row marked $\\ddagger$ is the prespecified remint-unnecessary "
        "regime, where the exact tie on all pairs is the passing outcome and a positive "
        "advantage would have invalidated the study; its interval is $[0,0]$ by construction "
        "and is not an undetermined contrast.}"
    )
    lines.append("  \\label{tab:paired-uncertainty}")
    lines.append("  \\footnotesize")
    # tabularx with an expanding, ragged-right label column: the comparison names are
    # long enough to overflow \textwidth in a plain tabular at 11pt/1in margins, and
    # overflow is invisible to text-level checks. The X column cannot clip.
    lines.append(
        "  \\begin{tabularx}{\\textwidth}{l>{\\raggedright\\arraybackslash}X r r r r}"
    )
    lines.append("    \\toprule")
    lines.append(
        "    Study & Comparison & Mean diff. & 95\\,\\% CI & $n$ & win/tie/loss \\\\"
    )
    lines.append("    \\midrule")

    crossing: list[str] = []
    exact_ties: list[str] = []
    public_study = {
        "N4-A": "Prior",
        "N4-B": "Reopening",
        "N4-C": "Verify",
        "N4-E": "Acquire",
        "N4-F3": "Transport",
    }
    for study, path, label, metric in ROWS:
        node = _dig(payload, study, path)
        low, high = node["bootstrap_95pct_ci"]
        mean = node["mean_difference"]
        n_pairs = int(node["n_pairs"])
        win = node["paired_win_fraction"]
        tie = node["paired_tie_fraction"]
        loss = node["paired_loss_fraction"]
        includes_zero = low <= 0.0 <= high
        # An exact tie on every pair is a degenerate interval, not an undetermined
        # contrast. N4-F3's remint-unnecessary regime is prespecified to tie, so it
        # is marked separately and must not be read as a failed comparison.
        exact_tie = includes_zero and low == 0.0 and high == 0.0 and tie == 1.0
        if exact_tie:
            marker = "$\\ddagger$"
            exact_ties.append(f"{study} {label}")
        elif includes_zero:
            marker = "$\\dagger$"
            crossing.append(f"{study} {label}")
        else:
            marker = ""
        lines.append(
            f"    {public_study[study]} & {label}{marker} & {_fmt(mean)} "
            f"& $[{_fmt(low)},\\ {_fmt(high)}]$ & {n_pairs} "
            f"& {win:.2f}/{tie:.2f}/{loss:.2f} \\\\"
        )

    lines.append("    \\bottomrule")
    lines.append("  \\end{tabularx}")
    lines.append("  \\par\\smallskip")
    lines.append(
        "  \\textit{Metric note:} Prior, acquisition and transport differences are in episode utility; "
        "reopening in mean round utility; verification in scalarized regret reduction. "
        "The provenance family is a frozen exact census (200 laundering / 200 honest chains), not a sampled "
        "paired comparison, and therefore has no interval; its counts are reported in the text."
    )
    lines.append("\\end{table}")

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"wrote {TARGET.relative_to(PAPER.parents[1])}")
    print(f"rows: {len(ROWS)}")
    print(f"undetermined (interval contains zero): {len(crossing)}")
    for item in crossing:
        print(f"  - {item}")
    print(f"prespecified exact ties: {len(exact_ties)}")
    for item in exact_ties:
        print(f"  - {item}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
