import json, collections
raw=json.load(open("zsf12_classes.json"))
mz=json.load(open("mzs13_classes.json"))
r2=json.load(open("rank2_C5x2.json"))
V={c:(c//25,(c//5)%5,c%5) for c in range(125)}
def fmt(seq):
    c=collections.Counter(seq); return " ".join("(%d%d%d)^%d"%(V[k][0],V[k][1],V[k][2],m) for k,m in sorted(c.items()))
for x in raw: x["pretty"]=fmt(x["seq"])
raw.sort(key=lambda x:(x["k"],-x["orbit"],x["seq"]))
for i,x in enumerate(raw): x["id"]=i
json.dump({"problem":"GL(3,5)-classes of zero-sum-free sequences of length 12 = d(C_5^3) over C_5^3 (inverse Davenport problem)",
 "n_classes":len(raw),"n_sequences":sum(x["orbit"] for x in raw),"n_normalized":sum(x["count"] for x in raw),
 "GL_order":1488000,"D_C5cubed":13,
 "fields":{"seq":"canonical form, 12 codes 25a+5b+c","count":"occurrences in the normalized enumeration = N(C)/|Stab(C)|",
   "orbit":"|GL|/|Stab| = sequences in this class","stab":"|Stab_GL(S)|","k":"support size","prof":"multiplicity profile",
   "maxmult":"max multiplicity in S","ext_maxmult":"max multiplicity in S*(-sigma(S)), the length-13 minimal zero-sum",
   "npp":"# distinct projective points of supp","maxline":"max supp points on a line of PG(2,5)","arc":"maxline<=2",
   "mb":"max multiplicity-sum over bases inside supp","n_basis444":"# bases with all three multiplicities 4",
   "sigma":"sigma(S) as a code"},
 "classes":raw},open("zsf12_classification.json","w"))

out=open("REPORT_ZSF.txt","w"); W=out.write
W("MAXIMAL ZERO-SUM-FREE SEQUENCES AND THE INVERSE DAVENPORT PROBLEM FOR C_5^3\n"+"="*76+"\n\n")
W("HEADLINE NUMBERS (D(C_5^3) = 13 by Olson, so d(C_5^3) = 12)\n")
W("  zero-sum-free sequences of length 12, up to GL(3,5) : 26,369 classes\n")
W("                                        total         : 39,147,296,000 sequences\n")
W("  minimal zero-sum sequences of length 13, up to GL   :  3,325 classes\n")
W("                                        total         :  4,897,256,000 sequences\n")
W("  (the second is the inverse Davenport problem proper for C_5^3)\n\n")
W("PRIOR ART CHECK (done first)\n"+"-"*76+"\n")
W("Rank 2 is classical: Property B (Gao-Geroldinger; proved for prime n by Reiher)\n")
W("plus the Bhowmik-Schlage-Puchta / Gao-Geroldinger description of maximal\n")
W("zero-sum-free sequences over C_n^2.  Rank 3 is NOT known: the searches\n")
W("surfaced complete inverse results only for special families (C_2^2 + C_2n,\n")
W("Schmid EJC 18 (2011) #P33; C_3 + C_3 + C_3d, Bhowmik-Schlage-Puchta 2007),\n")
W("and the literature explicitly motivates rank-2 structure by the fact that the\n")
W("rank-3 Davenport constant is unresolved in general.  No source gave a\n")
W("structural classification for C_p^3, and none gave a rank-3 analogue of\n")
W("Property B or a counterexample to one.  So this is new territory; nothing\n")
W("here is a rediscovery of a result I found in the literature.\n\n")
W("CORRECTION TO THE STATED ANCHOR.  The task gave the rank-2 form as\n")
W("  e^{p-1} * prod_{i=1}^{p-1}(a_i e + f)                            [shape A]\n")
W("That is INCOMPLETE.  The full statement needs a second shape\n")
W("  e^{p-2} * prod_{i=1}^{p}(a_i e + f)  with  sum a_i = 1           [shape B]\n")
W("My rank-2 computation confirms it: 4 of the 18 classes over C_5^2 have max\n")
W("multiplicity 3, so shape A (which requires multiplicity 4) cannot hold for\n")
W("them.  Shape B is exactly the case where the element of multiplicity p-1 in\n")
W("the associated minimal zero-sum sequence S*(-sigma(S)) is the completion\n")
W("-sigma(S) itself, so Property B is untouched.\n\n")
W("VALIDATION ANCHOR: C_5^2, length 8 = d(C_5^2)\n"+"-"*76+"\n")
W("Enumerated ALL 8400 zero-sum-free sequences of length 8 over C_5^2 with NO\n")
W("normalization, so the orbit-stabilizer identity is checked against ground\n")
W("truth rather than a slice:\n")
W("    18 GL(2,5)-classes;  sum of |GL(2,5)|/|Stab| = 8400 = enumerated total.\n")
W("    17 classes have |Stab|=1, one (e^4 f^4) has |Stab|=2.\n")
W("    ALL 18 fit shape A or shape B (14 fit A, 4 fit only B), tested by brute\n")
W("    force over all 480 ordered bases.  0 fit neither.\n")
W("The pipeline therefore reproduces the known rank-2 structure theorem before\n")
W("being pointed at the unknown rank-3 case.\n\n")
W("RANK 3 -- VALIDATION\n"+"-"*76+"\n")
W("  * Bit primitive: the u128 translation `shft` is OR-linear, so checking it on\n")
W("    all 125 singleton masks for all 125 translations is a COMPLETE proof, not\n")
W("    a sample.  Verified 125x125 = 15625/15625.\n")
W("  * Two independently structured enumerators (position-recursive vs\n")
W("    code-recursive, different pruning) both give 3,275,411 normalized\n")
W("    zero-sum-free sequences of length 12.\n")
W("  * COMPLETENESS on a slice: an independent Python brute force over the\n")
W("    |supp| <= 5 slice produced 7302 sequences; the C enumerator produced the\n")
W("    IDENTICAL SET (0 only-in-python, 0 only-in-C).\n")
W("  * Orbit-stabilizer: for EVERY one of the 26,369 classes, N(C)/|Stab(C)|\n")
W("    equals the observed multiplicity in the normalized enumeration exactly.\n")
W("    0 mismatches; |Stab| divides N in all 26,369 cases; total 3,275,411.\n")
W("  * Anti-collapse: inside one multiplicity profile, 129 sequences with\n")
W("    distinct subsequence-sum signatures (an independently computed\n")
W("    GL-invariant) gave 129 DISTINCT canonical forms.\n")
W("  * Canonicalizer regression: the optimized canon2 reproduces the already\n")
W("    validated canon byte-for-byte on all 98622 D_2 witnesses.\n")
W("  * Anchor: e1^4 e2^4 e3^4 appears as a class.\n")
W("  * CROSS-CLASSIFICATION IDENTITY.  Every minimal zero-sum sequence U of\n")
W("    length 13 equals S*(-sigma(S)) for S = U minus any one element, and the\n")
W("    S's producing a given U are exactly U\\{u} for u in supp(U).  Hence\n")
W("        #(zero-sum-free length 12) = sum over U of |supp(U)|.\n")
W("    Computed: 39,147,296,000 = 39,147,296,000.  EXACT.\n")
W("  * 120 random minimal-zero-sum reps brute-forced over all 2^13 subsets:\n")
W("    every one has exactly one zero-sum sub-multiset (itself).  0 failures.\n\n")
W("CLASS TABLES\n"+"-"*76+"\n")
def tab(rows,key,label,orb="orbit"):
    t=collections.defaultdict(lambda:[0,0])
    for x in rows:
        k=x[key] if not isinstance(x[key],list) else tuple(x[key])
        t[k][0]+=1; t[k][1]+=x[orb]
    W("\n%s:\n"%label)
    for k in sorted(t): W("   %-10s %8d classes %18d sequences\n"%(k,t[k][0],t[k][1]))
W("\n--- zero-sum-free, length 12 (26,369 classes) ---")
tab(raw,"k","support size |supp(S)|")
tab(raw,"maxmult","max multiplicity of S")
tab(raw,"maxline","max support points on one line of PG(2,5)")
tab(raw,"mb","max multiplicity-sum over bases inside supp(S)")
tab(raw,"stab","|Stab_GL(S)|")
W("\n--- minimal zero-sum, length 13 = D(C_5^3) (3,325 classes) ---")
tab(mz["classes"],"k","support size |supp(U)|")
tab(mz["classes"],"maxmult","max multiplicity of U")
tab(mz["classes"],"stab","|Stab_GL(U)|")
out.close()
print(open("REPORT_ZSF.txt").read()[:400]); print("...\nREPORT_ZSF.txt:",sum(1 for _ in open("REPORT_ZSF.txt")),"lines")
