#!/usr/bin/env python3
"""QG-26 — is the committed R6I syndrome state space the Nerode index, or just sufficient?

Protocol: development/orion-qg-regime-geometry/QG26_NERODE_MINIMALITY_PROTOCOL_V1.md
(frozen before this file was written). Authority ceiling NOT_R6. No chemistry read.
The protected stretched-N2 subject is never opened.

The committed DP declares STATES = 1024. QG-25's donor search named the quantity that
number is supposed to be: the index of the right-congruence, i.e. Myhill-Nerode. This
computes it, two ways that must agree, and says whether 1024 is tight.
"""

from __future__ import annotations

import hashlib
import itertools
import json
import sys
import time
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[3]
ORION_Q = REPO_ROOT / "research" / "extensions" / "orion-q"
HARNESS_SRC = REPO_ROOT / "packages" / "orion-research-harness" / "src"
sys.path.insert(0, str(ORION_Q))
sys.path.insert(0, str(HARNESS_SRC))

import max_r6i_exact_rank2_shared_tag_dp as r6i  # noqa: E402  (G1: imported unmodified)

from orion_research_harness.criterion_binding import (  # noqa: E402
    FAIL,
    PASS,
    criterion_digest,
    validate_criterion_binding,
)
from orion_research_harness.donor_search import validate_donor_search  # noqa: E402

PROTOCOL = (
    REPO_ROOT
    / "development"
    / "orion-qg-regime-geometry"
    / "QG26_NERODE_MINIMALITY_PROTOCOL_V1.md"
)
OUT = REPO_ROOT / "research" / "extensions" / "orion-qg" / "QG26_NERODE_MINIMALITY_RESULTS.json"

# The criterion this lane adjudicates, quoted from protocol section 4 rather than
# paraphrased, so the digest binds the frozen words.
FROZEN_CRITERION = (
    "QG26_SYNDROME_IS_NERODE_MINIMAL - 2^r = 1024, both methods agree. "
    "The committed number is tight."
)


def _base4_code(values: tuple[int, ...]) -> int:
    code = 0
    for value in values:
        code = code * 4 + int(value)
    return code


def alphabet() -> tuple[list[int], int]:
    """Every letter the committed DP can emit, read out of _DELTA (G1, G6)."""
    letters = set()
    rows = 0
    for values in itertools.product(range(4), repeat=6):
        rows += 1
        letters.add(int(r6i._DELTA[_base4_code(values)]))
    return sorted(letters), rows


def gf2_rank(values: list[int]) -> tuple[int, list[int]]:
    """Rank over F_2, returning the echelon basis so the result is checkable."""
    basis: list[int] = []
    for value in values:
        cur = value
        for b in basis:
            cur = min(cur, cur ^ b)
        if cur:
            basis.append(cur)
            basis.sort(reverse=True)
    return len(basis), sorted(basis)


def subgroup(basis: list[int]) -> list[int]:
    """The subgroup generated by the letters: every F_2 combination of the basis."""
    elements = {0}
    for b in basis:
        elements |= {e ^ b for e in elements}
    return sorted(elements)


def moore_minimize(states: list[int], letters: list[int], accepting: int) -> dict[str, Any]:
    """Partition refinement to a fixpoint on the reachable translation automaton.

    Deliberately generic: it does not know the automaton is abelian, so it cannot
    silently reproduce the structural answer it is supposed to corroborate.
    """
    index = {s: i for i, s in enumerate(states)}
    delta = [[index[s ^ a] for a in letters] for s in states]
    block = [1 if s == accepting else 0 for s in states]
    rounds = 0
    while True:
        rounds += 1
        signature = {}
        new_block = [0] * len(states)
        for i in range(len(states)):
            sig = (block[i], tuple(block[j] for j in delta[i]))
            if sig not in signature:
                signature[sig] = len(signature)
            new_block[i] = signature[sig]
        if new_block == block:
            return {"blocks": len(set(block)), "refinement_rounds": rounds}
        block = new_block


def main() -> int:
    started = time.time()
    letters, rows = alphabet()
    rank, basis = gf2_rank(letters)
    reachable = subgroup(basis)
    structural = 2 ** rank

    # G2: the mechanical method, run for two independent targets. 239 is the
    # final_parity_state that appears in the committed ORION-Q receipts; 0 is the
    # identity. If minimality depended on the target, these would disagree.
    mechanical = {}
    for target in (0, 239):
        if target in reachable:
            mechanical[str(target)] = moore_minimize(reachable, letters, target)
        else:
            mechanical[str(target)] = {"blocks": None, "note": "target not in the reachable subgroup"}

    counts = {v["blocks"] for v in mechanical.values() if v["blocks"] is not None}
    methods_agree = len(counts) == 1 and counts == {structural}

    if not methods_agree:
        terminal = "QG26_METHOD_DISAGREEMENT"
    elif structural == r6i.STATES:
        terminal = "QG26_SYNDROME_IS_NERODE_MINIMAL"
    else:
        terminal = "QG26_SYNDROME_IS_LOOSE__FACTOR_MEASURED"

    reported = PASS if terminal == "QG26_SYNDROME_IS_NERODE_MINIMAL" else FAIL
    criterion_record = {
        "criterion": "protocol section 4, QG26_SYNDROME_IS_NERODE_MINIMAL",
        "frozen_criterion_digest": criterion_digest(FROZEN_CRITERION),
        "applied_criterion_digest": criterion_digest(FROZEN_CRITERION),
        "reported_verdict": reported,
        "note": "no criterion was changed; the digests are equal and stated, not omitted",
    }
    # G5: exercised, not declared. Fails closed.
    validate_criterion_binding(criterion_record, FROZEN_CRITERION)

    # G4: no novelty is asserted, and that is checked by the committed validator
    # rather than taken on this file's word.
    donor_record = {
        "claim": "the Nerode index of the committed R6I feasibility language",
        "asserts_novelty": False,
        "inherits": "QG-25 record C1, INSTANCE_OF_KNOWN_GENERAL (Myhill-Nerode 1958)",
    }
    validate_donor_search(donor_record)

    result: dict[str, Any] = {
        "schema": "ORIONQG.QG26.NerodeMinimality.v1",
        "authority_ceiling": "NOT_R6",
        "novelty_authority": False,
        "physical_quantum_advantage_claim": False,
        "chemistry_sources_read": False,
        "protected_subject_read": False,
        "protocol_sha256": hashlib.sha256(PROTOCOL.read_bytes()).hexdigest(),
        "committed_state_count": int(r6i.STATES),
        "alphabet": {
            "option_rows_enumerated": rows,
            "expected_option_rows": 4 ** 6,
            "complete": rows == 4 ** 6,
            "distinct_letters": len(letters),
            "letters": letters,
        },
        "structural_method": {
            "gf2_rank_of_alphabet": rank,
            "echelon_basis": basis,
            "nerode_index": structural,
            "argument": (
                "the transition monoid is translation by F_2^10, so the reachable set "
                "from the zero state is exactly the subgroup generated by the letters, "
                "of order 2^r; and for s != s' in that subgroup the word summing to "
                "s XOR target distinguishes them, so no two are Nerode-equivalent"
            ),
        },
        "mechanical_method": mechanical,
        "methods_agree": methods_agree,
        "terminal": terminal,
        "looseness_factor": int(r6i.STATES) // structural if structural else None,
        "criterion_binding": [criterion_record],
        "donor_search": [donor_record],
        "g3_scope_statement": (
            "This is a statement about the FEASIBILITY language only. The committed DP "
            "is min-plus and carries cost; nothing here shows any algorithm is faster, "
            "and whether the cost DP admits the same reduction is not answered."
        ),
        "caps_disclosed": [
            "runtime cap < 10 minutes, single process, wall clock",
            "mechanical minimization run for targets 0 and 239 only, not all targets",
            "complete enumeration of all 4^6 option rows",
        ],
    }
    payload = json.dumps(result, sort_keys=True, separators=(",", ":"))
    result["result_digest"] = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    OUT.write_text(json.dumps(result, indent=1, sort_keys=True) + "\n")
    print(f"ORIONQG_QG26={json.dumps({k: result[k] for k in ('terminal','committed_state_count','methods_agree','looseness_factor','result_digest')}, sort_keys=True)}")
    print(f"structural={structural} rank={rank} mechanical={ {k: v['blocks'] for k, v in mechanical.items()} }", file=sys.stderr)
    print(f"elapsed={time.time() - started:.1f}s", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
