#!/usr/bin/env python3
"""Read-only, end-to-end reproducibility and presentation check."""

from __future__ import annotations

import argparse
import filecmp
import json
import os
import struct
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
VIS = ROOT / "visualization"


def run(*args: str) -> None:
    environment = os.environ.copy()
    environment["PYTHONPATH"] = str(VIS / "src") + os.pathsep + environment.get("PYTHONPATH", "")
    subprocess.run([sys.executable, *args], cwd=ROOT, env=environment, check=True)


def output_files(root: Path) -> list[Path]:
    groups = [root / "data", root / "figures", root / "notebooks", root / "generated/manifests"]
    return sorted(path for group in groups for path in group.rglob("*") if path.is_file())


def compare(committed: Path, rebuilt: Path) -> None:
    current = {path.relative_to(committed).as_posix(): path for path in output_files(committed)}
    fresh = {path.relative_to(rebuilt).as_posix(): path for path in output_files(rebuilt)}
    if set(current) != set(fresh):
        missing = sorted(set(fresh) - set(current))
        extra = sorted(set(current) - set(fresh))
        raise RuntimeError(f"generated file set differs: missing={missing}, extra={extra}")
    drift = [
        name
        for name in sorted(current)
        if not filecmp.cmp(current[name], fresh[name], shallow=False)
    ]
    if drift:
        raise RuntimeError(f"generated byte drift: {drift}")


def inspect_png(path: Path) -> None:
    data = path.read_bytes()
    if len(data) < 1000 or data[:8] != b"\x89PNG\r\n\x1a\n":
        raise RuntimeError(f"invalid/blank-looking PNG: {path}")
    width, height = struct.unpack(">II", data[16:24])
    if width < 400 or height < 250:
        raise RuntimeError(f"PNG too small for inspection: {path} ({width}x{height})")


def inspect_svg(path: Path) -> None:
    tree = ET.parse(path)
    root = tree.getroot()
    text_nodes = [node for node in root.iter() if node.tag.endswith("text")]
    if len(text_nodes) < 2 or path.stat().st_size < 1000:
        raise RuntimeError(f"SVG lacks editable text/content: {path}")


def inspect_html(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    lowered = text.lower()
    if (
        "http://" in lowered
        or "https://" in lowered
        or "<script src=" in lowered
        or "<link rel=" in lowered
    ):
        raise RuntimeError("interactive HTML is not self-contained")
    for required in ("atlas-data", "paper", "metric", "anomalies"):
        if required not in text:
            raise RuntimeError(f"interactive HTML missing {required}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--keep-temp", action="store_true")
    args = parser.parse_args()
    run(str(VIS / "scripts/validate_sources.py"))
    temporary = tempfile.TemporaryDirectory(prefix="orion-visualization-check-")
    try:
        rebuilt = Path(temporary.name) / "visualization"
        run(str(VIS / "scripts/build_all.py"), "--output-root", str(rebuilt))
        run(str(VIS / "scripts/execute_notebooks.py"), "--visualization-root", str(rebuilt))
        compare(VIS, rebuilt)
        for path in sorted((rebuilt / "figures/static/png").glob("*.png")):
            inspect_png(path)
        for path in sorted((rebuilt / "figures/static/svg").glob("*.svg")):
            inspect_svg(path)
        inspect_html(rebuilt / "figures/interactive/evidence_atlas.html")
        atlas = json.loads((rebuilt / "data/derived/atlas.json").read_text(encoding="utf-8"))
        if len(atlas["paper_states"]) != 15 or len(atlas["anomalies"]) != 14:
            raise RuntimeError("adverse/status counts changed")
        print("CHECKED deterministic data, figures, HTML, notebooks, and manifests")
        print("SCIENTIFIC_AUTHORITY=UNCHANGED_BY_VISUALIZATION_CHECKS")
        return 0
    finally:
        if args.keep_temp:
            print(f"TEMP={temporary.name}")
            temporary.cleanup = lambda: None  # type: ignore[method-assign]
        else:
            temporary.cleanup()


if __name__ == "__main__":
    raise SystemExit(main())
