"""Generate FAILURE_LEDGER.md from execution receipts.

Generated, not hand-written, for one reason: a hand-written adverse record
drifts the moment a job is re-run, and it drifts in the flattering
direction. Nobody forgets to add a win.

Classification is by TERMINAL, read from the receipt. A terminal naming a
refutation, narrowing or inability is adverse; a terminal that cannot be
classified is reported as UNCLASSIFIED rather than silently assumed
positive.
"""
from __future__ import annotations

import glob
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXEC = ROOT / "research/orion-foundations-v3/exec"

# "FAIL" rather than "FAILED": the first version of this list used the past
# tense and silently missed P12_ALLOCATOR_TRANSFER_OR_ROBUSTNESS_FAILS, which
# landed in UNCLASSIFIED. That is the bucket working as intended -- an
# unmatched terminal must surface, never default to positive.
ADVERSE = ("REFUTED", "NARROWED", "INCOMPLETE", "NOT_OBSERVED", "INVALID",
           "ABSENT", "UNAVAILABLE", "CANNOT", "MISALIGNED", "FAIL")
BLOCKED = ("ABSENT", "UNAVAILABLE", "CANNOT", "INVALID")


def classify(terminal: str) -> str:
    t = terminal.upper()
    if any(k in t for k in BLOCKED):
        return "BLOCKED"
    if any(k in t for k in ADVERSE):
        return "ADVERSE"
    if "SUPPORTED" in t or "VERIFIED" in t or "COMPLETE" in t or "GREEN" in t:
        return "POSITIVE"
    return "UNCLASSIFIED"


def main() -> int:
    rows = []
    for f in sorted(glob.glob(str(EXEC / "*/RESULT_RECEIPT.json"))):
        d = json.loads(Path(f).read_text())
        rows.append(d)

    pos = [r for r in rows if classify(r["terminal"]) == "POSITIVE"]
    adv = [r for r in rows if classify(r["terminal"]) == "ADVERSE"]
    blk = [r for r in rows if classify(r["terminal"]) == "BLOCKED"]
    unk = [r for r in rows if classify(r["terminal"]) == "UNCLASSIFIED"]

    L = ["# Failure ledger", "",
         "Generated by `scripts/build_failure_ledger.py` from execution receipts.",
         "Do not edit by hand: a hand-maintained adverse record drifts, and it",
         "drifts in the flattering direction. Nobody forgets to add a win.", "",
         f"**{len(rows)} executed jobs**: {len(pos)} positive, {len(adv)} adverse, "
         f"{len(blk)} blocked, {len(unk)} unclassified.", ""]

    if unk:
        L += ["> **Unclassified terminals present.** These are reported rather than",
              "> assumed positive, because a classifier that defaults unknown to good",
              "> is not a classifier.", ""]
        for r in unk:
            L.append(f"> - `{r['job_id']}` — `{r['terminal']}`")
        L.append("")

    L += ["## Adverse and narrowing outcomes", ""]
    if not adv:
        L.append("_None._")
    for r in adv:
        L += [f"### {r['job_id']} — `{r['terminal']}`", ""]
        if r.get("terminal_reading"):
            L += [r["terminal_reading"], ""]
        if r.get("narrowed_statement"):
            L += ["**Narrowed statement.** " + str(r["narrowed_statement"]), ""]
    L.append("")

    L += ["## Blocked: no external party available", "",
          "These are not failures of the work. They are jobs whose specification",
          "requires someone outside the programme, which no amount of internal",
          "rigour supplies.", ""]
    for r in blk:
        L.append(f"- **{r['job_id']}** — `{r['terminal']}`")
        if r.get("what_would_discharge_this_job"):
            L.append(f"  - Discharged by: {r['what_would_discharge_this_job']}")
    L.append("")

    L += ["## Stated limits of every job", "",
          "Every receipt carries an explicit `what_this_does_not_establish`. They",
          "are collected here so a reader can see the boundary of the whole",
          "programme in one place rather than reconstructing it per job.", ""]
    for r in rows:
        lims = r.get("what_this_does_not_establish") or []
        if not lims:
            continue
        L.append(f"**{r['job_id']}**")
        for x in lims:
            L.append(f"- {x}")
        L.append("")

    L += ["## External validation status", "",
          "| Job | External validation | Authority delta |", "|---|---|---|"]
    for r in rows:
        L.append(f"| `{r['job_id']}` | {r.get('external_validation','?')} | "
                 f"{r.get('paper_authority_delta','?')} |")
    L += ["", "Every row reads CANNOT_CHECK for external validation. That is the",
          "honest state: two implementations inside one programme are not",
          "independent adjudication, and this ledger does not pretend otherwise.", ""]

    out = ROOT / "FAILURE_LEDGER.md"
    out.write_text("\n".join(L) + "\n")
    print(f"jobs={len(rows)} positive={len(pos)} adverse={len(adv)} "
          f"blocked={len(blk)} unclassified={len(unk)}")
    print(f"wrote {out} ({out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
