"""Freeze, load and verify the ORION-P2 offline complete-gold suite.

The suite is frozen *before* any system is configured against it. That ordering
is the only thing that makes the world an honest measuring instrument: once a
candidate has been tuned against a corpus, the corpus is no longer independent of
the candidate, and no hash committed afterwards can undo that.

Regeneration from `FROZEN_SEED` on a clean checkout must reproduce the committed
`suite_fingerprint` exactly. `verify` is what says so, and it is what the tests
call — including across a process boundary, since a suite that only reproduces
inside one interpreter is not reproducible at all.

Run `python3 -m orion.study.p2.freeze --write` to regenerate the artifact, or
with no arguments to verify the committed one.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .cases import (
    TASK_SCHEMA_VERSION,
    DiscoveryTask,
    build_probe_map,
    build_tasks,
    suite_fingerprint,
    task_from_json,
)
from .corpus import (
    CORPUS_SCHEMA_VERSION,
    DiscoveryWorld,
    build_world,
    canonical_bytes,
    sha256_digest,
    world_from_json,
)

#: The seed the committed artifact was generated from. Changing it mints a new
#: world, which is a new suite, which needs a new fingerprint and a protocol note
#: — never a silent edit.
FROZEN_SEED = 20260816

MANIFEST_SCHEMA_VERSION = "orion.p2.offline-gold-manifest.v1"

#: Provenance, stated rather than assumed. Every document is generated by
#: `corpus.py` in this repository from `FROZEN_SEED`; no third-party text,
#: metadata or identifier is copied in, and the author names, venues and
#: abstracts are synthetic strings assembled by the generator. The corpus
#: therefore carries no third-party licence encumbrance and is redistributable on
#: the same terms as the repository itself. This deliberately claims no licence
#: the repository does not have: at the time of freezing there is no LICENSE file
#: at the repository root, and inventing one here would be worse than saying so.
PROVENANCE = (
    "Fully synthetic. Generated by src/orion/study/p2/corpus.py from the recorded "
    "seed; contains no third-party text, metadata or identifiers, and so carries "
    "no third-party licence encumbrance. Redistributable on the repository's own "
    "terms; no separate licence is asserted here."
)

DEFAULT_ROOT = (
    Path(__file__).resolve().parents[4]
    / "papers"
    / "paper-02-open-world-scientific-discovery"
    / "evidence"
    / "offline_gold"
)

MANIFEST_FILE = "MANIFEST.json"

#: Committed shards. The world and task set are both larger than one comfortable
#: file at N=390, so each is split. Shard membership is a hash of the record's own
#: id rather than its position in the list, so adding or removing a topic moves
#: only the affected records instead of reshuffling every boundary.
SHARD_COUNT = 4
WORLD_SHARD = "world-{index:02d}.json"
TASKS_SHARD = "tasks-{index:02d}.json"


def _shard_of(identifier: str) -> int:
    return int(hashlib.sha256(identifier.encode("utf-8")).hexdigest()[:8], 16) % SHARD_COUNT

#: Keep every committed shard comfortably below the repository's file-size
#: comfort zone. Checked at write time rather than assumed.
MAX_FILE_BYTES = 1_000_000


#: `precision_plan.precision_tiers` from STATISTICAL_PLAN_V1.json, as
#: (required_n, tier, half_width). The plan commits `offline_complete_gold` to
#: TIER_B and requires the *achieved* tier be recorded, so the suite computes it
#: from its own N rather than asserting the committed one.
PRECISION_TIERS: tuple[tuple[int, str, float], ...] = (
    (1068, "TIER_A_full", 0.03),
    (385, "TIER_B_committed", 0.05),
    (171, "TIER_C_reduced", 0.075),
    (97, "TIER_D_minimum_inferential", 0.1),
)


def achieved_tier(task_count: int) -> dict[str, Any]:
    """The precision tier this suite's N actually reaches.

    Below TIER_D the family is `DESCRIPTIVE_ONLY` and cannot carry a promoted
    primary claim, which is a fact about the suite the run manifest has to carry.
    """

    for required, tier, half_width in PRECISION_TIERS:
        if task_count >= required:
            return {
                "tier": tier,
                "half_width": half_width,
                "required_n": required,
                "achieved_n": task_count,
                "descriptive_only": False,
            }
    return {
        "tier": "DESCRIPTIVE_ONLY",
        "half_width": None,
        "required_n": 97,
        "achieved_n": task_count,
        "descriptive_only": True,
    }


@dataclass(frozen=True)
class FrozenSuite:
    world: DiscoveryWorld
    tasks: tuple[DiscoveryTask, ...]

    @property
    def fingerprint(self) -> str:
        return suite_fingerprint(self.world, self.tasks)


def build_suite(seed: int = FROZEN_SEED) -> FrozenSuite:
    world = build_world(seed)
    return FrozenSuite(world=world, tasks=build_tasks(world))


def _dump(payload: Any) -> str:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False) + "\n"


def write_suite(root: Path = DEFAULT_ROOT, *, seed: int = FROZEN_SEED) -> dict[str, Any]:
    """Write the frozen suite and its manifest. Returns the manifest."""

    suite = build_suite(seed)
    root.mkdir(parents=True, exist_ok=True)
    for stale in sorted(root.glob("*.json")):
        stale.unlink()

    files: dict[str, Any] = {}
    for index in range(SHARD_COUNT):
        documents = [
            item.as_json()
            for item in suite.world.documents
            if _shard_of(item.doc_id) == index
        ]
        files[WORLD_SHARD.format(index=index)] = {
            "schema_version": CORPUS_SCHEMA_VERSION,
            "seed": seed,
            "shard": index,
            "shard_count": SHARD_COUNT,
            "documents": documents,
            "topics": [item.as_json() for item in suite.world.topics] if index == 0 else [],
        }
        files[TASKS_SHARD.format(index=index)] = {
            "schema_version": TASK_SCHEMA_VERSION,
            "shard": index,
            "shard_count": SHARD_COUNT,
            "tasks": [
                item.as_json() for item in suite.tasks if _shard_of(item.task_id) == index
            ],
        }

    for name, payload in sorted(files.items()):
        text = _dump(payload)
        size = len(text.encode("utf-8"))
        if size > MAX_FILE_BYTES:
            raise ValueError(
                f"{name} is {size} bytes, above the {MAX_FILE_BYTES}-byte shard ceiling; "
                "raise SHARD_COUNT before committing"
            )
        (root / name).write_text(text, encoding="utf-8")

    manifest = {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "corpus_schema_version": CORPUS_SCHEMA_VERSION,
        "task_schema_version": TASK_SCHEMA_VERSION,
        "seed": seed,
        "suite_fingerprint": suite.fingerprint,
        "world_content_hash": suite.world.content_hash,
        "document_count": len(suite.world.documents),
        "topic_count": len(suite.world.topics),
        "task_count": len(suite.tasks),
        "shard_count": SHARD_COUNT,
        "achieved_precision_tier": achieved_tier(len(suite.tasks)),
        "files": {
            name: {
                "sha256": sha256_digest(payload),
                "bytes": len(_dump(payload).encode("utf-8")),
            }
            for name, payload in sorted(files.items())
        },
        "provenance": PROVENANCE,
        "regenerate": "python3 -m orion.study.p2.freeze --write",
        "frozen_before_any_system_configured": True,
    }
    (root / MANIFEST_FILE).write_text(_dump(manifest), encoding="utf-8")
    return manifest


def load_suite(root: Path = DEFAULT_ROOT) -> FrozenSuite:
    """Load the committed suite from its shards without regenerating it."""

    documents: list[dict[str, Any]] = []
    topics: list[dict[str, Any]] = []
    seed = FROZEN_SEED
    schema = CORPUS_SCHEMA_VERSION
    for index in range(SHARD_COUNT):
        payload = json.loads(
            (root / WORLD_SHARD.format(index=index)).read_text(encoding="utf-8")
        )
        documents.extend(payload["documents"])
        topics.extend(payload["topics"])
        seed = int(payload["seed"])
        schema = payload["schema_version"]
    world = world_from_json(
        {"schema_version": schema, "seed": seed, "documents": documents, "topics": topics}
    )

    probe_map = build_probe_map(world)
    tasks: list[DiscoveryTask] = []
    for index in range(SHARD_COUNT):
        payload = json.loads(
            (root / TASKS_SHARD.format(index=index)).read_text(encoding="utf-8")
        )
        tasks.extend(task_from_json(item, probe_map) for item in payload["tasks"])
    return FrozenSuite(
        world=world, tasks=tuple(sorted(tasks, key=lambda item: item.task_id))
    )


def load_manifest(root: Path = DEFAULT_ROOT) -> dict[str, Any]:
    return json.loads((root / MANIFEST_FILE).read_text(encoding="utf-8"))


@dataclass(frozen=True)
class VerificationReport:
    ok: bool
    problems: tuple[str, ...]
    regenerated_fingerprint: str
    committed_fingerprint: str
    loaded_fingerprint: str


def verify(root: Path = DEFAULT_ROOT) -> VerificationReport:
    """Check that seed, committed bytes and manifest all agree.

    Three fingerprints have to match, not two. Regeneration proves the seed still
    produces this world; loading proves the committed bytes round-trip to the same
    objects; the manifest proves the recorded identity is the one on disk. Drop
    any one and a suite can be edited without the hash noticing.
    """

    problems: list[str] = []
    regenerated = build_suite(FROZEN_SEED)
    regenerated_fingerprint = regenerated.fingerprint

    manifest = load_manifest(root)
    committed_fingerprint = str(manifest.get("suite_fingerprint", ""))
    loaded = load_suite(root)
    loaded_fingerprint = loaded.fingerprint

    if manifest.get("seed") != FROZEN_SEED:
        problems.append(f"manifest seed {manifest.get('seed')!r} != FROZEN_SEED {FROZEN_SEED}")
    if regenerated_fingerprint != committed_fingerprint:
        problems.append("regenerated suite fingerprint does not match the manifest")
    if loaded_fingerprint != committed_fingerprint:
        problems.append("committed suite files do not match the manifest fingerprint")
    if regenerated.world.content_hash != str(manifest.get("world_content_hash", "")):
        problems.append("regenerated world content hash does not match the manifest")

    for name, expected in sorted(manifest.get("files", {}).items()):
        path = root / name
        if not path.is_file():
            problems.append(f"missing frozen file: {name}")
            continue
        payload = json.loads(path.read_text(encoding="utf-8"))
        if sha256_digest(payload) != expected.get("sha256"):
            problems.append(f"{name} content hash does not match the manifest")

    return VerificationReport(
        ok=not problems,
        problems=tuple(problems),
        regenerated_fingerprint=regenerated_fingerprint,
        committed_fingerprint=committed_fingerprint,
        loaded_fingerprint=loaded_fingerprint,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate the frozen suite")
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    parser.add_argument(
        "--print-fingerprint",
        action="store_true",
        help="print only the regenerated suite fingerprint and exit",
    )
    args = parser.parse_args(argv)

    if args.print_fingerprint:
        sys.stdout.write(build_suite(FROZEN_SEED).fingerprint + "\n")
        return 0
    if args.write:
        manifest = write_suite(args.root)
        sys.stdout.write(canonical_bytes(manifest).decode("utf-8") + "\n")
        return 0

    report = verify(args.root)
    for problem in report.problems:
        sys.stderr.write(f"FROZEN SUITE PROBLEM: {problem}\n")
    sys.stdout.write(f"suite_fingerprint={report.regenerated_fingerprint}\n")
    return 0 if report.ok else 1


__all__ = [
    "DEFAULT_ROOT",
    "FROZEN_SEED",
    "FrozenSuite",
    "MANIFEST_SCHEMA_VERSION",
    "PROVENANCE",
    "VerificationReport",
    "build_suite",
    "load_manifest",
    "load_suite",
    "main",
    "verify",
    "write_suite",
]


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    raise SystemExit(main())
