"""Freeze, load and verify the ORION-P2 offline complete-gold suite.

The suite is frozen *before* any system is configured against it. That ordering
is the only thing that makes the world an honest measuring instrument: once a
candidate has been tuned against a corpus, the corpus is no longer independent of
the candidate, and no hash committed afterwards can undo that.

Regeneration from `FROZEN_SEED` on a clean checkout must reproduce the committed
`suite_fingerprint` exactly. `verify` is what says so, and it is what the tests
call — including across a process boundary, since a suite that only reproduces
inside one interpreter is not reproducible at all.

Run `python3 -m orion.study.p2.freeze --write` to regenerate the artifact, or
with no arguments to verify the committed one.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .cases import (
    TASK_SCHEMA_VERSION,
    DiscoveryTask,
    build_tasks,
    suite_fingerprint,
    task_from_json,
)
from .corpus import (
    CORPUS_SCHEMA_VERSION,
    DiscoveryWorld,
    build_world,
    canonical_bytes,
    sha256_digest,
    world_from_json,
)

#: The seed the committed artifact was generated from. Changing it mints a new
#: world, which is a new suite, which needs a new fingerprint and a protocol note
#: — never a silent edit.
FROZEN_SEED = 20260816

MANIFEST_SCHEMA_VERSION = "orion.p2.offline-gold-manifest.v1"

#: Provenance, stated rather than assumed. Every document is generated by
#: `corpus.py` in this repository from `FROZEN_SEED`; no third-party text,
#: metadata or identifier is copied in, and the author names, venues and
#: abstracts are synthetic strings assembled by the generator. The corpus
#: therefore carries no third-party licence encumbrance and is redistributable on
#: the same terms as the repository itself. This deliberately claims no licence
#: the repository does not have: at the time of freezing there is no LICENSE file
#: at the repository root, and inventing one here would be worse than saying so.
PROVENANCE = (
    "Fully synthetic. Generated by src/orion/study/p2/corpus.py from the recorded "
    "seed; contains no third-party text, metadata or identifiers, and so carries "
    "no third-party licence encumbrance. Redistributable on the repository's own "
    "terms; no separate licence is asserted here."
)

DEFAULT_ROOT = (
    Path(__file__).resolve().parents[4]
    / "papers"
    / "paper-02-open-world-scientific-discovery"
    / "evidence"
    / "offline_gold"
)

WORLD_FILE = "world.json"
TASKS_FILE = "tasks.json"
MANIFEST_FILE = "MANIFEST.json"

#: Keep every committed shard comfortably below the repository's file-size
#: comfort zone. Checked at write time rather than assumed.
MAX_FILE_BYTES = 1_000_000


@dataclass(frozen=True)
class FrozenSuite:
    world: DiscoveryWorld
    tasks: tuple[DiscoveryTask, ...]

    @property
    def fingerprint(self) -> str:
        return suite_fingerprint(self.world, self.tasks)


def build_suite(seed: int = FROZEN_SEED) -> FrozenSuite:
    world = build_world(seed)
    return FrozenSuite(world=world, tasks=build_tasks(world))


def _dump(payload: Any) -> str:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False) + "\n"


def write_suite(root: Path = DEFAULT_ROOT, *, seed: int = FROZEN_SEED) -> dict[str, Any]:
    """Write the frozen suite and its manifest. Returns the manifest."""

    suite = build_suite(seed)
    root.mkdir(parents=True, exist_ok=True)

    world_payload = suite.world.as_json()
    tasks_payload = {
        "schema_version": TASK_SCHEMA_VERSION,
        "tasks": [task.as_json() for task in suite.tasks],
    }

    files = {WORLD_FILE: world_payload, TASKS_FILE: tasks_payload}
    for name, payload in files.items():
        text = _dump(payload)
        size = len(text.encode("utf-8"))
        if size > MAX_FILE_BYTES:
            raise ValueError(
                f"{name} is {size} bytes, above the {MAX_FILE_BYTES}-byte shard ceiling; "
                "reduce filler_documents or shard the corpus before committing"
            )
        (root / name).write_text(text, encoding="utf-8")

    manifest = {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "corpus_schema_version": CORPUS_SCHEMA_VERSION,
        "task_schema_version": TASK_SCHEMA_VERSION,
        "seed": seed,
        "suite_fingerprint": suite.fingerprint,
        "world_content_hash": suite.world.content_hash,
        "document_count": len(suite.world.documents),
        "topic_count": len(suite.world.topics),
        "task_count": len(suite.tasks),
        "files": {
            name: {
                "sha256": sha256_digest(payload),
                "bytes": len(_dump(payload).encode("utf-8")),
            }
            for name, payload in sorted(files.items())
        },
        "provenance": PROVENANCE,
        "regenerate": "python3 -m orion.study.p2.freeze --write",
        "frozen_before_any_system_configured": True,
    }
    (root / MANIFEST_FILE).write_text(_dump(manifest), encoding="utf-8")
    return manifest


def load_suite(root: Path = DEFAULT_ROOT) -> FrozenSuite:
    """Load the committed suite from disk without regenerating it."""

    world = world_from_json(json.loads((root / WORLD_FILE).read_text(encoding="utf-8")))
    payload = json.loads((root / TASKS_FILE).read_text(encoding="utf-8"))
    tasks = tuple(
        sorted((task_from_json(item) for item in payload["tasks"]), key=lambda item: item.task_id)
    )
    return FrozenSuite(world=world, tasks=tasks)


def load_manifest(root: Path = DEFAULT_ROOT) -> dict[str, Any]:
    return json.loads((root / MANIFEST_FILE).read_text(encoding="utf-8"))


@dataclass(frozen=True)
class VerificationReport:
    ok: bool
    problems: tuple[str, ...]
    regenerated_fingerprint: str
    committed_fingerprint: str
    loaded_fingerprint: str


def verify(root: Path = DEFAULT_ROOT) -> VerificationReport:
    """Check that seed, committed bytes and manifest all agree.

    Three fingerprints have to match, not two. Regeneration proves the seed still
    produces this world; loading proves the committed bytes round-trip to the same
    objects; the manifest proves the recorded identity is the one on disk. Drop
    any one and a suite can be edited without the hash noticing.
    """

    problems: list[str] = []
    regenerated = build_suite(FROZEN_SEED)
    regenerated_fingerprint = regenerated.fingerprint

    manifest = load_manifest(root)
    committed_fingerprint = str(manifest.get("suite_fingerprint", ""))
    loaded = load_suite(root)
    loaded_fingerprint = loaded.fingerprint

    if manifest.get("seed") != FROZEN_SEED:
        problems.append(f"manifest seed {manifest.get('seed')!r} != FROZEN_SEED {FROZEN_SEED}")
    if regenerated_fingerprint != committed_fingerprint:
        problems.append("regenerated suite fingerprint does not match the manifest")
    if loaded_fingerprint != committed_fingerprint:
        problems.append("committed suite files do not match the manifest fingerprint")
    if regenerated.world.content_hash != str(manifest.get("world_content_hash", "")):
        problems.append("regenerated world content hash does not match the manifest")

    for name, expected in sorted(manifest.get("files", {}).items()):
        path = root / name
        if not path.is_file():
            problems.append(f"missing frozen file: {name}")
            continue
        payload = json.loads(path.read_text(encoding="utf-8"))
        if sha256_digest(payload) != expected.get("sha256"):
            problems.append(f"{name} content hash does not match the manifest")

    return VerificationReport(
        ok=not problems,
        problems=tuple(problems),
        regenerated_fingerprint=regenerated_fingerprint,
        committed_fingerprint=committed_fingerprint,
        loaded_fingerprint=loaded_fingerprint,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate the frozen suite")
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    parser.add_argument(
        "--print-fingerprint",
        action="store_true",
        help="print only the regenerated suite fingerprint and exit",
    )
    args = parser.parse_args(argv)

    if args.print_fingerprint:
        sys.stdout.write(build_suite(FROZEN_SEED).fingerprint + "\n")
        return 0
    if args.write:
        manifest = write_suite(args.root)
        sys.stdout.write(canonical_bytes(manifest).decode("utf-8") + "\n")
        return 0

    report = verify(args.root)
    for problem in report.problems:
        sys.stderr.write(f"FROZEN SUITE PROBLEM: {problem}\n")
    sys.stdout.write(f"suite_fingerprint={report.regenerated_fingerprint}\n")
    return 0 if report.ok else 1


__all__ = [
    "DEFAULT_ROOT",
    "FROZEN_SEED",
    "FrozenSuite",
    "MANIFEST_SCHEMA_VERSION",
    "PROVENANCE",
    "VerificationReport",
    "build_suite",
    "load_manifest",
    "load_suite",
    "main",
    "verify",
    "write_suite",
]


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    raise SystemExit(main())
