#!/usr/bin/env python3
"""Derive the manuscript's scale facts from the artifacts instead of retyping them.

Every count that describes the frozen suite — tasks, documents, topics, systems,
repeats, run records, the achieved precision tier — currently appears as a literal
in several places: prose in three manuscript files, a run manifest, an analysis
guard, and snapshot tests. Changing the suite therefore silently falsifies files
nobody is looking at, and the last scale change made six of them wrong at once.

This is the root-cause fix rather than another round of hand-editing: the facts
are read from `evidence/offline_gold/MANIFEST.json` and
`evidence/offline_results/RESULTS_SUMMARY_V1.json`, emitted as LaTeX macros, and
the manuscript uses the macros. A stale number then becomes a failing test rather
than a sentence a reviewer catches.

A JSON sidecar is emitted next to the macros because derived quantities such as
the achieved half-width exist nowhere else in machine-readable form. The claim
ledger binds manuscript numbers to JSON artifacts, so without the sidecar the
half-width sentence can only be checked by hand.

``--check`` re-renders and exits non-zero if either committed file disagrees,
which is what CI and the test suite use.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

PAPER = Path(__file__).resolve().parent.parent
MANIFEST = PAPER / "evidence" / "offline_gold" / "MANIFEST.json"
RESULTS = PAPER / "evidence" / "offline_results" / "RESULTS_SUMMARY_V1.json"
OUTPUT = PAPER / "manuscript" / "generated" / "suite_facts.tex"
OUTPUT_JSON = PAPER / "manuscript" / "generated" / "suite_facts.json"

#: From STATISTICAL_PLAN_V1.json. Tier bounds are half-widths for a standalone
#: proportion at the plan's conservative p=0.5.
TIERS = (
    ("TIER_A_full", 0.03),
    ("TIER_B_committed", 0.05),
    ("TIER_C_reduced", 0.075),
    ("TIER_D_minimum_inferential", 0.10),
)
Z_95 = 1.959963984540054
DELTA_SUP = 0.03


def _fmt_int(value: int) -> str:
    """Thousands separators, so 16380 reads as a count rather than a serial."""

    return f"{value:,}".replace(",", "{,}")


def achieved_tier(n: int) -> tuple[str, float]:
    half_width = (Z_95 * 0.5 / (n ** 0.5)) if n else float("inf")
    tier = "BELOW_TIER_D"
    for name, bound in TIERS:
        if half_width <= bound:
            tier = name
            break
    return tier, half_width


def collect() -> dict[str, Any]:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    facts: dict[str, Any] = {
        "OfflineTaskCount": int(manifest["task_count"]),
        "OfflineDocumentCount": int(manifest["document_count"]),
        "OfflineTopicCount": int(manifest["topic_count"]),
        "OfflineSuiteFingerprintShort": str(manifest["suite_fingerprint"])[:12],
        "OfflineSuiteSeed": int(manifest["seed"]),
    }
    if RESULTS.is_file():
        results = json.loads(RESULTS.read_text(encoding="utf-8"))
        frozen = results.get("frozen_run", {})
        facts.update(
            {
                "OfflineSystemCount": int(frozen.get("n_systems", 0)),
                "OfflineRepeatCount": int(frozen.get("n_repeats", 0)),
                "OfflineRunRecordCount": int(frozen.get("n_result_records", 0)),
                "OfflineAnalysisAuthority": str(results.get("analysis_authority", "UNKNOWN")),
            }
        )
    tier, half_width = achieved_tier(facts["OfflineTaskCount"])
    facts["OfflineAchievedTier"] = tier
    facts["OfflineAchievedHalfWidth"] = f"{half_width:.4f}"
    facts["OfflineUnderpowered"] = "yes" if half_width > DELTA_SUP else "no"
    return facts


def render_json(facts: dict[str, Any]) -> str:
    """The same facts as a machine-readable sidecar for the claim ledger.

    The half-width lives in ``facts`` as its rendered string; the sidecar stores
    it as the number at that same written precision, so the ledger's numeric
    binding compares like with like.
    """

    payload: dict[str, Any] = dict(facts)
    payload["OfflineAchievedHalfWidth"] = round(float(facts["OfflineAchievedHalfWidth"]), 4)
    payload["OfflineUnderpowered"] = facts["OfflineUnderpowered"] == "yes"
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def render(facts: dict[str, Any]) -> str:
    lines = [
        "% Generated by scripts/render_suite_facts.py. Do not edit by hand.",
        "% Regenerate after any change to the frozen suite or the offline campaign:",
        "%   python3 scripts/render_suite_facts.py",
        "% The manuscript must cite these macros rather than literal counts, so that a",
        "% suite change cannot leave a stale number in prose.",
    ]
    # A seed is an identifier, not a quantity: 20{,}260{,}816 would be wrong in
    # the same way a thousands-separated commit hash would be.
    identifiers = {"OfflineSuiteSeed"}
    # The analysis-tier enums remain in the machine-readable sidecar and
    # evidence ledgers, but are deliberately absent from reader-facing TeX.
    private_labels = {"OfflineAnalysisAuthority", "OfflineAchievedTier"}
    for key, value in facts.items():
        if key in private_labels:
            continue
        if isinstance(value, int):
            rendered = str(value) if key in identifiers else _fmt_int(value)
        else:
            rendered = str(value).replace("_", "\\_")
        lines.append(f"\\newcommand{{\\{key}}}{{{rendered}}}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    parser.add_argument("--out", type=Path, default=OUTPUT)
    parser.add_argument("--json-out", type=Path, default=OUTPUT_JSON)
    args = parser.parse_args(argv)

    facts = collect()
    text = render(facts)
    text_json = render_json(facts)
    if args.check:
        stale = False
        for label, path, expected in (("SUITE_FACTS", args.out, text), ("SUITE_FACTS_JSON", args.json_out, text_json)):
            if not path.is_file():
                print(f"{label} missing: {path}")
                stale = True
            elif path.read_text(encoding="utf-8") != expected:
                print(f"{label} stale: regenerate with scripts/render_suite_facts.py")
                stale = True
        if stale:
            return 1
        print("SUITE_FACTS ok")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    args.json_out.write_text(text_json, encoding="utf-8")
    print(f"wrote {args.out}")
    print(f"wrote {args.json_out}")
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    raise SystemExit(main())
