"""Exact-study substrate for ORION-EA epistemic autoregression research."""

from .exact_worlds import (
    DeltaKind,
    DeltaOp,
    EdgeKind,
    EpistemicEdge,
    EpistemicIntervention,
    EpistemicNode,
    EpistemicWorld,
    ExactCase,
    ExactFamily,
    FailureScope,
    InterventionKind,
    NodeKind,
    NodeStatus,
    ObligationScope,
    Representation,
    ViewMode,
    apply_delta_with_representation,
    execute_intervention,
    generate_case,
    generate_obligation_hostile_pair,
    generate_representation_hostile_pair,
    generate_suite,
)
from .identifiability import (
    IdentifiabilityCollision,
    IdentifiabilityReport,
    analyze_identifiability,
)

__all__ = [
    "DeltaKind",
    "DeltaOp",
    "EdgeKind",
    "EpistemicEdge",
    "EpistemicIntervention",
    "EpistemicNode",
    "EpistemicWorld",
    "ExactCase",
    "ExactFamily",
    "FailureScope",
    "InterventionKind",
    "NodeKind",
    "NodeStatus",
    "ObligationScope",
    "Representation",
    "ViewMode",
    "IdentifiabilityCollision",
    "IdentifiabilityReport",
    "analyze_identifiability",
    "apply_delta_with_representation",
    "execute_intervention",
    "generate_case",
    "generate_obligation_hostile_pair",
    "generate_representation_hostile_pair",
    "generate_suite",
]
